UPDATE [${dbxschemaname}].[configurations] SET config_value = '["Casual Employee","Full-Time Employee","Part-Time Employee","Contract Employee","Trainee","Self-Employed","Retired","Unemployed"]' WHERE (configuration_id = 'fdcaba3d-7a06-7685-b75e-c689f0c190ke');
GO
UPDATE [${dbxschemaname}].[configurations] SET config_value = '["Accountant","Architect","Artist","Chef","Designer","Dietitian","Economist","Electrician","Engineer","Doctor","Geologist","Hairdresser","Mechanic","Midwife","Musician","Paramedic","Pharmacist","Physician","Physiotherapist","Pilot","Plumber","Psychologist","Scientist","Social Worker","Software Developer","Surgeon","Teacher","Technician","Veterinarian","Firefighter","Military Personnel","Military Veteran","Police Officer","Sailor"]' WHERE (configuration_id = 'fdcaba3d-7a06-7685-a75e-c689f0c290ke');
GO

UPDATE [${dbxschemaname}].[configurations] SET config_value = '{"UserActionName": "EntityCertification","Group": "Documents","Skippable": "false","Title": "Upload Entity Registration Certificate Document (%CompanyName% %CompanyType%)","Title_Key": "EntityCertification_Title","UserActionType": "DocumentUpload","Options": "","OptionsType": "","Description": "Please upload a scanned copy of your Entity Certificate- This will help to process your application faster","Description_Key": "EntityCertification_Description","DynamicDataDefinition": {"PersonalInfo":[{"name":"CompanyName","path":"$.CompanyName"},{"name":"CompanyType","path":"$.CompanyType"}]},"ActionLevel": "Application","NeedsReview": "false","isPreRequirement": "true"}' WHERE (configuration_id = 'SME_98');
UPDATE [${dbxschemaname}].[configurations] SET config_value = '["Accountant","Architect","Artist","Chef","Designer","Dietitian","Economist","Electrician","Engineer","Doctor","Geologist","Hairdresser","Mechanic","Midwife","Musician","Paramedic","Pharmacist","Physician","Physiotherapist","Pilot","Plumber","Psychologist","Scientist","Social Worker","Software Developer","Surgeon","Teacher","Technician","Veterinarian","Firefighter","Military Personnel","Military Veteran","Police Officer","Sailor"]' WHERE (configuration_id = 'fdcaba3d-7a06-7685-a75e-c689f0c290ke');
UPDATE [${dbxschemaname}].[configurations] SET config_value = '["Accountant","Architect","Artist","Chef","Designer","Dietitian","Economist","Electrician","Engineer","Doctor","Geologist","Hairdresser","Mechanic","Midwife","Musician","Paramedic","Pharmacist","Physician","Physiotherapist","Pilot","Plumber","Psychologist","Scientist","Social Worker","Software Developer","Surgeon","Teacher","Technician","Veterinarian","Firefighter","Military Personnel","Military Veteran","Police Officer","Sailor"]' WHERE (configuration_id = 'SME_76');
UPDATE [${dbxschemaname}].[configurations] SET config_value = '["Casual Employee","Full-Time Employee","Part-Time Employee","Contract Employee","Trainee","Self-Employed","Retired","Unemployed"]' WHERE (configuration_id = 'SME_77');
UPDATE [${dbxschemaname}].[configurations] SET config_value = '{"Retail":[{"JOINT.OWNER":"Joint Owner"}],"Business":[{"Owner":"Owner"},{"AUTH.SIGNER":"Authorized Signer"},{"Non Signer":"Non Signer"}]}' WHERE (configuration_id = 'acd7b520-39c3-44be-aed1-389e09c39ded');
UPDATE [${dbxschemaname}].[configurations] set config_value = '{"Retail":[{"JOINT.OWNER":"JOINT OWNER"}],"Business":[{"Owner":"OWNER"},{"AUTH.SIGNER":"Authorized Signer"},{"Non Signer":"NON SIGNER"},{"Guarantor":"Guarantor"},{"Co-Borrower":"Co-Borrower"}]}' WHERE (configuration_id = 'SME_90');
GO