INSERT INTO `currency` (`code`, `name`, `symbol`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('AUD', 'Australian dollar', '$', '2020-05-21 19:12:27', '2020-05-21 19:12:27', '2020-05-21 19:12:27', 0);
INSERT INTO `currency` (`code`, `name`, `symbol`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('CHF', 'Swiss franc', 'Fr', '2020-05-14 19:12:27', '2020-05-14 19:12:27', '2020-05-14 19:12:27', 0);
INSERT INTO `currency` (`code`, `name`, `symbol`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('JPY', 'Japanese yen', '¥', '2020-05-14 19:12:27', '2020-05-14 19:12:27', '2020-05-14 19:12:27', 0);
INSERT INTO `currency` (`code`, `name`, `symbol`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('CAD', 'Canadian dollar', 'C$', '2020-05-14 19:12:27', '2020-05-14 19:12:27', '2020-05-14 19:12:27', 0);
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('23bf1d9c-9c17-11ea-bb37-0242ac130002', 'RBObjects', 'Cards', 'activateCards', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('6f689bb6-9c16-11ea-bb37-0242ac130002', 'RBObjects', 'Accounts', 'GetRecentList', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('6f689dc8-9c16-11ea-bb37-0242ac130002', 'RBObjects', 'SwiftCode', 'getSwiftCode', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('3c3b0b69-5d5c-49d0-95dd-64a6b7d20367', 'RBObjects', 'CardStatements', 'getCardStatements', 'ALLOW');

UPDATE `application` SET `cardStatementYears` = '3' WHERE (`id` = '2');

INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('23b28883-155b-42c3-b458-348d97985952', 'RBObjects', 'CardTransactions', 'getCardTransactions', 'ALLOW');

INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('7f9fe846-76f5-4da2-878b-c4a4fb10867b', 'RBObjects', 'DownloadTransaction','GenerateTransactionReport', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('f74eb5da-c25d-45ed-9cde-dbf035cab2f6', 'TransactionUploadBinary', 'interbankfundtransfers', 'getBinary', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('3a2fb381-25f6-4211-aa43-0fadb6cf9c8f', 'TransactionUploadBinary', 'internationalfundtransfers', 'getBinary', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('06666c54-9f38-4ffc-8629-6027f5553ea4', 'TransactionUploadBinary', 'intrabanktransfers', 'getBinary', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('459cb81f-95e9-41d8-8026-c4a445224d0b', 'TransactionUploadBinary', 'ownaccounttransfers', 'getBinary', 'ALLOW');




INSERT INTO `notification` (`notificationModule`, `notificationSubModule`, `notificationSubject`, `notificationText`, `notificationActionLink`, `imageURL`, `isRead`, `receivedDate`, `notificationCategory`) VALUES ('Account', 'Account', 'Low Balane', 'Your Balance is low', 'ACCOUNT_DASHBOARD', 'https://via.placeholder.com/150', '0', '2020-05-06 18:54:16', 'ACCOUNT');

INSERT INTO `notification` (`notificationModule`, `notificationSubModule`, `notificationSubject`, `notificationText`, `notificationActionLink`, `imageURL`,`isRead`, `receivedDate`, `notificationCategory`) VALUES ('Deals', 'Deals', 'loan offer', 'You have been offered loan', '', 'https://via.placeholder.com/150','0', '2020-05-06 18:54:16', 'CAMPAIGN');


INSERT INTO `notification` (`notificationModule`, `notificationSubModule`, `notificationSubject`, `notificationText`, `notificationActionLink`, `isRead`, `receivedDate`, `notificationCategory`,`actionButtonLabelName`) VALUES ('Account', 'Account', 'password changed', 'Your Password has been changed', 'ACCOUNT_DASHBOARD', '0', '2020-05-06 18:54:16', 'SECURITY','GO TO DASHBOARD');


INSERT INTO `notification` (`notificationModule`, `notificationSubModule`, `notificationSubject`, `notificationText`, `notificationActionLink`, `isRead`, `receivedDate`, `notificationCategory`,`actionButtonLabelName`) VALUES ('Account', 'Account', 'Amount Deducted', '$500 decucted from your account', '', '0', '2020-05-06 18:54:16', 'TRANSACTION','');

INSERT INTO `usernotification` (`notification_id`, `user_id`, `isRead`, `receivedDate`) VALUES (22, '1465037195', '0', '2020-05-14 20:45:00');
INSERT INTO `usernotification` (`notification_id`, `user_id`, `isRead`, `receivedDate`) VALUES (23, '1465037195', '0', '2020-05-14 20:45:00');
INSERT INTO `usernotification` (`notification_id`, `user_id`, `isRead`, `receivedDate`) VALUES (24, '1465037195', '0', '2020-05-14 20:45:00');
INSERT INTO `usernotification` (`notification_id`, `user_id`, `isRead`, `receivedDate`) VALUES (25, '1465037195', '0', '2020-05-14 20:45:00');
UPDATE `application` SET `cardStatementYears` = '1' WHERE (`id` = '2');



UPDATE `card` SET `cvv`='111', `currentBalance`='1000', `rewardsPoint`='250', `availableBalance`='850', `expirationDate`='2025-06-12' WHERE  `Id`=346;
UPDATE `card` SET `cvv`='222',`currentBalance`='3400', `rewardsPoint`='250', `availableBalance`='3150', `expirationDate`='2025-06-11' WHERE  `Id`=347;
UPDATE `card` SET `card_Status`='Issued', `cvv`='333', `rewardsPoint`='550', `expirationDate`='2025-06-15' WHERE  `Id`=348;
INSERT INTO `card` ( `card_Status`, `User_id`, `expirationDate`, `pinNumber`, `cardNumber`, `cardType`, `action`, `creditLimit`, `availableCredit`, `serviceProvider`, `billingAddress`, `cardProductName`, `secondaryCardHolder`, `cardHolderName`, `cvv`, `rewardsPoint`, `account_id`) VALUES ('Active', '1002496540', '2020-06-22', '1580', '5314000000004360', 'Credit', 'Activate', '20000', '8513', 'Master Card', '2076, Burnett Ln, Austin, Texas, 78792', 'My Platinum Credit Card', 'John Doe', 'John Bailey', '444', '550', '190128223244156');
INSERT INTO `card` ( `card_Status`, `User_id`, `expirationDate`, `pinNumber`, `cardNumber`, `cardType`, `action`, `creditLimit`, `availableCredit`, `serviceProvider`, `billingAddress`, `cardProductName`, `secondaryCardHolder`, `cardHolderName`, `cvv`, `rewardsPoint`, `account_id`) VALUES ('Issued', '1002496540', '2025-06-22', '1580', '5314000000004360', 'Credit', 'Activate', '20000', '10000', 'Master Card', '2076, Burnett Ln, Austin, Texas, 78792', 'My Platinum Credit Card', 'John Doe', 'John Bailey', '555', '550', '190128223244156');

UPDATE `card` SET `cvv`='111', `currentBalance`='1000', `rewardsPoint`='250', `availableBalance`='850', `expirationDate`='2025-06-12' WHERE  `Id`=355;
UPDATE `card` SET `cvv`='222',`currentBalance`='3400', `rewardsPoint`='250', `availableBalance`='3150', `expirationDate`='2025-06-11' WHERE  `Id`=356;
UPDATE `card` SET `card_Status`='Issued', `cvv`='333', `rewardsPoint`='550', `expirationDate`='2025-06-15' WHERE  `Id`=357;
INSERT INTO `card` (`card_Status`, `User_id`, `expirationDate`, `pinNumber`, `cardNumber`, `cardType`, `action`, `creditLimit`, `availableCredit`, `serviceProvider`, `billingAddress`, `cardProductName`, `secondaryCardHolder`, `cardHolderName`, `cvv`, `rewardsPoint`, `account_id`) VALUES ('Active', '1033562458', '2020-06-22', '1580', '5314000000004360', 'Credit', 'Activate', '20000', '8513', 'Master Card', '2076, Burnett Ln, Austin, Texas, 78792', 'My Platinum Credit Card', 'John Doe', 'John Bailey', '444', '550', '190128223244156');
INSERT INTO `card` (`card_Status`, `User_id`, `expirationDate`, `pinNumber`, `cardNumber`, `cardType`, `action`, `creditLimit`, `availableCredit`, `serviceProvider`, `billingAddress`, `cardProductName`, `secondaryCardHolder`, `cardHolderName`, `cvv`, `rewardsPoint`, `account_id`) VALUES ('Issued', '1033562458', '2025-06-22', '1580', '5314000000004360', 'Credit', 'Activate', '20000', '10000', 'Master Card', '2076, Burnett Ln, Austin, Texas, 78792', 'My Platinum Credit Card', 'John Doe', 'John Bailey', '555', '550', '190128223244156');

INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for July','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-07');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for August','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-08');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for September','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-09');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for October','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-10');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for November','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-11');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for December','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2019-12');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for July','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-07');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for August','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-08');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for September','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-09');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for October','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-10');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for November','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-11');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for December','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2019-12');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for July','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-07');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for August','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-08');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for September','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-09');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for October','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-10');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for November','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-11');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for December','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2019-12');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for July','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-07');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for August','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-08');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for September','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-09');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for October','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-10');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for November','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-11');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for December','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2019-12');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280205276450,'2020-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4213280203144800,'2020-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',4541982333084990,'2020-01');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for June','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-06');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for May','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-05');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for April','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-04');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for March','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-03');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for February','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-02');
INSERT INTO `cardstatements` (`description`,`statementLink`,`Card_id`,`month`) VALUES ('Statement for January','https://retailbanking1.konycloud.com/dbimages/account-statement-pdf.pdf',5314000000004360,'2020-01');

INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Burger King, Airport', null, 'BURGER KING', 'Sacramento', 'Food & Drinks', 'C', 'T', 'U', 'Burger King, Airport', 'D', '2020-05-16 07:30:02', '-3.25', '124151789', 'USD', null, null, null, 'N', null, null, 'POS99255636', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Burger King, Airport', null, 'BURGER KING', 'Sacramento', 'Food & Drinks', 'C', 'T', 'U', 'Burger King, Airport', 'D', '2020-05-16 07:30:02', '-3.25', '12415178', 'USD', null, null, null, 'N', null, null, 'POS99255636', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-17 20:18:32', '-15.00', '792644856', 'USD', '0.91', 'EUR', '13.65', 'N', null, null, '324678959', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-17 20:18:32', '-15.00', '79264485', 'USD', '0.91', 'EUR', '13.65', 'N', null, null, '324678959', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:24', '-18.00', '923152151', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:24', '-3.00', '923152152', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-08 11:30:23', '-3.00', '923152153', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:24', '-18.00', '923152154', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:24', '-3.00', '923152155', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'SRVC CHGS', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:25', '-0.09', '923153241', 'USD', null, null, null, 'Y', '0.50000', '0.10', 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Sunny Bee SRV CHG', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:25', '-0.02', '923153242', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'SRV CHGS', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-08 11:30:25', '-0.02', '923153243', 'USD', null, null, null, 'Y', '0.50000', '0.01', 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'SRVC CHGS', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:25', '-0.09', '923153244', 'USD', null, null, null, 'Y', '0.50000', '0.10', 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Sunny Bee SRV CHG', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-15 10:03:25', '-0.02', '923153245', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Starbucks', null, 'STARTBUCKS', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Startbucks, Tower plaza', 'D', '2020-05-18 12:30:10', '-1.25', '241252323', 'USD', null, null, null, 'N', null, null, 'QR23524225', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Starbucks', null, 'STARTBUCKS', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Startbucks, Tower plaza', 'D', '2020-05-18 12:30:10', '-1.25', '2412523231', 'USD', null, null, null, 'N', null, null, 'QR23524225', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Starbucks', null, 'STARTBUCKS', 'Sacramento', 'Food & Drinks', 'C', 'T', 'B', 'Startbucks, Tower plaza', 'D', '2020-05-12 10:00:35', '-1.25', '242647758', 'USD', null, null, null, 'N', null, null, 'QR235673888', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Starbucks', null, 'STARTBUCKS', 'Sacramento', 'Food & Drinks', 'C', 'T', 'B', 'Startbucks, Tower plaza', 'D', '2020-05-12 10:00:35', '-1.25', '2426477581', 'USD', null, null, null, 'N', null, null, 'QR235673888', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Starbucks', null, 'STARTBUCKS', 'Sacramento', 'Food & Drinks', 'P', 'T', null, 'Startbucks, Tower plaza', 'D', '2020-05-23 12:30:10', '-3.45', '252626271', 'USD', null, null, null, 'N', null, null, 'QR23521551', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Payment Received', null, 'ACE BANK', 'Sacramento', 'Finance', 'C', 'T', 'B', 'ACE BANK', 'C', '2020-05-13 15:03:24', '350.00', '352362623', 'USD', null, null, null, 'N', null, null, 'OL253536262', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Payment Received', null, 'ACE BANK', 'Sacramento', 'Finance', 'C', 'T', 'B', 'ACE BANK', 'C', '2020-05-13 15:03:24', '350.00', '3523626231', 'USD', null, null, null, 'N', null, null, 'OL253536262', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', 'U', 'Uber Transportation', 'D', '2020-05-16 07:00:10', '-10.00', '2141564637', 'USD', null, null, null, 'N', null, null, '235232637378', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', 'U', 'Uber Transportation', 'D', '2020-05-16 07:00:10', '-10.00', '21415646371', 'USD', null, null, null, 'N', null, null, '235232637378', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Ramsay\'s', null, 'RAMSAY RESTO', 'Sacramento', 'Food & Drinks', 'C', 'T', 'B', 'Ramsay\'s Resto, Beverly Ave', 'D', '2020-05-13 20:15:54', '-125.00', '2532626266', 'USD', null, null, null, 'N', null, null, 'POS367575886', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Ramsay\'s', null, 'RAMSAY RESTO', 'Sacramento', 'Food & Drinks', 'C', 'T', 'B', 'Ramsay\'s Resto, Beverly Ave', 'D', '2020-05-13 20:15:54', '-125.00', '25326262661', 'USD', null, null, null, 'N', null, null, 'POS367575886', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'SRV CHGS', null, 'RAMSAY RESTO', 'Sacramento', 'Food & Drinks', 'C', 'F', 'B', 'Ramsay\'s Resto, Beverly Ave', 'D', '2020-05-13 20:15:54', '-3.13', '2532626268', 'USD', null, null, null, 'Y', '2.50000', '1.25', 'POS367575886', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'SRV CHGS', null, 'RAMSAY RESTO', 'Sacramento', 'Food & Drinks', 'C', 'F', 'B', 'Ramsay\'s Resto, Beverly Ave', 'D', '2020-05-13 20:15:54', '-3.13', '25326262681', 'USD', null, null, null, 'Y', '2.50000', '1.25', 'POS367575886', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-18 07:00:10', '-5.00', '3534643747', 'USD', '0.91', 'EUR', '4.55', 'N', null, null, '6357458488', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-18 18:00:10', '-5.00', '35346437471', 'USD', '0.91', 'EUR', '4.55', 'N', null, null, '6357458488', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-18 07:00:10', '-5.00', '35346437472', 'USD', '0.91', 'EUR', '4.55', 'N', null, null, '6357458488', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Uber', null, 'UBER', 'Manchester', 'Travel', 'C', 'T', 'U', 'Uber UK', 'D', '2020-05-18 18:00:10', '-5.00', '35346437473', 'USD', '0.91', 'EUR', '4.55', 'N', null, null, '6357458488', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'T', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-08 11:30:23', '-3.00', '9231521512', 'USD', null, null, null, 'N', null, null, 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'SRV CHGS', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'C', 'F', 'B', 'Sunny Bee, Clark Ave', 'D', '2020-05-08 11:30:25', '-0.02', '9231532423', 'USD', null, null, null, 'Y', '0.50000', '0.01', 'POS1422', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Total Gas', null, 'TOTAL GAS', 'Sacramento', 'Fuel', 'C', 'T', null, 'Total Gas, Mark St', 'D', '2020-05-14 15:03:24', '-4.00', '15645844848', 'USD', null, null, null, 'N', null, null, 'POS225252', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Total Gas', null, 'TOTAL GAS', 'Sacramento', 'Fuel', 'C', 'T', null, 'Total Gas, Mark St', 'D', '2020-05-14 15:03:24', '-4.00', '1.56458E+11', 'USD', null, null, null, 'N', null, null, 'POS225252', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Total Gas', null, 'TOTAL GAS', 'Sacramento', 'Fuel', 'C', 'T', 'B', 'Total Gas, Mark St', 'D', '2020-05-10 08:05:48', '-8.25', '53536396363', 'USD', null, null, null, 'N', null, null, 'POS225252', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Total Gas', null, 'TOTAL GAS', 'Sacramento', 'Fuel', 'P', 'T', null, 'Total Gas, Mark St', 'D', '2020-05-23 17:30:10', '-6.20', '65745845832', 'USD', null, null, null, 'N', null, null, 'POS222362', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Total Gas', null, 'TOTAL GAS', 'Sacramento', 'Fuel', 'C', 'T', 'B', 'Total Gas, Mark St', 'D', '2020-05-10 08:05:48', '-8.25', '5.35364E+11', 'USD', null, null, null, 'N', null, null, 'POS225252', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', null, 'Uber Transportation', 'D', '2020-05-17 20:18:32', '-4.50', '114141564', 'USD', null, null, null, 'N', null, null, 'POS5315', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', null, 'Uber Transportation', 'D', '2020-05-17 20:18:32', '-4.50', '1141415643', 'USD', null, null, null, 'N', null, null, 'POS5315', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'HardRock Café', null, 'HARDROCK CAFÉ', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Hardrock Café, Marine Drive', 'D', '2020-05-18 17:30:10', '-14.50', '125151252156', 'USD', null, null, null, 'N', null, null, 'POS1423623678', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'HardRock Café', null, 'HARDROCK CAFÉ', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Hardrock Café, Marine Drive', 'D', '2020-05-18 17:30:10', '-14.50', '1251512521561', 'USD', null, null, null, 'N', null, null, 'POS1423623678', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-16 07:00:10', '-45.00', '223246446', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-16 07:00:10', '-45.00', '2232464461', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-08 11:30:23', '-200.00', '2232464463', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-08 11:30:23', '-200.00', '2232464464', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-08 11:30:25', '-2.00', '2232464465', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-08 11:30:25', '-2.00', '2232464466', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Sunny Bee, Clark Ave', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'P', 'T', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-23 10:03:24', '-11.00', '22362722', 'USD', null, null, null, 'N', null, null, 'POS1453', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'SRVC CHGS', null, 'SUNNY BEE', 'Sacramento', 'Grocery', 'P', 'F', null, 'Sunny Bee, Clark Ave', 'D', '2020-05-23 10:03:25', '-0.06', '22362724', 'USD', null, null, null, 'Y', '0.50000', '0.10', 'POS1453', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-16 07:30:02', '-0.80', '225252790', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-16 07:30:02', '-0.80', '22324644678', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Max Life Insurance', null, 'MAX LIFE INSURANCE', 'Sacramento', 'Investment', 'C', 'T', null, 'Maxlife Insurance 242515156', 'D', '2020-05-14 06:00:10', '-550.00', '241241251331613', 'USD', null, null, null, 'N', null, null, 'OL32363623623', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Max Life Insurance', null, 'MAX LIFE INSURANCE', 'Sacramento', 'Investment', 'C', 'T', null, 'Maxlife Insurance 242515156', 'D', '2020-05-14 06:00:10', '-550.00', '22324644698', 'USD', null, null, null, 'N', null, null, 'OL32363623623', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Cosco', null, 'COSCO MART', 'Sacramento', 'Shopping', 'C', 'T', 'U', 'COSCO, US', 'D', '2020-05-20 10:03:24', '-40.00', '241512516361', 'USD', null, null, null, 'N', null, null, 'POS2515167888', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Cosco', null, 'COSCO MART', 'Sacramento', 'Shopping', 'C', 'T', 'U', 'COSCO, US', 'D', '2020-05-20 10:03:24', '-40.00', '2232464460123', 'USD', null, null, null, 'N', null, null, 'POS2515167888', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Coldstone Creamery', null, 'COLDSTONE CREAMERY', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'ColdStone Creamery, Clive St', 'D', '2020-05-13 20:45:54', '-8.30', '315125125215', 'USD', null, null, null, 'N', null, null, 'POS186859542', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Coldstone Creamery', null, 'COLDSTONE CREAMERY', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'ColdStone Creamery, Clive St', 'D', '2020-05-13 20:45:54', '-8.30', '2232464463576', 'USD', null, null, null, 'N', null, null, 'POS186859542', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Apple Music', null, 'APPLE MUSIC', 'Sacramento', 'Entertainment', 'C', 'T', null, 'Apple Music Bill 01114', 'D', '2020-05-18 07:00:10', '-12.00', '323623632636326', 'USD', null, null, null, 'N', null, null, 'OL1515125125', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Apple Music', null, 'APPLE MUSIC', 'Sacramento', 'Entertainment', 'C', 'T', null, 'Apple Music Bill 01114', 'D', '2020-05-18 07:00:10', '-12.00', '2232464461234560987', 'USD', null, null, null, 'N', null, null, 'OL1515125125', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Toys R Us', null, 'TOYS R US', 'Sacramento', 'Shopping', 'C', 'T', null, 'Toysrus, Total Mall', 'D', '2020-05-10 08:05:48', '-15.45', '3252262622', 'USD', null, null, null, 'N', null, null, 'POS532362622', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Toys R Us', null, 'TOYS R US', 'Sacramento', 'Shopping', 'C', 'T', null, 'Toysrus, Total Mall', 'D', '2020-05-10 08:05:48', '-15.45', '32522626221', 'USD', null, null, null, 'N', null, null, 'POS532362622', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Holiday Inn, London', null, 'Holiday INN GROUPS', 'Manchester', 'Accomodation', 'P', 'T', 'U', 'Holiday Inn, UK', 'D', '2020-05-18 17:30:10', '-100.00', '3444853894253785', 'USD', '0.91', 'EUR', '90.98', 'N', null, null, 'POS163789232', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Holiday Inn, London', null, 'Holiday INN GROUPS', 'Manchester', 'Accomodation', 'P', 'T', 'U', 'Holiday Inn, UK', 'D', '2020-05-18 17:30:10', '-390.00', '34448538942537851', 'USD', '0.91', 'EUR', '90.98', 'N', null, null, 'POS163789232', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Old Mac Bakery', null, 'OLD MAC BAKERY', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Old Mac Bakery', 'D', '2020-05-12 10:00:35', '-2.60', '353262623623', 'USD', null, null, null, 'N', null, null, 'POS125162472', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Old Mac Bakery', null, 'OLD MAC BAKERY', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Old Mac Bakery', 'D', '2020-05-12 10:00:35', '-2.60', '3532626236231', 'USD', null, null, null, 'N', null, null, 'POS125162472', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-20 10:03:24', '-200.00', '353734232', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Cash Withdrawal ATM', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-20 10:03:24', '-200.00', '3537342321', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-20 10:03:24', '-1.20', '353734233', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'SRVC CHGS ATM 1%', null, 'ACE BANK ATM', 'Sacramento', 'Finance', 'C', 'T', null, 'Cash WDWL ATM', 'D', '2020-05-20 10:03:24', '-1.20', '3537342331', 'USD', null, null, null, 'N', null, null, 'ATM2527454848', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', 'U', 'Uber Transportation', 'D', '2020-05-19 07:00:10', '-15.00', '354654648', 'USD', null, null, null, 'N', null, null, '991241521515', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'C', 'T', 'U', 'Uber Transportation', 'D', '2020-05-19 07:00:10', '-15.00', '3546546481', 'USD', null, null, null, 'N', null, null, '991241521515', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Pizza Hut', null, 'PIZZA HUT', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Pizza Hut, Clive St', 'D', '2020-05-13 20:15:54', '-5.42', '5326262623626', 'USD', null, null, null, 'N', null, null, 'POS2423262', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Pizza Hut', null, 'PIZZA HUT', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Pizza Hut, Clive St', 'D', '2020-05-13 20:15:54', '-5.42', '53262626236261', 'USD', null, null, null, 'N', null, null, 'POS2423262', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Uber', null, 'UBER', 'Sacramento', 'Travel', 'P', 'T', null, 'Uber Transportation', 'D', '2020-05-23 07:00:10', '-4.00', '5474583232', 'USD', null, null, null, 'N', null, null, '3252362623626', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Pizza Hut', null, 'PIZZA HUT', 'Sacramento', 'Food & Drinks', 'P', 'T', null, 'Pizza Hut, Clive St', 'D', '2020-05-23 20:15:54', '-8.35', '57697425231', 'USD', null, null, null, 'N', null, null, 'POS24221512', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Mark Hospital', null, 'MARK HOSPITAL', 'Sacramento', 'Health', 'C', 'T', null, 'Mark Hospital, Sacramento', 'D', '2020-05-19 18:00:10', '-800.00', '6474262623', 'USD', null, null, null, 'N', null, null, 'POS014166348', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Mark Hospital', null, 'MARK HOSPITAL', 'Sacramento', 'Health', 'C', 'T', null, 'Mark Hospital, Sacramento', 'D', '2020-05-19 18:00:10', '-800.00', '64742626231', 'USD', null, null, null, 'N', null, null, 'POS014166348', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Taco Bell', null, 'TACO BELL', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Taco Bell, Clar Ave', 'D', '2020-05-08 13:03:48', '-3.50', '78346262788', 'USD', null, null, null, 'N', null, null, 'POS166437373', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Taco Bell', null, 'TACO BELL', 'Sacramento', 'Food & Drinks', 'C', 'T', null, 'Taco Bell, Clar Ave', 'D', '2020-05-08 13:03:48', '-3.50', '783462627881', 'USD', null, null, null, 'N', null, null, 'POS166437373', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Amazon US', null, 'AMAZON', 'Sacramento', 'Online', 'P', 'T', null, 'Amazon Online', 'D', '2020-05-23 07:00:10', '-125.00', 'AM02422142', 'USD', null, null, null, 'N', null, null, 'OL943161', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280205276450', 'Amazon US', null, 'AMAZON', 'Sacramento', 'Online', 'C', 'T', null, 'Amazon Online', 'D', '2020-05-19 07:00:10', '-25.00', 'AM02425514', 'USD', null, null, null, 'N', null, null, 'OL94242', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4213280203144800', 'Amazon US', null, 'AMAZON', 'Sacramento', 'Online', 'C', 'T', null, 'Amazon Online', 'D', '2020-05-19 07:00:10', '-25.00', 'AM024255141', 'USD', null, null, null, 'N', null, null, 'OL94242', 'Debit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Amazon US', null, 'AMAZON', 'Sacramento', 'Online Shopping', 'C', 'T', 'B', 'Amazon Online', 'D', '2020-05-08 13:03:48', '-25.00', 'AM0242555', 'USD', null, null, null, 'N', null, null, 'OL94242', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Amazon US', null, 'AMAZON', 'Sacramento', 'Online Shopping', 'C', 'T', 'B', 'Amazon Online', 'D', '2020-05-08 13:03:48', '-25.00', 'AM02425553', 'USD', null, null, null, 'N', null, null, 'OL94242', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Netflix', null, 'NETFLIX', 'Sacramento', 'Entertainment', 'C', 'T', 'B', 'Netflix', 'D', '2020-05-14 06:00:10', '-10.00', 'NF2215262677', 'USD', null, null, null, 'Y', null, null, 'OL21511666', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Netflix', null, 'NETFLIX', 'Sacramento', 'Entertainment', 'C', 'T', 'B', 'Netflix', 'D', '2020-05-14 06:00:10', '-10.00', 'NF22152626771', 'USD', null, null, null, 'Y', null, null, 'OL21511666', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('4541982333084990', 'Ormer Mayfair', null, 'ORMER GROUPS', 'Manchester', 'Food & Drinks', 'P', 'T', 'U', 'Ormer Mayfair, Piccadilly', 'D', '2020-05-18 12:30:10', '-380.00', 'OM124151626', 'USD', '0.91', 'EUR', '345.72', 'N', null, null, 'POS9215151', 'Credit');
INSERT INTO `cardtransaction` (`cardNumber`, `transactionDescription`, `transactionBalance`, `transactionMerchantAddressName`, `transactionMerchantCity`, `merchantCategory`, `transactionStatus`, `transactionType`, `transactionCategory`, `transactionDetailDescription`, `transactionIndicator`, `transactionDate`, `transactionAmount`, `transactionReferenceNumber`, `transactionCurrencyCode`, `transactionExchangeRate`, `exchangeCurrency`, `exchangeAmount`, `transactionTaxIndicator`, `taxPercentage`, `transactionTaxAmount`, `transactionTerminalID`, `cardType`) VALUES ('5314000000004360', 'Ormer Mayfair', null, 'ORMER GROUPS', 'Manchester', 'Food & Drinks', 'P', 'T', 'U', 'Ormer Mayfair, Piccadilly', 'D', '2020-05-18 12:30:10', '-580.00', 'OM1241516261', 'USD', '0.91', 'EUR', '345.72', 'N', null, null, 'POS9215151', 'Credit');

UPDATE `notification` SET `notificationCategory`='ALERT_CAT_TRANSACTIONAL' WHERE  `notificationId`=12;
UPDATE `notification` SET `notificationCategory`='ALERT_CAT_TRANSACTIONAL' WHERE  `notificationId`=8;
UPDATE `notification` SET `notificationCategory`='ALERT_CAT_TRANSACTIONAL' WHERE  `notificationId`=19;
UPDATE `notification` SET `notificationCategory`='ALERT_CAT_ACCOUNTS' WHERE  `notificationId`=20;


UPDATE `notification` SET `notificationActionLink`='ACCOUNT_DASHBOARD', `actionButtonLabelName`='Go To Dashboard' WHERE  `notificationId`=20;

INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('28bh1d9c-5h37-13fs-ee37-0244fc130002', 'RBObjects', 'Cards', 'updateWithdrawalLimit', 'ALLOW');
INSERT INTO `service_permission_mapper` (`id`, `service_name`, `object_name`, `operation`, `permissions`) VALUES ('8fh87bb6-7g16-12ed-fb57-0565gh171108', 'RBObjects', 'Cards', 'updatePurchaseLimit', 'ALLOW');
