######
#
# Object Linked to MS hat don't need Legal Entity ID
#
######
Temenos.MultiEntity.MS_EXCLUSION_LIST = CampaignManagementMS,ProductManagementFromMS,ProductManagamentMS,ProductAndFacilityManagement,ProductManagement