######
#
# T24 properties# 
# For spotlight we can ignore username & userid fields as we will be always working POSTLOGIN scenarios
######
Temenos.Enrollment.PreLoginUserName = T24
Temenos.Enrollment.PreLoginUserId = 0001
Temenos.General.CampaignRoleId = ADMIN
Temenos.General.ORDMSRoleId = ADMIN
Temenos.General.MarketingCatalogueRoleId = ADMIN
Temenos.General.T24RoleId = INFINITY.RETAIL
Temenos.General.ConsentRoleId =  ADMIN
Temenos.General.DocumentOwner =  DocumentOwner
