GO
INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('RECEIVED_GUARANTEES', 'RETAIL_AND_BUSINESS_BANKING', 'Received Guarantees', 'View & Manage the Received Guarantees', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_UPDATE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'RECEIVED_GUARANTEES', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_VIEW', 'View the Received Guarantees', 'View the Received Guarantees', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'RECEIVED_GUARANTEES', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_UPDATE', 'Manage the Received Guarantees', 'View the Received Guarantees', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_UPDATE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES', 'en-GB', 'RECEIVED GUARANTEES', 'View & Manage the Received Guarantees', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES', 'en-US', 'RECEIVED GUARANTEES', 'View & Manage the Received Guarantees', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'de-DE', 'Received Guarantees View', 'Received Guarantees View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'en-GB', 'Received Guarantees View', 'Received Guarantees View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'en-US', 'Received Guarantees View', 'Received Guarantees View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'es-ES', 'Received Guarantees View', 'Received Guarantees View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_VIEW', 'fr-FR', 'Received Guarantees View', 'Received Guarantees View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'de-DE', 'Received Guarantees Update', 'Received Guarantees Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'en-GB', 'Received Guarantees Update', 'Received Guarantees Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'en-US', 'Received Guarantees Update', 'Received Guarantees Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'es-ES', 'Received Guarantees Update', 'Received Guarantees Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_UPDATE', 'fr-FR', 'Received Guarantees Update', 'Received Guarantees Update') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141003', 'TradeFinance', 'ReceivedGuarantees', 'getGuarantees', 'RECEIVED_GUARANTEES_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm142003', 'TradeFinance', 'ReceivedGuarantees', 'getGuaranteeById', 'RECEIVED_GUARANTEES_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm143003', 'TradeFinance', 'ReceivedGuarantees', 'generateGuaranteeReport', 'RECEIVED_GUARANTEES_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm144003', 'TradeFinance', 'ReceivedGuarantees', 'generateGuaranteesList', 'RECEIVED_GUARANTEES_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm145003', 'TradeFinance', 'ReceivedGuarantees', 'updateGuarantee', 'RECEIVED_GUARANTEES_UPDATE');


INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('RECEIVED_GUARANTEES_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'Received Guarantees Amendements', 'View & Manage the Received Guarantees Amendements', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'RECEIVED_GUARANTEES_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'View the Received Guarantees Amendements', 'View the Received Guarantees Amendements', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'RECEIVED_GUARANTEES_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'Manage the Received Guarantees Amendements', 'Manage the Received Guarantees Amendements', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS', 'en-GB', 'RECEIVED GUARANTEES AMENDMENTS', 'View & Manage the Received Guarantees Amendements', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS', 'en-US', 'RECEIVED GUARANTEES AMENDMENTS', 'View & Manage the Received Guarantees Amendements', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_AMENDMENTS') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'de-DE', 'Received Guarantees Amendements View', 'Received Guarantees Amendements View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'en-GB', 'Received Guarantees Amendements View', 'Received Guarantees Amendements View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'en-US', 'Received Guarantees Amendements View', 'Received Guarantees Amendements View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'es-ES', 'Received Guarantees Amendements View', 'Received Guarantees Amendements View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_VIEW', 'fr-FR', 'Received Guarantees Amendements View', 'Received Guarantees Amendements View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'de-DE', 'Received Guarantees Amendements Update', 'Received Guarantees Amendements Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'en-GB', 'Received Guarantees Amendements Update', 'Received Guarantees Amendements Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'en-US', 'Received Guarantees Amendements Update', 'Received Guarantees Amendements Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'es-ES', 'Received Guarantees Amendements Update', 'Received Guarantees Amendements Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_AMENDMENTS_UPDATE', 'fr-FR', 'Received Guarantees Amendements Update', 'Received Guarantees Amendements Update') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm146003', 'TradeFinance', 'ReceivedGuarantees', 'getAmendments', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm147003', 'TradeFinance', 'ReceivedGuarantees', 'getAmendmentById', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm148003', 'TradeFinance', 'ReceivedGuarantees', 'generateAmendmentReport', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm149003', 'TradeFinance', 'ReceivedGuarantees', 'generateAmendmentsList', 'RECEIVED_GUARANTEES_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141103', 'TradeFinance', 'ReceivedGuarantees', 'updateAmendment', 'RECEIVED_GUARANTEES_AMENDMENTS_UPDATE');


INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('RECEIVED_GUARANTEES_CLAIMS', 'RETAIL_AND_BUSINESS_BANKING', 'Received Guarantees Claims', 'Create View & Manage the Received Guarantees Claims', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'RECEIVED_GUARANTEES_CLAIMS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', 'Create the Received Guarantees Claims', 'Create the Received Guarantees Claims', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'RECEIVED_GUARANTEES_CLAIMS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', 'View the Received Guarantees Claims', 'View the Received Guarantees Claims', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'RECEIVED_GUARANTEES_CLAIMS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'Update the Received Guarantees Claims', 'Update the Received Guarantees Claims', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'RECEIVED_GUARANTEES_CLAIMS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', 'Delete the Received Guarantees Claims', 'Delete the Received Guarantees Claims', 1, 0, null, 0, 10, null, 0, 'DELETE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_CLAIMS_CREATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_CLAIMS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'RECEIVED_GUARANTEES_CLAIMS_DELETE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS', 'en-GB', 'RECEIVED_GUARANTEES_CLAIMS', 'Create View & Manage the Received Guarantees Claims', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('RECEIVED_GUARANTEES_CLAIMS', 'en-US', 'RECEIVED_GUARANTEES_CLAIMS', 'Create View & Manage the Received Guarantees Claims', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'RECEIVED_GUARANTEES_CLAIMS') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'de-DE', 'Received Guarantees Claims Create', 'Received Guarantees Claims Create') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'en-GB', 'Received Guarantees Claims Create', 'Received Guarantees Claims Create') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'en-US', 'Received Guarantees Claims Create', 'Received Guarantees Claims Create') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'es-ES', 'Received Guarantees Claims Create', 'Received Guarantees Claims Create') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_CREATE', 'fr-FR', 'Received Guarantees Claims Create', 'Received Guarantees Claims Create') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'de-DE', 'Received Guarantees Claims View', 'Received Guarantees Claims View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'en-GB', 'Received Guarantees Claims View', 'Received Guarantees Claims View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'en-US', 'Received Guarantees Claims View', 'Received Guarantees Claims View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'es-ES', 'Received Guarantees Claims View', 'Received Guarantees Claims View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_VIEW', 'fr-FR', 'Received Guarantees Claims View', 'Received Guarantees Claims View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'de-DE', 'Received Guarantees Claims Update', 'Received Guarantees Claims Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'en-GB', 'Received Guarantees Claims Update', 'Received Guarantees Claims Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'en-US', 'Received Guarantees Claims Update', 'Received Guarantees Claims Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'es-ES', 'Received Guarantees Claims Update', 'Received Guarantees Claims Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_UPDATE', 'fr-FR', 'Received Guarantees Claims Update', 'Received Guarantees Claims Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'de-DE', 'Received Guarantees Claims Delete', 'Received Guarantees Claims Delete') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'en-GB', 'Received Guarantees Claims Delete', 'Received Guarantees Claims Delete') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'en-US', 'Received Guarantees Claims Delete', 'Received Guarantees Claims Delete') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'es-ES', 'Received Guarantees Claims Delete', 'Received Guarantees Claims Delete') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('RECEIVED_GUARANTEES_CLAIMS_DELETE', 'fr-FR', 'Received Guarantees Claims Delete', 'Received Guarantees Claims Delete') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141203', 'TradeFinance', 'ReceivedGuarantees', 'CreateGuaranteeClaims', 'RECEIVED_GUARANTEES_CLAIMS_CREATE');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141303', 'TradeFinance', 'ReceivedGuarantees', 'SaveGuaranteeClaims', 'RECEIVED_GUARANTEES_CLAIMS_CREATE');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141403', 'TradeFinance', 'ReceivedGuarantees', 'GetGuaranteeClaims', 'RECEIVED_GUARANTEES_CLAIMS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141503', 'TradeFinance', 'ReceivedGuarantees', 'GetGuaranteeClaimsById', 'RECEIVED_GUARANTEES_CLAIMS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141603', 'TradeFinance', 'ReceivedGuarantees', 'generateReceivedGuaranteeClaim', 'RECEIVED_GUARANTEES_CLAIMS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141703', 'TradeFinance', 'ReceivedGuarantees', 'generateClaimsList', 'RECEIVED_GUARANTEES_CLAIMS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141803', 'TradeFinance', 'ReceivedGuarantees', 'UpdateReceivedGuaranteeClaim', 'RECEIVED_GUARANTEES_CLAIMS_UPDATE');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm141903', 'TradeFinance', 'ReceivedGuarantees', 'deleteGuaranteeClaim', 'RECEIVED_GUARANTEES_CLAIMS_DELETE');
GO

INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('RGUA_1', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'RECEIVED_GUARANTEE_STATUS', 'Received Guarantee Status', '[{\"DisplayStatus\":\"Pending Requests\",\"LCStatus\":[\"Pending Cust Auth\",\"Returned Cust Auth\",\"Submitted to Bank\",\"Returned by Bank\",\"Processing with Bank\",\"New\"]},{\"DisplayStatus\":\"Approved\",\"LCStatus\":[\"Approved\",\"Claim Extended\"]},{\"DisplayStatus\":\"Claim Honoured\",\"LCStatus\":[\"Claim Honoured\"]},{\"DisplayStatus\":\"Rejected\",\"LCStatus\":[\"Rejected\"]}]', 'CLIENT', '1');

GO
ALTER TABLE [${dbxschemaname}].[intrabankpayee] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[internationalpayee] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[interbankpayee] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[billpaypayee] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[p2ppayee] ADD [legalEntityId] VARCHAR(50) NULL;
GO

GO
INSERT INTO  [${dbxschemaname}].[rrole]([id]) VALUES ('CHANGE_REPAYMENT_DAY-CREATE');
INSERT INTO  [${dbxschemaname}].[rrole]([id]) VALUES ('CHANGE_REPAYMENT_DAY-VIEW');
INSERT INTO  [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [DisplaySequence], [isPrimary]) VALUES ('CHANGE_REPAYMENT_DAY', 'RETAIL_AND_BUSINESS_BANKING', 'Change Repayment Day', 'Change Repayment Day', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', '81', '0');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY', 'en-GB', 'Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY', 'de-DE', 'Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY', 'en-US', 'Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY', 'es-ES', 'Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY', 'fr-FR', 'Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS','CHANGE_REPAYMENT_DAY');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_WEALTH','CHANGE_REPAYMENT_DAY');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_RETAIL','CHANGE_REPAYMENT_DAY');
INSERT INTO [${dbxschemaname}].[featureaction]([id],[Feature_id],[App_id],[Type_id],[Rrole_id],[name],[description],[isAccountLevel],[isMFAApplicable],[isPrimary],[DisplaySequence],[createdts],[lastmodifiedts],[synctimestamp],[softdeleteflag],[status],[accesspolicyId],[actionlevelId]) VALUES ('CHANGE_REPAYMENT_DAY-CREATE' ,'CHANGE_REPAYMENT_DAY' ,'RETAIL_AND_BUSINESS_BANKING' ,'NON_MONETARY' ,'CHANGE_REPAYMENT_DAY-CREATE' ,'Create Change Repayment Day' ,'Create Change Repayment Day' ,'0', '0', '0', '10', GETDATE(), GETDATE(), GETDATE(),'0','SID_ACTION_ACTIVE','VIEW','CUSTOMERID_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id],[Feature_id],[App_id],[Type_id],[Rrole_id],[name],[description],[isAccountLevel],[isMFAApplicable],[isPrimary],[DisplaySequence],[createdts],[lastmodifiedts],[synctimestamp],[softdeleteflag],[status],[accesspolicyId],[actionlevelId]) VALUES ('CHANGE_REPAYMENT_DAY-VIEW' ,'CHANGE_REPAYMENT_DAY' ,'RETAIL_AND_BUSINESS_BANKING' ,'NON_MONETARY' ,'CHANGE_REPAYMENT_DAY-VIEW' ,'View Change Repayment Day' ,'View Change Repayment Day' ,'0', '0', '0', '10', GETDATE(), GETDATE(), GETDATE(),'0','SID_ACTION_ACTIVE','VIEW','CUSTOMERID_LEVEL') ;
INSERT INTO  [${dbxschemaname}].[actiondisplaynamedescription]([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY-CREATE','en-US','Create Change Repayment Day', 'Create Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[actiondisplaynamedescription]([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_DAY-VIEW','en-US','View Change Repayment Day', 'View Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_BUSINESS','CHANGE_REPAYMENT_DAY-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_WEALTH','CHANGE_REPAYMENT_DAY-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_RETAIL','CHANGE_REPAYMENT_DAY-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_BUSINESS','CHANGE_REPAYMENT_DAY-VIEW');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_WEALTH','CHANGE_REPAYMENT_DAY-VIEW');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_RETAIL','CHANGE_REPAYMENT_DAY-VIEW');
INSERT INTO  [${dbxschemaname}].[dependentactions]([actionId], [dependentactionId], [featureId], [actionName], [featureName]) VALUES ('CHANGE_REPAYMENT_DAY-CREATE', 'CHANGE_REPAYMENT_DAY-CREATE', 'CHANGE_REPAYMENT_DAY', 'Create Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[dependentactions]([actionId], [dependentactionId], [featureId], [actionName], [featureName]) VALUES ('CHANGE_REPAYMENT_DAY-VIEW', 'CHANGE_REPAYMENT_DAY-VIEW', 'CHANGE_REPAYMENT_DAY', 'View Change Repayment Day', 'Change Repayment Day');
INSERT INTO  [${dbxschemaname}].[compositeaction]([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID355', 'PID45', 'CHANGE_REPAYMENT_DAY-CREATE', 'CHANGE_REPAYMENT_DAY', '1');
INSERT INTO  [${dbxschemaname}].[compositeaction]([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID356', 'PID45', 'CHANGE_REPAYMENT_DAY-VIEW', 'CHANGE_REPAYMENT_DAY', '1');

INSERT INTO  [${dbxschemaname}].[rrole]([id]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-CREATE');
INSERT INTO  [${dbxschemaname}].[rrole]([id]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-VIEW');
INSERT INTO  [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [DisplaySequence], [isPrimary]) VALUES ('REPAYMENT_ACCOUNT', 'RETAIL_AND_BUSINESS_BANKING', 'Change Repayment Account', 'Change Repayment Account', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', '82', '0');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('REPAYMENT_ACCOUNT', 'en-GB', 'Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('REPAYMENT_ACCOUNT', 'de-DE', 'Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('REPAYMENT_ACCOUNT', 'en-US', 'Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('REPAYMENT_ACCOUNT', 'es-ES', 'Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id], [Locale_id], [displayName], [displayDescription]) VALUES ('REPAYMENT_ACCOUNT', 'fr-FR', 'Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS','REPAYMENT_ACCOUNT');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_WEALTH','REPAYMENT_ACCOUNT');
INSERT INTO  [${dbxschemaname}].[featureroletype]([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_RETAIL','REPAYMENT_ACCOUNT');
INSERT INTO [${dbxschemaname}].[featureaction]([id],[Feature_id],[App_id],[Type_id],[Rrole_id],[name],[description],[isAccountLevel],[isMFAApplicable],[isPrimary],[DisplaySequence],[createdts],[lastmodifiedts],[synctimestamp],[softdeleteflag],[status],[accesspolicyId],[actionlevelId]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-CREATE' ,'REPAYMENT_ACCOUNT' ,'RETAIL_AND_BUSINESS_BANKING' ,'NON_MONETARY' ,'CHANGE_REPAYMENT_ACCOUNT-CREATE' ,'Create Change Repayment Account' ,'Create Change Repayment Account' ,'0', '0', '0', '10', GETDATE(), GETDATE(), GETDATE(),'0','SID_ACTION_ACTIVE','VIEW','CUSTOMERID_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id],[Feature_id],[App_id],[Type_id],[Rrole_id],[name],[description],[isAccountLevel],[isMFAApplicable],[isPrimary],[DisplaySequence],[createdts],[lastmodifiedts],[synctimestamp],[softdeleteflag],[status],[accesspolicyId],[actionlevelId]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-VIEW' ,'REPAYMENT_ACCOUNT' ,'RETAIL_AND_BUSINESS_BANKING' ,'NON_MONETARY' ,'CHANGE_REPAYMENT_ACCOUNT-VIEW' ,'View Change Repayment Account' ,'View Change Repayment Account' ,'0', '0', '0', '10', GETDATE(), GETDATE(), GETDATE(),'0','SID_ACTION_ACTIVE','VIEW','CUSTOMERID_LEVEL') ;
INSERT INTO  [${dbxschemaname}].[actiondisplaynamedescription]([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-CREATE','en-US','Create Change Repayment Account', 'Create Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[actiondisplaynamedescription]([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-VIEW','en-US','View Change Repayment Account', 'View Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_BUSINESS','CHANGE_REPAYMENT_ACCOUNT-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_WEALTH','CHANGE_REPAYMENT_ACCOUNT-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_RETAIL','CHANGE_REPAYMENT_ACCOUNT-CREATE');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_BUSINESS','CHANGE_REPAYMENT_ACCOUNT-VIEW');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_WEALTH','CHANGE_REPAYMENT_ACCOUNT-VIEW');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_RETAIL','CHANGE_REPAYMENT_ACCOUNT-VIEW');
INSERT INTO  [${dbxschemaname}].[dependentactions]([actionId], [dependentactionId], [featureId], [actionName], [featureName]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-CREATE', 'CHANGE_REPAYMENT_ACCOUNT-CREATE', 'REPAYMENT_ACCOUNT', 'Create Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[dependentactions]([actionId], [dependentactionId], [featureId], [actionName], [featureName]) VALUES ('CHANGE_REPAYMENT_ACCOUNT-VIEW', 'CHANGE_REPAYMENT_ACCOUNT-VIEW', 'REPAYMENT_ACCOUNT', 'View Change Repayment Account', 'Change Repayment Account');
INSERT INTO  [${dbxschemaname}].[compositeaction]([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID357', 'PID45', 'CHANGE_REPAYMENT_ACCOUNT-CREATE', 'REPAYMENT_ACCOUNT', '1');
INSERT INTO  [${dbxschemaname}].[compositeaction]([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID358', 'PID45', 'CHANGE_REPAYMENT_ACCOUNT-VIEW', 'REPAYMENT_ACCOUNT', '1');

INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('CLAIMS_RECEIVED', 'RETAIL_AND_BUSINESS_BANKING', 'Claims Received', 'View & Manage the Claims Received', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('CLAIMS_RECEIVED_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('CLAIMS_RECEIVED_UPDATE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('CLAIMS_RECEIVED_VIEW', 'CLAIMS_RECEIVED', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'CLAIMS_RECEIVED_VIEW', 'View the Claims Received', 'View the Claims Received', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'CLAIMS_RECEIVED', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'CLAIMS_RECEIVED_UPDATE', 'Manage the Claims Received', 'View the Claims Received', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'CLAIMS_RECEIVED_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'CLAIMS_RECEIVED_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'CLAIMS_RECEIVED_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'CLAIMS_RECEIVED_UPDATE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'CLAIMS_RECEIVED_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'CLAIMS_RECEIVED_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'CLAIMS_RECEIVED_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'CLAIMS_RECEIVED_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'CLAIMS_RECEIVED_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'CLAIMS_RECEIVED_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('CLAIMS_RECEIVED', 'en-GB', 'CLAIMS RECEIVED', 'View & Manage the Claims Received', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('CLAIMS_RECEIVED', 'en-US', 'CLAIMS RECEIVED', 'View & Manage the Claims Received', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'CLAIMS_RECEIVED') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_VIEW', 'de-DE', 'Claims Received View', 'Claims Received View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_VIEW', 'en-GB', 'Claims Received View', 'Claims Received View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_VIEW', 'en-US', 'Claims Received View', 'Claims Received View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_VIEW', 'es-ES', 'Claims Received View', 'Claims Received View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_VIEW', 'fr-FR', 'Claims Received View', 'Claims Received View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'de-DE', 'Claims Receiveds Update', 'Claims Received Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'en-GB', 'Claims Received Update', 'Claims Received Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'en-US', 'Claims Received Update', 'Claims Received Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'es-ES', 'Claims Received Update', 'Claims Received Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('CLAIMS_RECEIVED_UPDATE', 'fr-FR', 'Claims Received Update', 'Claims Received Update') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151003', 'TradeFinance', 'ClaimsReceived', 'getClaims', 'CLAIMS_RECEIVED_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm152003', 'TradeFinance', 'ClaimsReceived', 'getClaimById', 'CLAIMS_RECEIVED_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm153003', 'TradeFinance', 'ClaimsReceived', 'generateClaimReport', 'CLAIMS_RECEIVED_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm154003', 'TradeFinance', 'ClaimsReceived', 'generateClaimsList', 'CLAIMS_RECEIVED_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm155003', 'TradeFinance', 'ClaimsReceived', 'updateClaim', 'CLAIMS_RECEIVED_UPDATE');

INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('INWARD_COLLECTIONS', 'RETAIL_AND_BUSINESS_BANKING', 'Inward Collections', 'View & Manage the Inward Collections', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_UPDATE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('INWARD_COLLECTIONS_VIEW', 'INWARD_COLLECTIONS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INWARD_COLLECTIONS_VIEW', 'View the Inward Collections', 'View the Inward Collections', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'INWARD_COLLECTIONS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INWARD_COLLECTIONS_UPDATE', 'Manage the Inward Collections', 'View the Inward Collections', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'INWARD_COLLECTIONS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'INWARD_COLLECTIONS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'INWARD_COLLECTIONS_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'INWARD_COLLECTIONS_UPDATE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INWARD_COLLECTIONS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INWARD_COLLECTIONS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INWARD_COLLECTIONS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INWARD_COLLECTIONS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS', 'en-GB', 'INWARD COLLECTIONS', 'View & Manage the Inward Collections', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS', 'en-US', 'INWARD COLLECTIONS', 'View & Manage the Inward Collections', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_VIEW', 'de-DE', 'Inward Collections View', 'Inward Collections View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_VIEW', 'en-GB', 'Inward Collections View', 'Inward Collections View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_VIEW', 'en-US', 'Inward Collections View', 'Inward Collections View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_VIEW', 'es-ES', 'Inward Collections View', 'Inward Collections View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_VIEW', 'fr-FR', 'Inward Collections View', 'Inward Collections View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'de-DE', 'Inward Collections Update', 'Inward Collections Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'en-GB', 'Inward Collections Update', 'Inward Collections Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'en-US', 'Inward Collections Update', 'Inward Collections Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'es-ES', 'Inward Collections Update', 'Inward Collections Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_UPDATE', 'fr-FR', 'Inward Collections Update', 'Inward Collections Update') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm156003', 'TradeFinance', 'InwardCollections', 'getCollections', 'INWARD_COLLECTIONS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm157003', 'TradeFinance', 'InwardCollections', 'getCollectionById', 'INWARD_COLLECTIONS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm158003', 'TradeFinance', 'InwardCollections', 'generateInwardCollectionReport', 'INWARD_COLLECTIONS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm159003', 'TradeFinance', 'InwardCollections', 'generateInwardCollectionsList', 'INWARD_COLLECTIONS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151103', 'TradeFinance', 'InwardCollections', 'updateInwardCollection', 'INWARD_COLLECTIONS_UPDATE');

INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence], [isPrimary], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])VALUES ('INWARD_COLLECTIONS_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'Inward Collections Amendments', 'View & Manage the Inward Collections Amendments', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', null, null, 0 , null, null, GETDATE(), GETDATE(), GETDATE(), 0) ;

INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', GETDATE(), GETDATE(), 0);
INSERT INTO [${dbxschemaname}].[rrole] ([id], [createdts], [lastmodifiedts], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), 0);

INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'INWARD_COLLECTIONS_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'View the Inward Collections Amendments', 'View the Inward Collections Amendments', 1, 0, null, 0, 10, null, 0, 'VIEW', 'ACCOUNT_LEVEL') ;
INSERT INTO [${dbxschemaname}].[featureaction]([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isMFAApplicable], [MFA_id], [isPrimary], [DisplaySequence], [dependency], [softdeleteflag], [accesspolicyId], [actionlevelId]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'INWARD_COLLECTIONS_AMENDMENTS', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'Manage the Inward Collections Amendments', 'View the Inward Collections Amendments', 1, 0, null, 0, 10, null, 0, 'CREATE', 'ACCOUNT_LEVEL') ;

INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_ADMINISTRATOR', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', null, null, 'UID11', null, 0);
INSERT INTO [${dbxschemaname}].[groupactionlimit]([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [modifiedby], [softdeleteflag]) VALUES (NEWID(), 'GROUP_CREATOR', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', null, null, 'UID11', null, 0);

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', null, null, GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', null, null, GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (NEWID(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE', GETDATE(), GETDATE(), GETDATE(), '0');

INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS', 'en-GB', 'INWARD COLLECTIONS AMENDMENTS', 'View & Manage the Inward Collections', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription] ([Feature_id], [Locale_id], [displayName], [displayDescription], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS', 'en-US', 'INWARD COLLECTIONS AMENDMENTS', 'View & Manage the Inward Collections', null, null, GETDATE(), GETDATE(), GETDATE(), '0') ;

INSERT INTO [${dbxschemaname}].[featureroletype] ([RoleType_id], [Feature_id]) VALUES ('TYPE_ID_BUSINESS', 'INWARD_COLLECTIONS_AMENDMENTS') ;

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'de-DE', 'Inward Collections Amendments View', 'Inward Collections Amendments View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'en-GB', 'Inward Collections Amendments View', 'Inward Collections Amendments View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'en-US', 'Inward Collections Amendments View', 'Inward Collections Amendments View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'es-ES', 'Inward Collections Amendments View', 'Inward Collections Amendments View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_VIEW', 'fr-FR', 'Inward Collections Amendments View', 'Inward Collections Amendments View') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'de-DE', 'Inward Collections Amendments Update', 'Inward Collections Amendments Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'en-GB', 'Inward Collections Amendments Update', 'Inward Collections Amendments Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'en-US', 'Inward Collections Amendments Update', 'Inward Collections Amendments Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'es-ES', 'Inward Collections Amendments Update', 'Inward Collections Amendments Update') ;
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('INWARD_COLLECTIONS_AMENDMENTS_UPDATE', 'fr-FR', 'Inward Collections Amendments Update', 'Inward Collections Amendments Update') ;

INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151203', 'TradeFinance', 'InwardCollections', 'getInwardCollectionsAmendments', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151303', 'TradeFinance', 'InwardCollections', 'getInwardCollectionsAmendmentById', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151403', 'TradeFinance', 'InwardCollections', 'generateAmendmentReport', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151503', 'TradeFinance', 'InwardCollections', 'generateAmendmentsList', 'INWARD_COLLECTIONS_AMENDMENTS_VIEW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper]([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7qx7kia-4125-11yc-839j-0242lm151603', 'TradeFinance', 'InwardCollections', 'updateInwardCollectionAmendment', 'INWARD_COLLECTIONS_AMENDMENTS_UPDATE');


UPDATE [${dbxschemaname}].[featureaction] SET [isAccountLevel] = '0' WHERE ([id] = 'VIEW_DOCUMENTS');


GO
ALTER TABLE [${dbxschemaname}].[transaction] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[ownaccounttransfers] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[intrabanktransfers] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[interbankfundtransfers] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[internationalfundtransfers] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[p2ptransfers] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[recentcurrencies] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[billpaytransfers] ADD [legalEntityId] VARCHAR(50) NULL;

GO
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('INCL_1', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'INWARDCOLLECTIONS_STATUS', 'Inward Collections Status', '[{\"DisplayStatus\":\"Pending requests\",\"InwardStatus\":[\"New\",\"Processing by Bank\",\"Submitted to Bank\",\"Overdue\",\"Pay Due\",\"Returned by Bank\"]},{\"DisplayStatus\":\"Approved\",\"InwardStatus\":[\"Approved\"]},{\"DisplayStatus\":\"Settled\",\"InwardStatus\":[\"Settled\"]},{\"DisplayStatus\":\"Rejected\",\"InwardStatus\":[\"Rejected\"]}]', 'CLIENT', '1');
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('INCL_2', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'INWARDCOLLECTIONS_TENOR_TYPE', 'Inward Collections Tenor Type', '[{\"type\":\"sight\",\"colorCode\":\"#FF8600\"},{\"type\":\"usance\",\"colorCode\":\"#229EAE\"}]', 'CLIENT', '1');
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('INCL_3', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'INWARDCOLLECTIONS_CHART_DATA', 'Inward Collections Chart Data', '[{\"DisplayStatus\":\"Processing\",\"InwardStatus\":[\"New\",\"Processing by Bank\",\"Submitted to Bank\",\"Overdue\",\"Pay Due\"]},{\"DisplayStatus\":\"Approved\",\"InwardStatus\":[\"Approved\",\"Settled\"]}]', 'CLIENT', '1');

GO
ALTER TABLE [${dbxschemaname}].[bulkpaymenttemplate] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[bulkpaymenttemplatepos] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[bulkpaymentrequest] ADD [legalEntityId] VARCHAR(50) NULL;
ALTER TABLE [${dbxschemaname}].[bulkpaymentrequestpos] ADD [legalEntityId] VARCHAR(50) NULL;

GO
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('C360_ROLE_MAPPING1','C360_CONFIG_BUNDLE','PREFERENCE' ,'LE23698574_CUSTOMER_ROLE_MAPPING','Mapping T24 and customer role','{"MINOR.UGMA":"GID_CREDITCARD_CUSTOMERS", "F.SURVIVOR":"4dd6183f-61d2-410f-8a4f-871af67ac933", "DBA":"GROUP_PLATINUM", "PARTICIPANT":"GROUP_PLATINUM", "IRA.OWNER":"DEFAULT_EUROPE_GROUP", "US.BENE.POD.CONT":"DEFAULT_EUROPE_GROUP", "SUB.PARTICIPANT":"GROUP_CREATOR", "LEGAL.OWNER":"GID_BANKING_CUSTOMERS", "MINOR.UTMA":"GID_HNW_CUSTOMERS", "AGENT":"GROUP_AUTHORIZER", "INSTRUCTING.PARTY":"GROUP_AUTHORIZER", "OWNER":"GID_PRIORITY_MEMBERS", "AUTH.SIGNER":"DEFAULT_EUROPE_GROUP", "BENE.IRREV.TRUST":"DEFAULT_GROUP", "TRUSTEE":"GROUP_VIEWER", "INVESTOR":"GROUP_VIEWER", "ADMIN":"GROUP_ADMINISTRATOR", "POWER.OF.ATTORNEY":"GROUP_SERVICE", "GUARDIAN":"GROUP_ADMINISTRATOR", "NOMINEE":"GID_LOAN_CUSTOMERS", "BENE.POD":"GID_CREDITCARD_CUSTOMERS", "RISK.PARTICIPANT":"4dd6183f-61d2-410f-8a4f-871af67ac933", "APPLICANT":"GROUP_VIEWER", "E.SURVIVOR":"GROUP_SERVICE", "CUSTODIAN":"GID_PRIORITY_MEMBERS", "INTERMEDIARY":"GROUP_CREATOR", "GUARANTOR":"a759860a-683a-4d41-81f8-fbd97d53b608", "SOLICITOR":"GROUP_ADMINISTRATOR", "PRIMARY.OWNER":"GROUP_TESTING", "AGENT.CUM.PARTICIPANT":"GROUP_CREATOR", "BENE.OTHER":"GID_BANKING_CUSTOMERS", "BENE.REV.TRUST":"GID_HNW_CUSTOMERS", "CONSERVATOR":"GID_LOAN_CUSTOMERS", "EXECUTOR":"GROUP_TESTING", "SUB-PARTICIPANT":"GROUP_AUTHORIZER", "SECONDARY.OWNER":"a759860a-683a-4d41-81f8-fbd97d53b608", "JOINT.OWNER":"DEFAULT_GROUP"}','SERVER','0', '','',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '0');
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('C360_ROLE_MAPPING2','C360_CONFIG_BUNDLE','PREFERENCE' ,'LE23698573_CUSTOMER_ROLE_MAPPING','Mapping T24 and customer role','{"MINOR.UGMA":"GID_CREDITCARD_CUSTOMERS", "F.SURVIVOR":"4dd6183f-61d2-410f-8a4f-871af67ac933", "DBA":"GROUP_PLATINUM", "PARTICIPANT":"GROUP_PLATINUM", "IRA.OWNER":"DEFAULT_EUROPE_GROUP", "US.BENE.POD.CONT":"DEFAULT_EUROPE_GROUP", "SUB.PARTICIPANT":"GROUP_CREATOR", "LEGAL.OWNER":"GID_BANKING_CUSTOMERS", "MINOR.UTMA":"GID_HNW_CUSTOMERS", "AGENT":"GROUP_AUTHORIZER", "INSTRUCTING.PARTY":"GROUP_AUTHORIZER", "OWNER":"GID_PRIORITY_MEMBERS", "AUTH.SIGNER":"DEFAULT_EUROPE_GROUP", "BENE.IRREV.TRUST":"DEFAULT_GROUP", "TRUSTEE":"GROUP_VIEWER", "INVESTOR":"GROUP_VIEWER", "ADMIN":"GROUP_ADMINISTRATOR", "POWER.OF.ATTORNEY":"GROUP_SERVICE", "GUARDIAN":"GROUP_ADMINISTRATOR", "NOMINEE":"GID_LOAN_CUSTOMERS", "BENE.POD":"GID_CREDITCARD_CUSTOMERS", "RISK.PARTICIPANT":"4dd6183f-61d2-410f-8a4f-871af67ac933", "APPLICANT":"GROUP_VIEWER", "E.SURVIVOR":"GROUP_SERVICE", "CUSTODIAN":"GID_PRIORITY_MEMBERS", "INTERMEDIARY":"GROUP_CREATOR", "GUARANTOR":"a759860a-683a-4d41-81f8-fbd97d53b608", "SOLICITOR":"GROUP_ADMINISTRATOR", "PRIMARY.OWNER":"GROUP_TESTING", "AGENT.CUM.PARTICIPANT":"GROUP_CREATOR", "BENE.OTHER":"GID_BANKING_CUSTOMERS", "BENE.REV.TRUST":"GID_HNW_CUSTOMERS", "CONSERVATOR":"GID_LOAN_CUSTOMERS", "EXECUTOR":"GROUP_TESTING", "SUB-PARTICIPANT":"GROUP_AUTHORIZER", "SECONDARY.OWNER":"a759860a-683a-4d41-81f8-fbd97d53b608", "JOINT.OWNER":"DEFAULT_GROUP"}','SERVER','0', '','',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '0');
INSERT INTO [${dbxschemaname}].[configurations]([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('C360_ROLE_MAPPING3','C360_CONFIG_BUNDLE','PREFERENCE' ,'GB0010001_CUSTOMER_ROLE_MAPPING','Mapping T24 and customer role','{"MINOR.UGMA":"GID_CREDITCARD_CUSTOMERS", "F.SURVIVOR":"4dd6183f-61d2-410f-8a4f-871af67ac933", "DBA":"GROUP_PLATINUM", "PARTICIPANT":"GROUP_PLATINUM", "IRA.OWNER":"DEFAULT_EUROPE_GROUP", "US.BENE.POD.CONT":"DEFAULT_EUROPE_GROUP", "SUB.PARTICIPANT":"GROUP_CREATOR", "LEGAL.OWNER":"GID_BANKING_CUSTOMERS", "MINOR.UTMA":"GID_HNW_CUSTOMERS", "AGENT":"GROUP_AUTHORIZER", "INSTRUCTING.PARTY":"GROUP_AUTHORIZER", "OWNER":"GID_PRIORITY_MEMBERS", "AUTH.SIGNER":"DEFAULT_EUROPE_GROUP", "BENE.IRREV.TRUST":"DEFAULT_GROUP", "TRUSTEE":"GROUP_VIEWER", "INVESTOR":"GROUP_VIEWER", "ADMIN":"GROUP_ADMINISTRATOR", "POWER.OF.ATTORNEY":"GROUP_SERVICE", "GUARDIAN":"GROUP_ADMINISTRATOR", "NOMINEE":"GID_LOAN_CUSTOMERS", "BENE.POD":"GID_CREDITCARD_CUSTOMERS", "RISK.PARTICIPANT":"4dd6183f-61d2-410f-8a4f-871af67ac933", "APPLICANT":"GROUP_VIEWER", "E.SURVIVOR":"GROUP_SERVICE", "CUSTODIAN":"GID_PRIORITY_MEMBERS", "INTERMEDIARY":"GROUP_CREATOR", "GUARANTOR":"a759860a-683a-4d41-81f8-fbd97d53b608", "SOLICITOR":"GROUP_ADMINISTRATOR", "PRIMARY.OWNER":"GROUP_TESTING", "AGENT.CUM.PARTICIPANT":"GROUP_CREATOR", "BENE.OTHER":"GID_BANKING_CUSTOMERS", "BENE.REV.TRUST":"GID_HNW_CUSTOMERS", "CONSERVATOR":"GID_LOAN_CUSTOMERS", "EXECUTOR":"GROUP_TESTING", "SUB-PARTICIPANT":"GROUP_AUTHORIZER", "SECONDARY.OWNER":"a759860a-683a-4d41-81f8-fbd97d53b608", "JOINT.OWNER":"DEFAULT_GROUP"}','SERVER','0', '','',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '0');

GO
UPDATE [${dbxschemaname}].[featureaction] SET [isMFAApplicable] = '0' WHERE ([id] = 'CARD_MANAGEMENT_ADD_CARD_APPLE_WALLET' AND [companyLegalUnit] = 'ALL');
UPDATE [${dbxschemaname}].[featureaction] SET [isMFAApplicable] = '0' WHERE ([id] = 'CARD_MANAGEMENT_ADD_CARD_GOOGLE_PAY' AND [companyLegalUnit] = 'ALL');
UPDATE [${dbxschemaname}].[featureaction] SET [isMFAApplicable] = '0' WHERE ([id] = 'CARD_MANAGEMENT_ADD_CARD_SAMSUNG_PAY' AND [companyLegalUnit] = 'ALL');

INSERT INTO  [${dbxschemaname}].[featureaction]([id],[Feature_id],[App_id],[Type_id],[Rrole_id],[name],[description],[isAccountLevel],[isMFAApplicable],[isPrimary],[DisplaySequence],[createdts],[lastmodifiedts],[synctimestamp],[softdeleteflag],[status],[accesspolicyId],[actionlevelId]) VALUES ('UPDATE_PRIMARY_ADDRESS' ,'PROFILE_SETTINGS' ,'RETAIL_AND_BUSINESS_BANKING' ,'NON_MONETARY' ,'PROFILE_SETTINGS-CREATE' ,'Update Primary Address' ,'Update Primary Address of customer' ,'0', '0', '0', '47', GETDATE(), GETDATE(), GETDATE(),'0','SID_ACTION_ACTIVE','VIEW','CUSTOMERID_LEVEL') ;
INSERT INTO  [${dbxschemaname}].[actiondisplaynamedescription]([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UPDATE_PRIMARY_ADDRESS','en-US','Update Primary Address', 'Update Primary Address of customer');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_BUSINESS','UPDATE_PRIMARY_ADDRESS');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_WEALTH','UPDATE_PRIMARY_ADDRESS');
INSERT INTO  [${dbxschemaname}].[featureactionroletype]([RoleType_id], [Action_id]) VALUES ('TYPE_ID_RETAIL','UPDATE_PRIMARY_ADDRESS');
INSERT INTO  [${dbxschemaname}].[dependentactions]([actionId], [dependentactionId], [featureId], [actionName], [featureName]) VALUES ('UPDATE_PRIMARY_ADDRESS', 'UPDATE_PRIMARY_ADDRESS', 'PROFILE_SETTINGS', 'Update Primary Address', 'Profile Settings');
INSERT INTO  [${dbxschemaname}].[compositeaction]([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID359', 'PID45', 'UPDATE_PRIMARY_ADDRESS', 'PROFILE_SETTINGS', '1');


update [${dbxschemaname}].[configurations] set [config_value] = '{"GB0010001":"5801fa32-a416-45b6-af01-b22e2de93777"}' where  [configuration_id] = '80b2a729-c211-43b3-aae8-e3cc8d546b1';


update [${dbxschemaname}].[configurations] set [config_value] = '{"GB0010001":"707dfea8-d0fe-4154-89c3-e7d7ef2ee16a"}' where  [configuration_id] = '80b2a729-8143-43b3-aae8-e3cc8d546b1';

