UPDATE [${dbxschemaname}].[configurations] SET config_value ='{"QUEUE_APPLICATION_RETAIL_LARGE_SIZE_PL","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_PL","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_PL","QUEUE_APPLICATION_RETAIL_LARGE_SIZE_OD","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_OD","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_OD","QUEUE_APPLICATION_RETAIL_CC_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CC_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CC_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CC_UK_LONDON","QUEUE_APPLICATION_RETAIL_CC_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CC_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CC_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CC_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CC_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_CHECKING_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CHECKING_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CHECKING_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CHECKING_UK_LONDON","QUEUE_APPLICATION_RETAIL_CHECKING_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CHECKING_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_SAVINGS_US_AUSTIN","QUEUE_APPLICATION_RETAIL_SAVINGS_US_ORLANDO","QUEUE_APPLICATION_RETAIL_SAVINGS_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LONDON","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_CD_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CD_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CD_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CD_UK_LONDON","QUEUE_APPLICATION_RETAIL_CD_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CD_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CD_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CD_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CD_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_DEFAULT_QUEUE","QUEUE_APPLICATION_SME_LARGE_BL","QUEUE_APPLICATION_SME_MEDIUM_BL","QUEUE_APPLICATION_SME_SMALL_BL","QUEUE_APPLICATION_SME_LARGE_OD","QUEUE_APPLICATION_SME_MEDIUM_OD","QUEUE_APPLICATION_SME_SMALL_OD","QUEUE_APPLICATION_SME_LARGE_CC","QUEUE_APPLICATION_SME_MEDIUM_CC","QUEUE_APPLICATION_SME_SMALL_CC","QUEUE_APPLICATION_SME_CURRENT_IN_HYD","QUEUE_APPLICATION_SME_CURRENT_IN_CHEN","QUEUE_APPLICATION_SME_CURRENT_US_SANFRAN","QUEUE_APPLICATION_SME_CURRENT_US_AUSTIN","QUEUE_APPLICATION_SME_CURRENT_UK_LONDON","QUEUE_APPLICATION_SME_CURRENT_UK_MANU","QUEUE_APPLICATION_SME_CURRENT_UK_LP","QUEUE_APPLICATION_SME_CURRENT_EGYPT_CAIRO","QUEUE_APPLICATION_SME_CURRENT_COMMON_OTHER","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_LARGE_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_LENDING_DEFAULT","QUEUE_APPLICATION_RETAIL_MORTGAGE_DEFAULT"}' WHERE configuration_id ='23b62843-e025-40a4-8c22-14a9a45c6yue57w';

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_25', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'CONFIRM_AND_CANCEL_SIMULATIONS', N'Confirm and Cancel Popup Messages For Resimulate Screen', N'{\"CONFIRM\": \"CONFIRM_SIMULATION_POPUP_TEXT\",\"CANCEL\": \"CANCEL_SIMULATION_POPUP_TEXT\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_26', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'MORTGAGE_BUREAU_SCORE', N'MIN and MAX Bureau score value of Mortgage Application', N'{\"MIN_BUREAU_SCORE\":\"600\", \"MAX_BUREAU_SCORE\":\"750\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

UPDATE [${dbxschemaname}].[configurations] SET config_value ='{"QUEUE_APPLICATION_RETAIL_LARGE_SIZE_PL","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_PL","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_PL","QUEUE_APPLICATION_RETAIL_LARGE_SIZE_OD","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_OD","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_OD","QUEUE_APPLICATION_RETAIL_CC_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CC_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CC_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CC_UK_LONDON","QUEUE_APPLICATION_RETAIL_CC_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CC_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CC_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CC_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CC_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_CHECKING_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CHECKING_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CHECKING_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CHECKING_UK_LONDON","QUEUE_APPLICATION_RETAIL_CHECKING_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CHECKING_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_SAVINGS_US_AUSTIN","QUEUE_APPLICATION_RETAIL_SAVINGS_US_ORLANDO","QUEUE_APPLICATION_RETAIL_SAVINGS_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LONDON","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_CD_US_AUSTIN","QUEUE_APPLICATION_RETAIL_CD_US_ORLANDO","QUEUE_APPLICATION_RETAIL_CD_US_SANFRANCISCO","QUEUE_APPLICATION_RETAIL_CD_UK_LONDON","QUEUE_APPLICATION_RETAIL_CD_UK_MANCHESTER","QUEUE_APPLICATION_RETAIL_CD_UK_LIVERPOOL","QUEUE_APPLICATION_RETAIL_CD_EGYPT_BANHA","QUEUE_APPLICATION_RETAIL_CD_EGYPT_CAIRO","QUEUE_APPLICATION_RETAIL_CD_EGYPT_TANTA","QUEUE_APPLICATION_RETAIL_DEFAULT_QUEUE","QUEUE_APPLICATION_SME_LARGE_BL","QUEUE_APPLICATION_SME_MEDIUM_BL","QUEUE_APPLICATION_SME_SMALL_BL","QUEUE_APPLICATION_SME_LARGE_OD","QUEUE_APPLICATION_SME_MEDIUM_OD","QUEUE_APPLICATION_SME_SMALL_OD","QUEUE_APPLICATION_SME_LARGE_CC","QUEUE_APPLICATION_SME_MEDIUM_CC","QUEUE_APPLICATION_SME_SMALL_CC","QUEUE_APPLICATION_SME_CURRENT_IN_HYD","QUEUE_APPLICATION_SME_CURRENT_IN_CHEN","QUEUE_APPLICATION_SME_CURRENT_US_SANFRAN","QUEUE_APPLICATION_SME_CURRENT_US_AUSTIN","QUEUE_APPLICATION_SME_CURRENT_UK_LONDON","QUEUE_APPLICATION_SME_CURRENT_UK_MANU","QUEUE_APPLICATION_SME_CURRENT_UK_LP","QUEUE_APPLICATION_SME_CURRENT_EGYPT_CAIRO","QUEUE_APPLICATION_SME_CURRENT_COMMON_OTHER","QUEUE_APPLICATION_RETAIL_SMALL_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_LARGE_SIZE_MORTGAGE","QUEUE_APPLICATION_RETAIL_LENDING_DEFAULT","QUEUE_APPLICATION_RETAIL_MORTGAGE_DEFAULT","QUEUE_MORTGAGE_SERVICING","QUEUE_CUSTOMER_PROFILE"}' WHERE configuration_id ='23b62843-e025-40a4-8c22-14a9a45c6yue57w';
GO

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'4e31abf8-0019-4c3b-876d-b3a19wcfg3bc', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SERVICE_REQUEST_MOCK_STATUS', N'Mock status for Service Request', N'{\"servicing_mock_flag\":\"true\", \"fulfilmentStatus\":\"Completed\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

INSERT INTO [${dbxschemaname}].[configurations]  ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag])
VALUES (N'e67be3e0-2b6a-4772-b062-18f704718cf3',N'INFINITY_ASSIST_CONFIG_BUNDLE',N'PREFERENCE',N'SERVICE_PAM_PROCESS_CONFIG',N'PAM process change config for Servicing journey',N'[{\"eventType\": \"serviceRequestCreated\",\"processDetails\": {\"processType\": \"Create\",\"processId\": \"InfinityAssist.SRParentProcess\",\"signalName\": \"\",\"uniqueSignalRequired\": false}}]',N'CLIENT',1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
Go

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_27', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CUSTOMER_OFFER_LETTER', N'Config to set recipients and notification type  for Retail Receiving Offer Letter Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_28', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CREDIT_APPROVAL', N'Config to set recipients and notification type for Retail receiving notification for credit Approval Notification.', N'{"notifyRecipients" : "RM","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_29', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_APPLICATION_APPROVED', N'Config to set recipients and notification type for Retail application Approved status Notification.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_30', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_KYC_COMPLETION', N'Config to set recipients and notification type for Retail KYC Completion Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_31', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_AIP_ILLUSTRATIVE_CUSTOMER_ACTION', N'Config to set recipients and notification type for Retail AIP Ilustrative CustomerActions Notification.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_32', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_APPLICATON_REJECTION', N'Config to set recipients and notification type for Retail Application Rejection Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_33', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_USER_OFFER_LETTER', N'Config to set recipients and notification type for Retail Receiving Offer Letter Notification.', N'{"notifyRecipients" : "RM","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_34', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_DENIED_APPLICATION', N'Config to set recipients and notification type for Retail Denied Application Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_35', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_CUSTOMER_OFFER_LETTER', N'Config to set recipients and notification type for SME Receiving Offer Letter Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_36', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_CUSTOMER_OFFER_LETTER_COAPPLICANT', N'Config to set recipients and notification type for SME Receiving Offer Letter Notification.', N'{"notifyRecipients" : "CO_APPLICANT","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_37', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_CREDIT_APPROVAL', N'Config to set recipients and notification type for SME credit Approval Notification.', N'{"notifyRecipients" : "RM","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_38', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_APPLICATION_APPROVED', N'Config to set recipients and notification type for SME Application Approved status Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_39', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_DENIED_APPLICATION', N'Config to set recipients and notification type for SME Denied Application Notification.', N'{"notifyRecipients" : "MAIN_BORROWER","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_40', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CUSTOMER_ACTION_XCREDIT_CARDS_CONSENT', N'Config to set recipients and notification type for Retail Credit cards Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_41', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CUSTOMER_ACTION_CONSENT', N'Config to set recipients and notification type for Retail Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_42', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', N'Config to set recipients and notification type for Retail offerAcceptance CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_43', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_CONSENT', N'Config to set recipients and notification type for Retail Mortgage Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_44', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', N'Config to set recipients and notification type for Retail Mortgage offerAcceptance CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_45', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_AIP', N'Config to set recipients and notification type for Retail Mortgage AIP CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_46', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_CUSTOMER_ACTION_MOBILE_PHONE_NUMBER_CONSENT', N'Config to set recipients and notification type for Retail Mobile Phone Number Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_47', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_NOTIFY_RETRIGGER_SIMULATION', N'Config to set recipients and notification type for Retail Retrigger Simulation.', N'{"notifyRecipients" : "RM","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_48', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_CUSTOMER_ACTION_XCREDIT_CARDS_CONSENT', N'Config to set recipients and notification type for SME Credit cards Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_49', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_NOTIFY_CUSTOMER_ACTION_CONSENT', N'Config to set recipients and notification type for SME Consent CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_50', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SMS_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', N'Config to set recipients and notification type for SME offerAcceptance CustomerActions.', N'{"notifyRecipients" : "ALL_PARTIES","notificationType" : "BOTH"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
Go