package com.kony.adminconsole.utilities;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.apache.commons.lang3.StringUtils;
import com.temenos.logger.Logger;
import com.temenos.logger.alert.Alert;
import com.temenos.logger.diagnostics.Diagnostic;
import org.json.JSONArray;
import org.json.JSONObject;

import com.kony.adminconsole.commons.utils.CommonUtilities;
import com.kony.adminconsole.dto.ExportColumnDetailsBean;

public class CSVGenerator {

	private static final Alert alert = Logger.forAlert().forModule("Infinity", "SPOTLIGHT");
	private static final Diagnostic diagnostic = Logger.forDiagnostic().forModule("Infinity", "SPOTLIGHT");
	private static final String DATE_FORMAT = "MM/dd/yy hh:mm a";
	private static final SimpleDateFormat dateFormat = new SimpleDateFormat(DATE_FORMAT);

	public StringBuilder generateCSV(JSONArray dataArray, String title, String generatedBy, Integer offset,
			List<ExportColumnDetailsBean> fieldList, String filters) throws IOException {
		try {
			StringBuilder responseCsvBuilder = new StringBuilder();
			CSVPrinter responseCsvPrinter = CSVFormat.DEFAULT
					.print(responseCsvBuilder);
			
			responseCsvPrinter.printRecord("Title",CommonUtilities.prependSingleQuoteIfFirstCharIsTriggerChar(title) );
			responseCsvPrinter.printRecord("Report generated by : ", CommonUtilities.prependSingleQuoteIfFirstCharIsTriggerChar(generatedBy) );
			responseCsvPrinter.printRecord("Report generated on : ", changeDateByOffset(offset) );
			responseCsvPrinter.printRecord("Filters applied : ", filters.trim().isEmpty() ? "N/A" : CommonUtilities.prependSingleQuoteIfFirstCharIsTriggerChar(filters) );
			responseCsvPrinter.printRecord();
			
			List<String> row = new ArrayList<String>();
			for (ExportColumnDetailsBean field : fieldList) {
	            if (StringUtils.isNotBlank(field.getDisplayName())) {
	            	row.add(field.getDisplayName());
	            }
	        }
			responseCsvPrinter.printRecord(row.toArray());
			
			if (dataArray != null) {
				StringBuilder cellValue = new StringBuilder();
				JSONObject rowData = null;
				for (int i = 0; i < dataArray.length(); i++) {
					rowData = dataArray.getJSONObject(i);
					row = new ArrayList<String>();
					int count=1;
					for (ExportColumnDetailsBean field : fieldList) {
						if (StringUtils.isBlank(field.getDisplayName())) {
							cellValue = cellValue.append(rowData.optString(field.getParamName()) + " ");
						} else {
							if (field.getType().equalsIgnoreCase("date")) {
								Long longdate = new Long(rowData.optString(field.getParamName()));
								cellValue = cellValue.append(changeDateByOffset(new Date(longdate), offset));
							} else {
								String data = CommonUtilities.prependSingleQuoteIfFirstCharIsTriggerChar(
										rowData.optString(field.getParamName()).toString());
								int count_cells=1;
								int maxCellLength=32758; // Excel cell size
								if(StringUtils.isNotBlank(data) && (data.length()>maxCellLength)) {
									count_cells=(int) Math.ceil((double)data.length()/maxCellLength);
								}
								// Handling below if the column is at the last and cell exceeds excel size)
								if(count == fieldList.size() && count_cells>1) {
									
									for(int k=1;k<=count_cells;k++) {
										
										int startIndex;
										int lengthToPrint;
										if(k==count_cells) {
											lengthToPrint=data.length();
										}else {
											lengthToPrint=maxCellLength*k;
										}
										startIndex = maxCellLength*(k-1);
										String str=data.substring(startIndex, lengthToPrint);
										cellValue = cellValue.append(str);
										if(k!= count_cells) {
											row.add(cellValue.toString());
											cellValue = new StringBuilder();
										}
									}
								}
								else	
									cellValue = cellValue
											.append(CommonUtilities.prependSingleQuoteIfFirstCharIsTriggerChar(
													rowData.optString(field.getParamName())));
							}
							row.add(cellValue.toString());
							cellValue = new StringBuilder();
						}
						count++;
					}
					diagnostic.prepareInfo("export report row - " +Arrays.toString(row.toArray())).log();
					responseCsvPrinter.printRecord(row.toArray());
				}
			}
			return responseCsvBuilder;
		} catch (IOException ioe) {
			alert.prepareError("IOException in writing csv file - ", ioe).log();
			throw ioe;
		} catch (Exception e) {
			alert.prepareError("Exception in writing csv file - ", e).log();
			throw e;
		}
	}
	
	private static String changeDateByOffset(Integer offset) {
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
        TimeZone timezone = TimeZone.getTimeZone("UTC");
        Calendar datetimeUTC = Calendar.getInstance();
        datetimeUTC.setTimeZone(timezone);

        Date localeDate = new Date(datetimeUTC.getTime().getTime() + ((-1) * offset * 60 * 1000));
        return dateFormat.format(localeDate);
    }

	private String changeDateByOffset(Date inputDate, Integer offset) {

		TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
		TimeZone timezone = TimeZone.getTimeZone("UTC");
		Calendar datetimeUTC = Calendar.getInstance();
		datetimeUTC.setTimeZone(timezone);
		datetimeUTC.setTimeInMillis(inputDate.getTime());

		Date localeDate = new Date(datetimeUTC.getTime().getTime() + ((-1) * offset * 60 * 1000));
		return dateFormat.format(localeDate);
	}
	
}
