package com.kony.adminconsole.utilities;

public enum ServiceNameToEventMapper {		

	CREATE_SERVICE_DEFINITION(ModuleNameEnum.SERVICE_DEFINITION,EventEnum.CREATE),
	DELETE_SERVICE_DEFINITION(ModuleNameEnum.SERVICE_DEFINITION,EventEnum.DELETE),
	UPDATE_SERVICE_DEFINITION(ModuleNameEnum.SERVICE_DEFINITION,EventEnum.UPDATE),
	CREATE_CONTRACT(ModuleNameEnum.CONTRACTS,EventEnum.CREATE),
	EDIT_CONTRACT(ModuleNameEnum.CONTRACTS,EventEnum.UPDATE),
	CREATE_CUSTOMER_ROLE(ModuleNameEnum.CUSTOMERROLES,EventEnum.CREATE),
	EDIT_CUSTOMER_ROLE(ModuleNameEnum.CUSTOMERROLES,EventEnum.UPDATE),
	CREATE_INFINITY_USER(ModuleNameEnum.INFINITYUSER,EventEnum.CREATE),
	APPROVE_RESET_TX_PIN(ModuleNameEnum.RESET_TRANS_PIN,EventEnum.APPROVEREQUEST),
	REJECT_RESET_TX_PIN(ModuleNameEnum.RESET_TRANS_PIN,EventEnum.REJECTREQUEST),
	DISPUTE_TRANS(ModuleNameEnum.DISPUTE_TRANSACTION,EventEnum.SETTLED),
	APPROVE_ENROLL_REQ(ModuleNameEnum.ENROLLMENT_REQUESTS,EventEnum.APPROVEENROLL),
	REJECT_ENROLL_REQ(ModuleNameEnum.ENROLLMENT_REQUESTS,EventEnum.REJECTENROLL),
	ACTIVATE_MERCHANT(ModuleNameEnum.MERCHANT_MANAGEMENT,EventEnum.MERCHANT_ACTIVATE),
	DEACTIVATE_MERCHANT(ModuleNameEnum.MERCHANT_MANAGEMENT,EventEnum.MERCHANT_DEACTIVATE),
	UPDATE_MERCHANT(ModuleNameEnum.MERCHANT_MANAGEMENT,EventEnum.MERCHANT_UPDATE),
	CREATE_MERCHANT(ModuleNameEnum.MERCHANT_MANAGEMENT,EventEnum.MERCHANT_CREATE),
	MERCHANT_FEE_DELETE(ModuleNameEnum.MERCHANT_MANAGEMENT,EventEnum.MERCHANT_FEE_DELETE),
	CREATE_CARD_LIMITS(ModuleNameEnum.CARD_LIMITS_MANAGEMENT,EventEnum.CREATE_CARD_LIMITS),
	UPDATE_CARD_LIMITS(ModuleNameEnum.CARD_LIMITS_MANAGEMENT,EventEnum.UPDATE_CARD_LIMITS),
	DELETE_CARD_LIMITS(ModuleNameEnum.CARD_LIMITS_MANAGEMENT,EventEnum.DELETE_CARD_LIMITS),
	DISABLE_THIRDPARTY_AUTH(ModuleNameEnum.INFINITYUSER,EventEnum.DISABLE_THIRDPARTY_AUTH),
	EDIT_INFINITY_USER(ModuleNameEnum.INFINITYUSER,EventEnum.UPDATE);
	private final ModuleNameEnum event;
	private final EventEnum eventType;

	private ServiceNameToEventMapper(ModuleNameEnum event, EventEnum eventType) {
		this.event = event;
		this.eventType = eventType;
	}

	public ModuleNameEnum getEvent() {
		return event;
	}

	public EventEnum getEventType() {
		return eventType;
	}
}
