INSERT INTO `configurationbundles` (`bundle_id`, `bundle_name`, `app_id`, `createdby`, `modifiedby`) VALUES ('INFINITY_ASSIST_CONFIG_BUNDLE', 'InfinityAssist', 'InfinityAssist', 'Kony dev', 'Kony dev');

INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_1', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_OFAC_CHECK_REPORT_WITHIN_DAYS', 'Retail OFAC check report', '5', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_2', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_BLACKLIST_CHECK_REPORT_WITHIN_DAYS', 'Retail blacklist check report', '5', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_3', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_BUREAU_CHECK', 'Retail bureau check', '{\"provider\":\"Experian\",\"withinDays\":\"30\"}', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_4', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_OFFER_ACCEPTANCE_MODE', 'Retail offer acceptance mode', 'Offline', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_5', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_RM_SUPERVISOR', 'Retail rm supervisor', 'rmautouser', 'CLIENT', '1');
UPDATE `configurations` SET `config_value` = '{\"provider\":\"07\",\"withinDays\":\"30\"}' WHERE (`configuration_id` = 'IA_3');

INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_6', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_OFAC_CHECK_REPORT_WITHIN_DAYS', 'SME OFAC check report', '5', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_7', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_BLACKLIST_CHECK_REPORT_WITHIN_DAYS', 'SME blacklist check report', '5', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_8', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_BUSINESS_BUREAU_CHECK', 'SME Business Bureau Check', '{\"provider\":\"Experian\",\"withinDays\":\"30\"}', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_9', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_RELATED_PARTY_BUREAU_CHECK', 'SME Related Party Bureau Check', '{\"provider\":\"Experian\",\"withinDays\":\"30\"}', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_10', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_OFFER_ACCEPTANCE_MODE', 'SME offer acceptance mode', 'Offline', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_11', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_RM_SUPERVISOR', 'SME rm supervisor', 'smermautouser', 'CLIENT', '1');
insert into `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`, `createdby`, `modifiedby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) values 
('4e31abf8-0019-4c3b-876d-b3a19eaca3bc', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'ASSESSMENT_MOCK_SERVICE_STATUS', 'Mock status data for OFAC/Blacklist ', '{\"blacklist_mock_flag\" : \"true\",\"ofac_mock_flag\" : \"true\",\"ofac_status\": \"pass\",\"blacklist_status\": \"pass\"}', 'CLIENT', '1', '', '', '2021-10-08 10:19:19', '2021-10-08 10:19:19', '2021-10-08 10:19:19', '0');
UPDATE `configurations` SET `config_value` = '{\"provider\":\"07\",\"withinDays\":\"30\"}' WHERE (`configuration_id` = 'IA_8');
UPDATE `configurations` SET `config_value` = '{\"provider\":\"07\",\"withinDays\":\"30\"}' WHERE (`configuration_id` = 'IA_9');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_12', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'PRODUCTID_MCMS_REDHAT_MAPPING', 'Mapping of MCMS product ids to Redhat Identifiers', '{\"ADVANCED.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"BASIC.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"PREFERRED.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"SAVINGS.PRIME.INFINITY\":\"RETAIL.UNSECURED\",\"SAVINGS.STANDARD.INFINITY\":\"RETAIL.UNSECURED\",\"SAVINGS.SALARY.INFINITY\":\"RETAIL.UNSECURED\",\"INFINITY.ADAMANTIUM.CARD\":\"RETAIL.UNSECURED\",\"INFINITY.VIBRANIUM.CARD\":\"RETAIL.UNSECURED\",\"INFINITY.BESKAR.CARD\":\"RETAIL.UNSECURED\",\"OVERDRAFT.ACCOUNT\":\"RETAIL.UNSECURED\",\"PERSONAL.LOAN\":\"RETAIL.UNSECURED\",\"OVERDRAFT.ACCOUNT.SME\":\"SME.OVERDRAFT\",\"INFINITY.TRAVEL.CARD\":\"SME.CREDITCARD\",\"INFINITY.FUSION.BUSINESS.CARD\":\"SME.CREDITCARD\",\"INFINITY.UNLIMITED.REWARDS.CARD\":\"SME.CREDITCARD\",\"SMALL.BUSINESS.LOAN\":\"SME.LOAN\"}', 'CLIENT', '1');
INSERT INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_13', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'FINANCIAL_RATIO_DEFAULT_VALUES', 'Default values for Financial Ratio Fields', '{\"debtToIncomeRatio\":\"50\",\"dscr\":\"3.5\",\"debtToEquity\":\"1.1\",\"operatingMargin\":\"0.30\",\"netProfitMargin\":\"0.40\",\"currentRatio\":\"1.8\"}', 'CLIENT', '1');
UPDATE `configurations` SET `config_value` = '{\"blacklist_mock_flag\" : \"true\",\"ofac_mock_flag\" : \"true\",\"ofac_status\": \"pass\", \"blacklist_status\": \"pass\", \"bureau_mock_flag\" : \"true\", \"mock_bureau_eventType\" : \"Business Bureau\", \"mock_bureau_level\" : \"package1\", \"mock_bureau_score\" : \"1000\", \"mock_bureau_status\" : \"Pending\"}' WHERE (`configuration_id` = '4e31abf8-0019-4c3b-876d-b3a19eaca3bc');