INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'149', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'CSR_MODE', N'Turn ON/OFF of Funding option on CSR', N'ON', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'156', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'PRODUCTSELECTION_MANDATORY', N'Product Selection Configuration', N'true', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'150', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'CSR_MFA', N'Turn ON/OFF of MFA option on CSR', N'ON', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
UPDATE [${dbxschemaname}].[communicationtemplate] SET Text = N'<p>Dear [#]FirstName[/#] [#]LastName[/#],</p><p>You have successfully signed in to your online banking profile.</p><p>Regards,<br />Infinity Bank</p>.' WHERE (id = '76')
UPDATE [${dbxschemaname}].[communicationtemplate] SET Text = N'<p>Dear [#]FirstName[/#] [#]LastName[/#],</p><p>You have made an invalid sign in attempt for your username [#]MaskedUsername[/#]  on [#]ServerDate[/#] [#]ServerTime[/#].</p><p>Regards,<br />Infinity Bank</p><p>&nbsp;</p>' WHERE (id = '80')
UPDATE [${dbxschemaname}].[emailtemplates] SET TemplateText = N'<p>&nbsp;</p><center><div style="width: 95%; height: 5px; margin: 0px 0px 0px 0px;"><div><table border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td style="background-color: #284e77; font-size: 1px; line-height: 1px; -webkit-text-size-adjust: none;" align="center" valign="top" bgcolor="#284e77" height="10">&nbsp;</td></tr></tbody></table></div></div><div style="width: 95%; margin: 0px 0px 50px 0px;"><div style="display: inline-block; text-align: left;"><table style="width: 50%;" width="50%"><tbody><tr><td width="200"><img style="text-align: right; width: 200px; border: 0;" src="https://retailbanking1.konycloud.com/dbimages/infinitydbxlogo.png" alt="temenos_logo" width="200" /></td></tr></tbody></table> <br /><br />Hi %firstName% %lastName%,<br /><br />You are enrolled to Digital Banking Channel. Please activate your account now.<br /><br />%userName% is your username. Activation code is sent to you registered mobile number.<br /><br />You are required to input your username &amp; activation code in the link below.<br /><br /><div style="text-align: center; border-width: 1px; border-radius: 4px;"><table style="table-layout: fixed;" border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td style="color: #ffffff; background-color: #333b44; word-wrap: break-word; word-break: break-all; padding: 10px; line-height: 20px;" align="center"><div style="margin: 10px 10px 10px 10px; font-size: 13px;">To activate your account and set a password,<a style="color: #11abeb;" href="%resetPasswordLink%">click here</a> <br />or paste the following link on your browser: <br /><br /><a style="color: #11abeb;">%resetPasswordLink%</a></div></td></tr></tbody></table></div> <br /><center>The activation code will expire in %activationCodeExpiry% days , so activate it right away.</center><br /><br />Regards,<br />Temenos Banking Team <br /><br /><br /><br /><span style="color: #999999; font-size: 12px;">This is a system generated mail. If you are not the named addressee please notify the sender immediately by e-mail at support@temenosbank.com and then delete the e-mail from your system. Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments. Temenos, Inc. www.temenos.com </span><br /><br /><div align="center"><span style="color: #999999;"><strong>(c) Copyright Temenos Digital Retail Origination</strong>. All rights reserved.</span></div></div></div></center>' WHERE (id = '22')
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'157', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'CoApplicant_Mandatory', N'CoApplicant Configuration', N'true', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
DELETE FROM [${dbxschemaname}].[configurations] WHERE (configuration_id = '149');
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92044', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'INCOMEDOCUMENT_CONFIG', N'IncomeDocument', N'{"UserActionName": "IncomeDocument","Group": "Income","Skippable": "true","Title": "Income document","UserActionType": "DocumentUpload","Options": "","OptionsType": "","Description": "Upload a document showing your income - such as a payslip or tax statement. This will help us process your application faster.","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92045', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'MOBILEPHONENUMBERCONSENT_CONFIG', N'MobilePhoneNumberConsent', N'{"UserActionName": "MobilePhoneNumberConsent","Group": "Legal","Skippable": "false","Title": "Mobile phone number consent","UserActionType": "Radio-ButtonSelection","Options": ["The bank can call or text me through automated means","The bank can only contact me through non-automated means","The bank can''t contact me (this may impact your approval)"],"OptionsType": "PREDEFINED","Description": "If the phone number provided on this application is a mobile phone number, it is my mobile phone number, and by clicking on the button below, I consent to receive auto-dialed and prerecorded/artificial calls, including texts, relating to my relationship with this bank. It may include handling, servicing, and billing for any of my account(s). Message and data rates may apply. You can stop these messages by contacting our service center.","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92046', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BACKUPWITHHOLDING_CONFIG', N'BackupWithholding', N'{"UserActionName": "BackupWithholding","Group": "Legal","Skippable": "false","Title": "Backup withholding","UserActionType": "Radio-ButtonSelection","Options": ["No, I''m not subject to backup withholding","Yes, I have heard that I''m subject to backup withholding"],"OptionsType": "PREDEFINED","Description": "Have you been notified by the local government that you are subject to backup withholding?","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92047', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'CITIZENSHIP_CONFIG', N'Citizenship', N'{"UserActionName": "Citizenship","Group": "Additional Info","Skippable": "false","Title": "Citizenship","UserActionType": "Radio-ButtonSelection","Options": ["I''m a citizen of this country",	"I''m a citizen of another country"],"OptionsType": "PREDEFINED","Description": "Under federal regulations, we need to gather your citizenship information","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92048', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'EMPLOYMENTSTATUS_CONFIG', N'EmploymentStatus', N'{"UserActionName": "EmploymentStatus","Group": "Income","Skippable": "false","Title": "Employment status","UserActionType": "Radio-ButtonSelection","Options":["Employed","Self-Employed","Other"],"OptionsType": "PREDEFINED","Description": "Select your current employment status.","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92049', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'MONTHLYGROSSINCOME_CONFIG', N'MonthlyGrossIncome', N'{"UserActionName": "MonthlyGrossIncome","Group": "Income","Skippable": "false","Title": "Monthly income","UserActionType": "Currency","Options": "","OptionsType": "","Description": "Provide your estimated monthly income, including all sources of income.","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'7a128ba1-8faa-468c-a782-4ea013a92050', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'STARTDATE_CONFIG', N'StartDate', N'{"UserActionName": "StartDate","Group": "Income","Skippable": "true","Title": "Start Date","UserActionType": "Date","OptionsType": "","Options": "","Description": "When did you start working for this employer? (enter month and year in the format mm/yyyy)","DynamicDataDefinition": "","NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{"desktop":"false","mobile":"true","tablet":"true"}' WHERE (configuration_id='120');
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'160', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'OPEN_ACCOUNT_BUTTON', N'to SHOW/HIDE of Open account button in dashboard pages', N'SHOW', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'60bf2b5c-9b7e-45c5-bfa5-5ff0b124289f', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'CONFIRMADDRESS_CONFIG', N'ConfirmAddress', N'{"UserActionName": "ConfirmAddress","Group": "AdditionalInfo","Skippable": "false","Title": "Confirm your address at %Address1 %city %state","UserActionType": "Radio-ButtonSelection","OptionsType": "PREDEFINED","Options": ["Own","Rent","Live for free"],"Description": "Do you own, rent or live for free at %Address1 %city %state","DynamicDataDefinition": {"AddressInfo": [{"name": "Address1","path": "$.AddressLine1"},{"name": "city","path": "$.City"},{"name": "state","path": "$.State"}]},"NeedsReview": "true"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO