/*Create/Edit Outage Message Maker checker configuration is not visible under the makerchecker configurations*/ 
UPDATE `dbxdb`.`makercheckerconfig` SET `companyLegalUnit` = 'NP0010001' WHERE (`id` = '12');
UPDATE `dbxdb`.`makercheckerconfig` SET `companyLegalUnit` = 'NP0010001' WHERE (`id` = '13');
UPDATE `dbxdb`.`makercheckerconfig` SET `companyLegalUnit` = 'NP0010001' WHERE (`id` = '14');



/* Added Terms and conditions for Virtual Card Request */
INSERT INTO `dbxdb`.`termandcondition` (`id`, `Code`, `Title`, `Description`,`companyLegalUnit`) VALUES ('1920045', 'VirtualCard_TnC', 'Card Request - Virtual', 'Terms and Conditions for Virtual Card request', 'NP0010001');
INSERT INTO `dbxdb`.`termandconditionapp` (`id`, `TermAndConditionId`, `AppId`, `createdby`, `companyLegalUnit`) VALUES ('2312375', '1920045', 'RETAIL_AND_BUSINESS_BANKING', 'admin', 'NP0010001');
INSERT INTO `dbxdb`.`termandconditiontext` (`id`, `TermAndConditionId`, `LanguageCode`, `Version_Id`, `Description`, `Content`, `ContentType_id`, `ContentModifiedBy`, `Status_id`, `companyLegalUnit`) VALUES ('1893601889', '1920045', 'en-US', '1.0', 'Card Request - Virtual', 'TEST', 'TEXT', '', 'SID_TANDC_ACTIVE', 'NP0010001');


/*** card emi T&C **/
INSERT INTO `dbxdb`.`termandcondition` (`id`, `Code`, `Title`, `Description`,`companyLegalUnit`) VALUES ('1920046', 'CardEMI_TnC', 'Convert EMI - Card', 'Terms and Conditions for Convert EMI', 'NP0010001');
INSERT INTO `dbxdb`.`termandconditionapp` (`id`, `TermAndConditionId`, `AppId`, `createdby`, `companyLegalUnit`) VALUES ('2312376', '1920046', 'RETAIL_AND_BUSINESS_BANKING', 'admin', 'NP0010001');
INSERT INTO `dbxdb`.`termandconditiontext` (`id`, `TermAndConditionId`, `LanguageCode`, `Version_Id`, `Description`, `Content`, `ContentType_id`, `ContentModifiedBy`, `ContentModifiedOn`, `Status_id`, `createdby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1153166087', '1920046', 'en-US', '1.0', 'Card Transaction EMI Convertion', 'The Card Transaction to EMI facility is available only on eligible credit card transactions as determined by the card issuer from time to time. The card account must be active and in good standing at the time of requesting EMI conversion, and the request must be made within the specified period from the transaction date. Once a transaction is successfully converted into EMI, the request cannot be cancelled or reversed. The applicable interest rate, EMI tenure, processing fee, and related charges will be communicated at the time of conversion, and applicable taxes will be levied as per prevailing laws. The EMI amount, comprising principal, interest, and taxes, will be billed monthly as part of the card statement, and failure to pay by the due date may attract late payment charges and negatively impact the cardholder\\u2019s credit score.<div><br /></div><div> The full transaction amount will be blocked from the available credit limit at the time of conversion and will be released proportionately as EMIs are repaid. Pre-closure of the EMI may be permitted subject to applicable foreclosure charges, and interest already billed will not be non-refundable. In case of a merchant refund or dispute, the handling of the EMI conversion will be subject to the issuer\\u2019s prevailing policies. If the card is closed, blocked, or in default before all EMIs are repaid, the outstanding amount shall become immediately payable. The issuer reserves the right to modify, suspend, or withdraw the EMI conversion facility at any time in accordance with applicable laws.</div>', 'TEXT', 'admin1', '2026-02-09 16:00:49', 'SID_TANDC_ACTIVE', '9f883caa-6cc2-4863-b0af-e88eb5ac3370', '2026-02-09 16:00:49', '2026-02-09 16:00:49', '2026-02-09 16:00:49', '0', 'ALL');
