USE [${dbxdbname}]
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID232');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID370');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID370');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID370');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID370');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID183');
GO
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_RM' and [Permission_id] = 'PID414')
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_RM' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_RM' and [Permission_id] = 'PID416');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_OPS' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID234');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID233');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID238');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID239');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID240');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID241');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID362');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID300');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID301');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID302');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID303');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID344');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID345');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID346');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID347');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID136');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID137');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID138');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID139');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID154');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID155');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID156');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID157');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID167');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID168');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID169');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID170');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID180');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID189');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID190');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID191');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID192');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_UW' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_UW' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_UW' and [Permission_id] = 'PID416');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID233');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID234');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_UW', N'PID233');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_UW', N'PID234');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID233');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID234');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID362');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_UW', N'PID362');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID362');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID143');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID251');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID255');
GO
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_UW' and [Permission_id] = 'PID417');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID416');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID417');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID371');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID386');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_RM', N'PID333');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_UW', N'PID333');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID256');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_OPS', N'PID333');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID371');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_SME_SUPERVISOR', N'PID333');
GO
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailOps' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID414');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID415');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID416');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID416');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID416');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID417');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailOps', N'PID255');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailOps', N'PID251');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailOps', N'PID143');
GO
INSERT INTO [${dbxschemaname}].[permission] ([id],[Type_id],[Status_id],[Name],[Description],[isComposite],[PermissionValue]) VALUES ('PID426','PER_TYPE_BORROWER_FEE','SID_ACTIVE','FacilityOverviewViewBorrowerFee','Permission to view borrower fee in Facility Overview','0','TRUE');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailRM', N'PID426');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailUW', N'PID426');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailOps', N'PID426');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailSupervisor', N'PID426');
GO
INSERT INTO [${dbxschemaname}].[permission] ([id],[Type_id],[Status_id],[Name],[Description],[isComposite],[PermissionValue]) VALUES ('PID427','PER_TYPE_FACILITY','SID_ACTIVE','RequestOverviewAddFacility','Permission to add facility in Request Overview','0','TRUE');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailRM', N'PID427');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailUW', N'PID427');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id])  VALUES (N'RID_RetailSupervisor', N'PID427');
GO
INSERT INTO [${dbxschemaname}].[role] ([id], [Type_id], [Status_id], [Parent_id], [Name], [Description]) VALUES (N'RID_SME_RM_MANAGER', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME RM Manager', 'This role is for SME RM Manager');
INSERT INTO [${dbxschemaname}].[role] ([id], [Type_id], [Status_id], [Parent_id], [Name], [Description]) VALUES (N'RID_SME_OPERATIONS_MANAGER', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME Operations Manager', 'This role is for SME Operations Manager');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM_MANAGER', N'PID01');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPERATIONS_MANAGER', N'PID01');
GO
INSERT INTO [${dbxschemaname}].[role] ([id], [Type_id], [Status_id], [Parent_id], [Name], [Description]) VALUES (N'RID_SME_IT_ADMINISTRATOR', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME IT Administrator', 'This role is for SME IT Administrator');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_IT_ADMINISTRATOR', N'PID01');
GO
INSERT INTO [${dbxschemaname}].[permission] ([id],[Type_id],[Status_id],[Name],[Description],[isComposite],[PermissionValue]) VALUES ('PID423','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewAddExternalService','Permission to add services in Request Overview','0','TRUE');
INSERT INTO [${dbxschemaname}].[permission] ([id],[Type_id],[Status_id],[Name],[Description],[isComposite],[PermissionValue]) VALUES ('PID424','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewUpdateExternalService','Permission to update services in Request Overview','0','TRUE');
INSERT INTO [${dbxschemaname}].[permission] ([id],[Type_id],[Status_id],[Name],[Description],[isComposite],[PermissionValue]) VALUES ('PID425','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewDeleteExternalService','Permission to delete services in Request Overview','0','TRUE');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_UNDERWRITER', 'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_UNDERWRITER', 'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_UNDERWRITER', 'PID425');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_SUPERVISOR', 'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_SUPERVISOR', 'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES ('RID_SUPERVISOR', 'PID425');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID425');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID425');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID425');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailOps', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailSupervisor', N'PID183');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailSupervisor', N'PID423');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailSupervisor', N'PID424');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailSupervisor', N'PID425');
GO
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_UNDERWRITER', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_UNDERWRITER', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_UNDERWRITER', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RELATIONSHIP_MANAGER', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RELATIONSHIP_MANAGER', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RELATIONSHIP_MANAGER', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_OPERATIONS', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_OPERATIONS', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_OPERATIONS', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID148');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID260');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID264');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID265');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailOps', N'PID149');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailOps', N'PID261');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailOps', N'PID265');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailOps' and [Permission_id] = 'PID270');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailOps' and [Permission_id] = 'PID270');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailOps' and [Permission_id] = 'PID270');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailOps' and [Permission_id] = 'PID270');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID271');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID271');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID271');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailRM' and [Permission_id] = 'PID271');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID272');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID272');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID272');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailSupervisor' and [Permission_id] = 'PID272');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID273');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID273');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID273');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_RetailUW' and [Permission_id] = 'PID273');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SECRETARY', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RELATIONSHIP_MANAGER', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_UNDERWRITER', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SUPERVISOR', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_OPERATIONS', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_RM', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_OPS', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SUPERVISOR', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailRM', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailOps', N'PID249');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailSupervisor', N'PID249');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_OPERATIONS' and [Permission_id] = 'PID378');
GO
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_OPS' and [Permission_id] = 'PID233');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_OPS' and [Permission_id] = 'PID362');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID136');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID137');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID138');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID139');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID238');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID239');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID240');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID241');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID154');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID155');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID156');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID157');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID274');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID275');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID276');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID277');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID189');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID190');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID191');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID192');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID344');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID345');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID346');
DELETE FROM [${dbxschemaname}].[rolepermission] WHERE ([Role_id] = 'RID_SME_SUPERVISOR' and [Permission_id] = 'PID347');
GO