package com.kony.dbputilities.fileutil;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.lang.model.element.ElementKind;

import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.StringUtils;
import com.temenos.logger.Logger;
import com.temenos.logger.alert.Alert;
import com.temenos.logger.diagnostics.Diagnostic;
import org.apache.log4j.PropertyConfigurator;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.WebColors;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.WriterProperties;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Div;
import com.itextpdf.layout.element.IBlockElement;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import com.itextpdf.layout.property.VerticalAlignment;
import com.kony.dbputilities.util.DBPUtilitiesConstants;
import com.kony.dbputilities.util.HelperMethods;
import com.kony.dbputilities.util.JSONUtil;

public class PDFGenerator implements FileGenerator {
	private static final Alert alert = Logger.forAlert().forModule("Infinity", "DIGITALBANKING");
	private static final Diagnostic diagnostic = Logger.forDiagnostic().forModule("Infinity", "DIGITALBANKING");
    private JsonObject userDetails;
    private String imgFileName = "RetailBankingBanner.png";
    private String logoFileName = "kony_logo.png";
    private String currencyCode = "$";
    private String[] fields = new String[] { "transactionDate", "description", "transactionId" };
    private String[] userDisplayName = new String[] { "Name: ", "Account: ", "Branch: " };
    private String[] userKeys = new String[] { "userfirstname", "account", "bankName" };
    String[] headers = new String[] { "Date", "Description", "Transaction ID", "Withdrawal", "Deposit", "Balance" };
    private String[] combinedStatementHeaders = new String[] { "Transaction Date","Ref #Number", "Description", "Amount", "Balance"};
    private String[] combinedStatementFields = new String[] { "transactionDate", "transactionId","description", "amount","fromAccountBalance"};
    private String contactNumberDisplayName = "Phone";
    private String emailIdDisplayName = "E-Mail";
    
    private Set<String> depositTypes;
    private String[] loanFields = new String[] { "Date", "Principal", "Interest", "Charges","Amount","OutstandingBalance" };
    private String[] loanUserDisplayName = new String[] { "Name: ", "Account Name: ", "Account Number: " };
    private String[] combinedStatementDetails = new String[] {"Report Generated on:","Report Generated by:","Bank Name:","Start Date:","End Date:"};
    private String[] loanUserKeys = new String[] { "userfirstname", "accountName", "account" };
    String[] loanHeaders = new String[] { "Payment Date", "Principal", "Interest", "Charge", "Amount($)", "OutStanding Amount($)" };
	private Map<String, String> summary;
	private String paymentDateFormat="MM/dd/yyyy";
    
    @Override
    public byte[] generateFile(JsonArray data, String title, String generatedBy, String startDate, String endDate,
            Map<String, String> fieldList, Map<String, Object> otherData, String filters) throws IOException {
        init();
        if (null != otherData.get("userDetails")) {
            this.userDetails = (JsonObject) otherData.get("userDetails");
        }
        if (StringUtils.isNotBlank((String) otherData.get("imgFileName"))) {
            this.imgFileName = (String) otherData.get("imgFileName");
        }
        InputStream is = PDFGenerator.class.getClassLoader().getResourceAsStream("log4j.properties");
		try {
		PropertyConfigurator.configure(is);
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(os, new WriterProperties());
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);
        addFont(document);
        addLogoImage(document);
        Table userDetailsTable = new Table(UnitValue.createPercentArray(new float[] { 1, 1 }));
        userDetailsTable.addCell(new Cell().add(getUserDatilsDiv(userDisplayName,userKeys)).setBorder(Border.NO_BORDER));
        userDetailsTable.addCell(new Cell().add(getNoteDiv()).setBorder(Border.NO_BORDER));
        userDetailsTable.addCell(new Cell().add(getDateDiv(startDate, endDate)).setBorder(Border.NO_BORDER));
        userDetailsTable.addCell(new Cell().setBorder(Border.NO_BORDER));
        document.add(userDetailsTable);

        Table transTable = getTransactionsTable();
        addTransactionsHeader(transTable,headers);
        addTransactionsData(data, transTable);
        document.add(transTable);

        document.close();
        return os.toByteArray();
	    }
		catch (Exception e) {
			alert.prepareError(e).log();
			return null;
		}finally {
	    	if (is!=null) {
	    		try {
	    			is.close();
	    		}
	    		catch(Exception e)
	    		{
	    			alert.prepareError(e).log();
	    		}
	    	}
	    }
    }

    private void init() {
        depositTypes = new HashSet<>();
        depositTypes.add("Deposit");
        depositTypes.add("Interest");
        depositTypes.add("ReceivedP2P");
        depositTypes.add("ReceivedRequest");
        depositTypes.add("Credit");
    }

    private void addTransactionsData(JsonArray data, Table transTable) {
        if (null != data && data.size() > 0) {
            for (int i = data.size() - 1; i >= 0; i--) {
                JsonObject rowData = data.get(i).getAsJsonObject();

                addRow(transTable, rowData,this.fields);
                String amount = rowData.get("amount").getAsString();
                if (!amount.startsWith("-")) {
                    transTable.addCell(getNoBorderCell());
                    transTable.addCell(getNoBorderCell().add(new Paragraph(amount)));
                } else {
                    transTable.addCell(getNoBorderCell().add(new Paragraph(amount)));
                    transTable.addCell(getNoBorderCell());
                }
                if (rowData.has("fromAccountBalance")) {
                    transTable.addCell(
                            getNoBorderCell().add(new Paragraph(rowData.get("fromAccountBalance").getAsString())));
                }
            }
        }
    }

    private void addRow(Table transTable, JsonObject rowData,String[] fields) {
        try {
            for (int i = 0; i < fields.length; i++) {
                if (rowData.has(fields[i])) {
                    String data = rowData.get(fields[i]).getAsString();
                    if ("transactionDate".equals(fields[i])) {
                        data = HelperMethods.convertDateFormat(data, "MM/dd/yyyy");
                    }
                    if ("Date".equals(fields[i])) {
                        data = HelperMethods.convertDateFormat(data, this.paymentDateFormat);
                    }
                    transTable.addCell(getNoBorderCell().add(new Paragraph(data)));
                } else {
                    transTable.addCell(getNoBorderCell());
                }
            }
        } catch (Exception e) {
            alert.prepareError("Error in generation of pdf",e).log();
        }
    }
    private void addCombinedStatementFooter(Document document) {
    	int numberOfPages = document.getPdfDocument().getNumberOfPages();
        for (int i = 1; i <= numberOfPages; i++) {
        	document.showTextAligned(new Paragraph(String.format("Page %s of %s", i, numberOfPages)),
                    559, 10, i, TextAlignment.RIGHT, VerticalAlignment.BOTTOM, 0);
        }
	}

    
    private void addCombinedStatementRow(Table transTable, JsonObject rowData,String[] fields) throws Exception {
        try {
            for (int i = 0; i < fields.length; i++) {
                if (rowData.has(fields[i]) && StringUtils.isNotBlank(rowData.get(fields[i]).getAsString())) {
                    String data = rowData.get(fields[i]).getAsString();
                    if ("transactionDate".equals(fields[i])) {
                        data = HelperMethods.convertDateFormat(data, "MM/dd/yyyy");
                    }
                    if ("amount".equals(fields[i])) {
                        data = this.currencyCode + data;
                    }
                    if ("fromAccountBalance".equals(fields[i])) {
                        data = this.currencyCode + data;
                    }
                    if ("transactionDate".equals(fields[i])) {
                    	transTable.addCell(getCombinedStatmentCell().add(new Paragraph(data).setFontColor(ColorConstants.BLACK, 0.9f)));
                    } else {
                    	transTable.addCell(getCombinedStatmentCell().add(new Paragraph(data)));
                    }
                } else {
                    transTable.addCell(getNoBorderCell().setBorderBottom(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.8f, 0.6f)).setHeight(20f));
                }
            }
            transTable.setMarginLeft(3f);
        } catch (Exception e) {
            alert.prepareError("Error in generation of pdf",e).log();
            throw e;
        }
    }
    
    private IBlockElement getDateDiv(String from, String to) {
        Div dateDiv = new Div();
        Paragraph p = new Paragraph("Account Statement").setBold();
        dateDiv.add(p);
        if (StringUtils.isNotBlank(from) && StringUtils.isNotBlank(to)) {
            Paragraph date = new Paragraph("Statement from " + from + " to " + to);
            dateDiv.add(date);
        }
        return dateDiv;
    }

    private Table getTransactionsTable() {
        return new Table(UnitValue.createPercentArray(new float[] { 1, 2, 2, 1, 1, 1 }));
    }

    private Table getCombinedStatmentsTable() {
        return new Table(UnitValue.createPercentArray(new float[] { 2, 3, 3, 2, 2}));
    }

    private Table addTransactionsHeader(Table transTable,String[] headers) {
        for (int i = 0; i < headers.length; i++) {
            transTable.addHeaderCell(new Cell().setBackgroundColor(WebColors.getRGBColor("azure"))
                    .add(new Paragraph(headers[i])).setBorder(Border.NO_BORDER).setTextAlignment(TextAlignment.LEFT));
        }
        transTable.getHeader().setBorder(new SolidBorder(0.1f));
        transTable.setWidth(UnitValue.createPercentValue(100));
        return transTable;
    }
    
    private Table addCombinedStatementHeader(Table table,String[] headers) {
        for (int i = 0; i < headers.length; i++) {
            table.addHeaderCell(getNoBorderCell().setMarginLeft(3f).setVerticalAlignment(VerticalAlignment.MIDDLE).setBackgroundColor(ColorConstants.LIGHT_GRAY,0.1f).setFontColor(ColorConstants.BLACK, 0.9f)
                    .add(new Paragraph(headers[i])));
        }
        table.getHeader().setBorderTop(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.1f, 0.6f)).setBorderBottom(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.1f, 0.6f));
        table.setWidth(UnitValue.createPercentValue(100));
        return table;
    }

    public void addLogoImage(Document document) throws IOException {
    	InputStream is = PDFGenerator.class.getClassLoader().getResourceAsStream(this.imgFileName);
    	try {
        Image konyLogo = new Image(ImageDataFactory.create(IOUtils.toByteArray(is)));
        Div imageDiv = new Div().setBorder(new SolidBorder(0.2f));
        imageDiv.setHeight(50.5f);
        imageDiv.setWidth(UnitValue.createPercentValue(100));
        konyLogo.setWidth(imageDiv.getWidth());
        konyLogo.setHeight(imageDiv.getHeight());
        imageDiv.add(konyLogo);
        document.add(imageDiv);
    	}
		catch (Exception e) {
			alert.prepareError(e).log();
			return null;
		}finally {
	    	if (is!=null) {
	    		try {
	    			is.close();
	    		}
	    		catch(Exception e)
	    		{
	    			alert.prepareError(e).log();
	    		}
	    	}
	    }
    }
    
    private void addInfinityLogoImage(Document document) throws IOException {
        InputStream is = PDFGenerator.class.getClassLoader().getResourceAsStream(this.logoFileName);
        try {
        Image konyLogo = new Image(ImageDataFactory.create(IOUtils.toByteArray(is)));
        Div imageDiv = new Div();
        imageDiv.setHeight(UnitValue.createPercentValue(30));
        imageDiv.setWidth(UnitValue.createPercentValue(35));
        konyLogo.setWidth(imageDiv.getWidth());
        konyLogo.setHeight(imageDiv.getHeight());
        imageDiv.add(konyLogo);
        document.add(imageDiv);
        }
		catch (Exception e) {
			alert.prepareError(e).log();
			return null;
		}finally {
	    	if (is!=null) {
	    		try {
	    			is.close();
	    		}
	    		catch(Exception e)
	    		{
	    			alert.prepareError(e).log();
	    		}
	    	}
	    }
    }

    private Div getHeaderDetailsDiv(String[] userDetailsKeys, String title, String generatedOn, String generatedBy, String bankName, String startDate, String endDate) {
        float userMargin = 10f;
        Div userContainer = new Div().setWidth((int)(PageSize.A4.getWidth()/1.14));
        userContainer.setBorder(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.4f, 0.6f));
        userContainer.add(new Paragraph(title).setMarginLeft(10f).setFontSize(12f).setMarginTop(5f).setBold());
        Table userTable = new Table(3);
        userTable.setWidth(UnitValue.createPercentValue(100));
        userTable.setBorder(Border.NO_BORDER);
        Cell key = null;
        
        key = getNoBorderCell();
        key.add(new Paragraph("Report Generated by:")).setFontColor(ColorConstants.BLACK, 0.5f);
        key.setWidth(UnitValue.createPercentValue(50));
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph("Bank Name: ")).setFontColor(ColorConstants.BLACK, 0.5f);
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph(bankName));
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        key.setBold();
        
        key = getNoBorderCell();
        key.add(new Paragraph(generatedBy));
        key.setWidth(UnitValue.createPercentValue(50));
        key.setBold();
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph("Start Date: ")).setFontColor(ColorConstants.BLACK, 0.5f);
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph(startDate));
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        key.setBold();
        
        key = getNoBorderCell();
        key.add(new Paragraph("Report Generated On:")).setFontColor(ColorConstants.BLACK, 0.5f);
        key.setWidth(UnitValue.createPercentValue(50));
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph("End Date: ")).setFontColor(ColorConstants.BLACK, 0.5f);
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        
        key = getNoBorderCell();
        key.add(new Paragraph(endDate));
        key.setWidth(UnitValue.createPercentValue(25));
        userTable.addCell(key);
        key.setBold();
        
        key = getNoBorderCell();
        key.add(new Paragraph(generatedOn));
        key.setWidth(UnitValue.createPercentValue(50));
        key.setBold();
        userTable.addCell(key);
        
        Div userDiv = new Div();
        userDiv.setMargin(userMargin);
        userDiv.setMarginTop(5f);
        userContainer.setMarginTop(5f);
        userContainer.setMarginBottom(5f);
        userDiv.add(userTable);
        userContainer.add(userDiv);
        return userContainer;
    }
    
    public Div getUserDatilsDiv(String[] userDisplayName,String[] userKeys) {
        float containerMargin = 11f;
        float userMargin = 5f;
        Div userContainer = new Div().setBorder(new SolidBorder(0.2f))
                .setWidth(PageSize.A4.getWidth() / 2 - 2 * containerMargin);
        userContainer.setMargin(containerMargin);

        Table userTable = new Table(2);
        userTable.setBorder(Border.NO_BORDER);

        Cell key = null;
        Cell value = null;
        for (int i = 0; i < userDisplayName.length; i++) {
            key = getNoBorderCell();
            value = getNoBorderCell();
            key.add(new Paragraph(userDisplayName[i]));
            if (null != this.userDetails && this.userDetails.has(userKeys[i])
                    && !userDetails.get(userKeys[i]).isJsonNull()) {
                value.add(new Paragraph(userDetails.get(userKeys[i]).getAsString()));
            }
            userTable.addCell(key);
            userTable.addCell(value);
        }
        // adding user phone

        if(JSONUtil.hasKey(this.userDetails, "ContactNumbers")) {
        	JsonArray communications =this.userDetails.getAsJsonArray("ContactNumbers");
        	for (JsonElement communicationElement : communications ) {
        	    JsonObject communicationObject = communicationElement.getAsJsonObject();
        	    if(JSONUtil.hasKey(communicationObject, "isPrimary" ) && 
        	    		communicationObject.get("isPrimary").getAsString().equals("true")) {
                    String contactNumber = JSONUtil.hasKey(communicationObject, "Value" ) ? 
                            		communicationObject.get("Value").getAsString() : "";
                    if(StringUtils.isNotBlank(contactNumber)) {
                    	key = getNoBorderCell();
                        value = getNoBorderCell();
                        key.add(new Paragraph(this.contactNumberDisplayName));
                        value.add(new Paragraph(contactNumber));
                        userTable.addCell(key);
                        userTable.addCell(value);
                    }
        	    	break;
        	    }
        	}
        }
        
        // adding user email        
        if(JSONUtil.hasKey(this.userDetails, "EmailIds")) {
        	JsonArray communications =this.userDetails.getAsJsonArray("EmailIds");
        	for (JsonElement communicationElement : communications ) {
        	    JsonObject communicationObject = communicationElement.getAsJsonObject();
        	    if(JSONUtil.hasKey(communicationObject, "isPrimary" ) && 
        	    		communicationObject.get("isPrimary").getAsString().equals("true")) {
                    String emailId = JSONUtil.hasKey(communicationObject, "Value" ) ? 
                            		communicationObject.get("Value").getAsString() : "";
                    if(StringUtils.isNotBlank(emailId)) {
                    	key = getNoBorderCell();
                        value = getNoBorderCell();
                    	key.add(new Paragraph(this.emailIdDisplayName));
                        value.add(new Paragraph(emailId));
                        userTable.addCell(key);
                        userTable.addCell(value);
                    }
        	    	break;
        	    }
        	}
        }

        key = getNoBorderCell();
        value = getNoBorderCell();
        key.add(new Paragraph("Address: "));
        StringBuilder sb = new StringBuilder();
        String[] addressComps = new String[] { "AddressLine1", "AddressLine2", "CityName", "ZipCode" };
        
        JsonObject primaryAddress=new JsonObject();
        if(null != this.userDetails 
        		&& this.userDetails.has("Addresses")) {
        	JsonArray address=this.userDetails.getAsJsonArray("Addresses");
        	
        	for (JsonElement addressElement : address) {
        	    JsonObject addressObject = addressElement.getAsJsonObject();
        	    if(addressObject.has("isPrimary") && addressObject.get("isPrimary").getAsString().equals("true")) {
        	    	primaryAddress=addressObject;
        	    	break;
        	    }
        	}
        }
        for (int i = 0; i < addressComps.length; i++) {
            if (null != primaryAddress &&  primaryAddress.has(addressComps[i])) {
                if (sb.length() > 0) {
                    sb.append(", ");
                }
                sb.append(primaryAddress.get(addressComps[i]).getAsString());
            }
        }
        value.add(new Paragraph(sb.toString()));
        userTable.addCell(key);
        userTable.addCell(value);
        
		if (this.summary != null && this.summary.size() > 0) {
			if (this.summary.containsKey("OverDueInstallmentsCount")) {
				key = getNoBorderCell();
				value = getNoBorderCell();
				key.add(new Paragraph("OverDue Payments: "));
				value.add(new Paragraph(this.summary.get("OverDueInstallmentsCount")));
				userTable.addCell(key);
				userTable.addCell(value);
			}
			if (this.summary.containsKey("PaidInstallmentsCount")) {
				key = getNoBorderCell();
				value = getNoBorderCell();
				key.add(new Paragraph("Paid Installments: "));
				value.add(new Paragraph(this.summary.get("PaidInstallmentsCount")));
				userTable.addCell(key);
				userTable.addCell(value);
			}
			if (this.summary.containsKey("FutureInstallmentsCount")) {
				key = getNoBorderCell();
				value = getNoBorderCell();
				key.add(new Paragraph("Future Payments: "));
				value.add(new Paragraph(this.summary.get("FutureInstallmentsCount")));
				userTable.addCell(key);
				userTable.addCell(value);
			}

		}
        
        Div userDiv = new Div();
        userDiv.setMargin(userMargin);
        userDiv.add(userTable);
        userContainer.add(userDiv);
        return userContainer;
    }

    public Div getNoteDiv() {
        Div noteDiv = new Div();
        noteDiv.add(new Paragraph(
                "Note:\n Please note that the content of this statement will be considered correct if no error is reported within 30 days of reciept of statement. The "
                        + "address of the statement is that on record with the bank as the day of requesting this content. Please note that the content of this statement"
                        + "will be considered correct if no error is reported within 30 days of reciept of statement. The address of the statement is that on record with the bank as the day of requesting this content.")
                                .setFontSize(11f));
        return noteDiv;
    }
    
    public Cell getNoBorderCell() {
        return new Cell().setBorder(Border.NO_BORDER);
    }
    
    private Cell getCombinedStatmentCell() {
    	return getNoBorderCell().setBorderBottom(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.8f, 0.6f)).setHeight(20f).setVerticalAlignment(VerticalAlignment.MIDDLE).setPadding(3);
    }
    
    public void addFont(Document document) throws IOException {
        PdfFont font = PdfFontFactory.createFont(StandardFonts.TIMES_ROMAN);
        document.setFont(font);
    }
    
    private void addCombinedStatementFont(Document document) throws IOException {
        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        document.setFontSize(10f);
        document.setFont(font);
    }

    @Override
    public String getContentType() {
        return "application/pdf";
    }
    
    @Override
    public byte[] generateLoanFile(JsonArray data, String title, String generatedBy,
            Map<String, String> fieldList, Map<String, Object> otherData, String filters,String installmentType,Map<String, String> summaryDetails,String paymentDateFormat) throws IOException {

        init();
        if (null != otherData.get("userDetails")) {
            this.userDetails = (JsonObject) otherData.get("userDetails");
        }
        if (StringUtils.isNotBlank((String) otherData.get("imgFileName"))) {
            this.imgFileName = (String) otherData.get("imgFileName");
        }
        
        this.summary=summaryDetails;
        this.paymentDateFormat=paymentDateFormat;
        InputStream is = PDFGenerator.class.getClassLoader().getResourceAsStream("log4j.properties");
        try {
        PropertyConfigurator.configure(is);
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(os, new WriterProperties());
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);
        addFont(document);
        addLogoImage(document);
        Table userDetailsTable = new Table(UnitValue.createPercentArray(new float[] { 1, 1 }));
        userDetailsTable.addCell(new Cell().add(getUserDatilsDiv(loanUserDisplayName,loanUserKeys)).setBorder(Border.NO_BORDER));
        userDetailsTable.addCell(new Cell().add(getNoteDiv()).setBorder(Border.NO_BORDER));
        //userDetailsTable.addCell(new Cell().add(getDateDiv(startDate, endDate)).setBorder(Border.NO_BORDER));
        userDetailsTable.addCell(new Cell().setBorder(Border.NO_BORDER));
        document.add(userDetailsTable);
		
		Table overdueTable = getTransactionsTable();
		Table paidTable = getTransactionsTable();
		Table futureTable = getTransactionsTable();
		
		if (null != data && data.size() > 0) {
			 for (int i = data.size() - 1; i >= 0; i--) {
				 String Type = data.get(i).getAsJsonObject().get("InstallmentType").getAsString();
				 if(Type.equalsIgnoreCase(DBPUtilitiesConstants.PAID)) {
					 addRow(paidTable, data.get(i).getAsJsonObject(),this.loanFields);
				 }
				 else if(Type.equalsIgnoreCase(DBPUtilitiesConstants.DUE)) {
					 addRow(overdueTable, data.get(i).getAsJsonObject(),this.loanFields);
				 }
				 else if(Type.equalsIgnoreCase(DBPUtilitiesConstants.FUTURE)) {
					 addRow(futureTable, data.get(i).getAsJsonObject(),this.loanFields);
				 }	 
			 }
		}
		
		if (installmentType.equalsIgnoreCase("All") ) {
			addtable(document, overdueTable, "Overdue Payments");
			addtable(document, paidTable, "Paid Installlments");
			addtable(document, futureTable, "Future Payments");
		}
		else if ( installmentType.equalsIgnoreCase("Paid")) {
			addtable(document, paidTable, "Paid Installlments");
		}
		else if ( installmentType.equalsIgnoreCase("overdue")) {
			addtable(document, overdueTable, "Overdue Payments");
		}
		else if (installmentType.equalsIgnoreCase("future")) {
			addtable(document, futureTable, "Future Payments");
		}
		
        document.close();
        return os.toByteArray();
	    }
		catch (Exception e) {
			alert.prepareError(e).log();
			return null;
		}finally {
	    	if (is!=null) {
	    		try {
	    			is.close();
	    		}
	    		catch(Exception e)
	    		{
	    			alert.prepareError(e).log();
	    		}
	    	}
	    }
        
    }
    
    private void addtable(Document document, Table scheduletable, String header) {
    	Div headingDiv = new Div();
        Paragraph p = new Paragraph(header).setBold();
        headingDiv.add(p);
        document.add(headingDiv);
		addTransactionsHeader(scheduletable,loanHeaders);
        document.add(scheduletable);
    }
    
	@Override
	public byte[] generateCombinedStatementsFile(JsonArray dataObject, String title, String generatedBy,
			String startDate, String endDate, Map<String, String> fieldList, String bankName, String currencyCode,
			String paymentDateFormat) throws Exception {
		init();
        this.paymentDateFormat=paymentDateFormat;
        InputStream is= PDFGenerator.class.getClassLoader().getResourceAsStream("log4j.properties");
        try {
        PropertyConfigurator.configure(is);
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(os, new WriterProperties());
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);
        addCombinedStatementFont(document);
        addInfinityLogoImage(document);
        SimpleDateFormat reportGeneratedDateFormat = new SimpleDateFormat("MM/dd/yyyy, hh:mm a");
        String generatedOn = reportGeneratedDateFormat.format(new Date());
        this.currencyCode = StringUtils.isBlank(currencyCode) ? "$" : currencyCode;
        try {
        	startDate = StringUtils.isBlank(startDate) ? "NA" : HelperMethods.convertDateFormat(startDate, "MM/dd/yyyy");
        	endDate = StringUtils.isBlank(endDate) ? "NA" : HelperMethods.convertDateFormat(endDate, "MM/dd/yyyy");
		} catch (ParseException e) {
			alert.prepareError("Error while parsing date" +e).log();
		}
        Table userDetailsTable = new Table(UnitValue.createPercentArray(new float[] { 2,1,1}));
        userDetailsTable.addCell(new Cell().add(getHeaderDetailsDiv(combinedStatementDetails, title, generatedOn,generatedBy,bankName,startDate,endDate)).setBorder(Border.NO_BORDER));
        document.add(userDetailsTable);
        for(int i=0;i<dataObject.size();i++) {
        	JsonElement accountElement = dataObject.get(i);
        	JsonObject accountObject = accountElement.getAsJsonObject();
        	String accountName = null;
        	String accountNumber = null;
        	JsonArray data = new JsonArray();
        	if(StringUtils.isNotBlank(accountObject.get("accountName").toString()))
        		accountName = accountObject.get("accountName").getAsString();
        	if(StringUtils.isNotBlank(accountObject.get("accountNumber").toString()))
        		accountNumber = accountObject.get("accountNumber").getAsString();
        	if(StringUtils.isNotBlank(accountObject.get("transactionsList").toString()))
				data = accountObject.get("transactionsList").getAsJsonArray();
			Table accountTransactions = getCombinedStatmentsTable();
			if (null != data && data.size() > 0) {
				for (int j = data.size() - 1; j >= 0; j--) {
					try {
						addCombinedStatementRow(accountTransactions, (JsonObject) data.get(j), this.combinedStatementFields);
					} catch (Exception e) {
						alert.prepareError("Error while adding data  to pdf").log();
					}
				}
			}
			accountTransactions.setFontColor(ColorConstants.BLACK, 0.5f);
			addCombinedStatementsTable(document, accountTransactions, accountName, accountNumber);
		}
        //addCombinedStatementFooter(document);
        document.close();
        return os.toByteArray();
        }
		catch (Exception e) {
			alert.prepareError(e).log();
			return null;
		}finally {
	    	if (is!=null) {
	    		try {
	    			is.close();
	    		}
	    		catch(Exception e)
	    		{
	    			alert.prepareError(e).log();
	    		}
	    	}
	    }
	}
    
	private void addCombinedStatementsTable(Document document, Table combinedStatementTable, String accountName, String accountNumber) {
    	Div headingDiv = new Div();
    	Table accountTable = new Table(2);
    	accountTable.addCell(getNoBorderCell().add(new Paragraph(accountName + ":   " )).setFontColor(ColorConstants.BLACK, 0.5f));
    	accountTable.addCell(getNoBorderCell().add(new Paragraph(accountNumber)).setFontColor(ColorConstants.BLACK, 0.9f));
    	headingDiv.setBorderTop(new SolidBorder(ColorConstants.LIGHT_GRAY, 0.3f, 0.6f));
        accountTable.setPaddingTop(2);
        accountTable.setFontSize(11f);
        accountTable.setMarginTop(2f);
        headingDiv.add(accountTable);
        document.add(headingDiv);
		addCombinedStatementHeader(combinedStatementTable, combinedStatementHeaders);
        document.add(combinedStatementTable);
    }
}