UPDATE [${dbxschemaname}].[alertsubtype] SET [recipienttype] = '1' WHERE ([id] = 'APPROVE_SINGLE_INTERNATIONAL_TRANSFER_APPROVERS');
GO

UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getContractInfinityUsers' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getContractInfinityUsers';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'checkIfCompanyExists' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'checkIfCompanyExists';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getListOfContractsByStatus' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getListOfContractsByStatus';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getCompanyAccounts' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getCompanyAccounts';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getContractAccounts' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getContractAccounts';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getRelativeCoreCustomerContractDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getRelativeCoreCustomerContractDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getContractDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getContractDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'searchCoreCustomers' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'searchCoreCustomers';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getContractFeatureActionLimits' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getContractFeatureActionLimits';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'createContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'createContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getCoreRelativeCustomers' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getCoreRelativeCustomers';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'enrollContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'enrollContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getCoreCustomerContractDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getCoreCustomerContractDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'updateContractStatus' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'updateContractStatus';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getCoreCustomerAccounts' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getCoreCustomerAccounts';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'searchContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'searchContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'editContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'editContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Contract' ,[operation] = 'getCoreCustomerRoleFeatureActionLimits' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Contract' AND [operation] = 'getCoreCustomerRoleFeatureActionLimits';
GO

UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomerLimits' ,[operation] = 'getCustomerActionLimits' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomerLimits' AND [operation] = 'getCustomerActionLimits';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'getCustomRoleDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'getCustomRoleDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'getOrganizationCustomRoles' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'getOrganizationCustomRoles';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'createCustomRole' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'createCustomRole';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'updateCustomRole' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'updateCustomRole';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'deleteCustomRole' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'deleteCustomRole';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'verifyCustomRoleName' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'verifyCustomRoleName';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'CustomRole' ,[operation] = 'applyCustomRole' WHERE [service_name] = 'RBObjects' AND [object_name] = 'CustomRole' AND [operation] = 'applyCustomRole';

GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'updateInfinityUserStatus' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'updateInfinityUserStatus';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserContractCoreCustomerActions' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserContractCoreCustomerActions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserLimits' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserLimits';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getCustomRoleByCompanyID' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getCustomRoleByCompanyID';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'updateInfinityProspect' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'updateInfinityProspect';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getUserApprovalPermissions' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getUserApprovalPermissions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'CreateInfinityUserWithContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'CreateInfinityUserWithContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'createRetailContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'createRetailContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserContractDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserContractDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getCoreCustomerFeatureActionLimits' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getCoreCustomerFeatureActionLimits';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'enrollRetailUser' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'enrollRetailUser';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserFeatureActions' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserFeatureActions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'createBusinessContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'createBusinessContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserAccounts' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserAccounts';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'assignInfinityUserToPrimaryRetailContract' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'assignInfinityUserToPrimaryRetailContract';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'createInfinityProspect' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'createInfinityProspect';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_1' ,[operation] = 'getInfinityUserContractCustomers' WHERE [service_name] = 'RBObjects' AND [object_name] = 'InfinityUser' AND [operation] = 'getInfinityUserContractCustomers';
GO

UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyLoginMFAOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestOTPRegisterMB' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestOTPRegisterMB';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestMFAOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getBBCustomerServiceLimit' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getBBCustomerServiceLimit';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyOTPPreLoginMB' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyOTPPreLoginMB';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'dbxVerifyOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'dbxVerifyOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getUserNameAndPasswordPolicies' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getUserNameAndPasswordPolicies';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyOTPPreLoginEnroll' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyOTPPreLoginEnroll';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'updateDBXUserName' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'updateDBXUserName';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyMFAOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getUserNamePolicy' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getUserNamePolicy';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'sendActivationCodeForEnrollment' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'sendActivationCodeForEnrollment';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getPasswordPolicy' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getPasswordPolicy';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'editBBCustomerServiceLimit' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'editBBCustomerServiceLimit';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestPreLoginOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestPreLoginOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getMFAServiceConfig' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getMFAServiceConfig';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'sendCustomerUnlockEmail' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'sendCustomerUnlockEmail';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyLoginMFASecurityQuestions' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyLoginMFASecurityQuestions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getPasswordRules' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getPasswordRules';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'regenerateActivationCode' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'regenerateActivationCode';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'IsSharedTokenValid' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'IsSharedTokenValid';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'CreateDbxMicroBusinessOwner' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'CreateDbxMicroBusinessOwner';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'ResendActivationLink' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'ResendActivationLink';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getUserNameRules' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getUserNameRules';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'createBBCustomerServiceLimit' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'createBBCustomerServiceLimit';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestLoginMFAOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getCustomerTypes' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getCustomerTypes';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'verifyDbxUserName' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'verifyDbxUserName';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getEAgreementPdfDownloaded' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getEAgreementPdfDownloaded';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'fetchAuthorizedSignatories' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'fetchAuthorizedSignatories';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getAPIPasswordLockoutSettings' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getAPIPasswordLockoutSettings';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'updateCustomerDetailsForAdmin' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'updateCustomerDetailsForAdmin';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getCustomerCommunication' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getCustomerCommunication';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getAccountActionCustomerApproverList' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getAccountActionCustomerApproverList';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestOTPPreLoginMB' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestOTPPreLoginMB';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getAddressTypes' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getAddressTypes';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'resetUserPasswordFromEmail' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'resetUserPasswordFromEmail';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getUserNameAndPasswordRules' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getUserNameAndPasswordRules';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getDbxUserStatus' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getDbxUserStatus';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'sendDbxResetPasswordEmail' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'sendDbxResetPasswordEmail';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getGroups' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getGroups';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'downloadEAgreementPdf' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'downloadEAgreementPdf';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'requestOTPPreLogin' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'requestOTPPreLogin';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'createGroup' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'createGroup';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'dbxRequestOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'dbxRequestOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'getUserNameRulesAndPolicy' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'getUserNameRulesAndPolicy';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'IsEmailLinkActive' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'IsEmailLinkActive';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'ExternalUsers_2' ,[operation] = 'updateCustomerProfile' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'updateCustomerProfile';

GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'Features' ,[operation] = 'getAccessPolicies' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Feature' AND [operation] = 'getAccessPolicies';

GO
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('5b73230a-516a-4431-a3fa-35720f3084db', 'ExternalUserManagement', 'ExternalUsers_2', 'createCustomerInPartyandT24', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('5f787292-114b-43f5-9bf3-6955c403481d', 'ExternalUserManagement', 'ExternalUsers_2', 'CreateEmploymentDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('417a28ac-6959-4f40-b042-e6ef5f2104d5', 'ExternalUserManagement', 'ExternalUsers_2', 'createTaxDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('d363cdad-cfb5-4c89-afa1-c30a82c740c4', 'ExternalUserManagement', 'ExternalUsers_2', 'getCustomerDetailsInPartyAndT24', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('3e97a9b8-3e48-41c4-b219-db94d260b49d', 'ExternalUserManagement', 'ExternalUsers_2', 'getCustomerDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('bba4ff9e-00d4-425e-b1b0-79725628327f', 'ExternalUserManagement', 'ExternalUsers_2', 'GetDueDiligenceDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('67820191-4f4e-4ded-9686-9556d872b307', 'ExternalUserManagement', 'ExternalUsers_2', 'GetEmploymentDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('c059e3c2-edd8-4850-8f4e-686fc68ea77b', 'ExternalUserManagement', 'ExternalUsers_2', 'GetTaxDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e6fa4663-e550-4f66-8ba2-b0c66420cba1', 'ExternalUserManagement', 'ExternalUsers_2', 'updateCitizenship', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('d9cb1378-572d-40bc-8805-cda22004a6d6', 'ExternalUserManagement', 'ExternalUsers_2', 'updateCustomerInPartyAndT24', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('55e74807-36d6-4daa-827a-6f7cb6460762', 'ExternalUserManagement', 'ExternalUsers_2', 'UpdateEmploymentDetails', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('77b9872a-803a-4111-8ad3-c0c820c7e8c4', 'ExternalUserManagement', 'ExternalUsers_2', 'updateTaxDetails', 'ALLOW');
GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'search' ,[operation] = 'customerSearch' WHERE [service_name] = 'RBObjects' AND [object_name] = 'search' AND [operation] = 'customerSearch';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'search' ,[operation] = 'getCustomerBasicInformation' WHERE [service_name] = 'RBObjects' AND [object_name] = 'search' AND [operation] = 'getCustomerBasicInformation';

GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'serviceDefinition' ,[operation] = 'getServiceDefinitionRoles' WHERE [service_name] = 'RBObjects' AND [object_name] = 'serviceDefinition' AND [operation] = 'getServiceDefinitionRoles';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'serviceDefinition' ,[operation] = 'getServiceDefinitionsForContracts' WHERE [service_name] = 'RBObjects' AND [object_name] = 'serviceDefinition' AND [operation] = 'getServiceDefinitionsForContracts';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'serviceDefinition' ,[operation] = 'getServicedefinitionAndRoleFeatures' WHERE [service_name] = 'RBObjects' AND [object_name] = 'serviceDefinition' AND [operation] = 'getServicedefinitionAndRoleFeatures';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'DigitalProfile' ,[operation] = 'get' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DigitalProfile' AND [operation] = 'get';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'DigitalProfile' ,[operation] = 'update' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DigitalProfile' AND [operation] = 'update';
GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'EnrollmentSecurity' ,[operation] = 'generateCaptchaForEnrollment' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'Security' AND [operation] = 'generateCaptchaForEnrollment';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'requestLoginMFAOTP' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'requestLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyLoginMFAOTP' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyLoginMFASecurityQuestions' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyLoginMFASecurityQuestions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'SMS' ,[operation] = 'sendKMSSMS' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'sendKMSSMS';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Email' ,[operation] = 'sendKMSEmail' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'sendKMSEmail';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'SMS' ,[operation] = 'smsOTP' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DbxUser' AND [operation] = 'smsOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Browser' ,[operation] = 'getSupportedBrowserMatrix' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Browser' AND [operation] = 'getSupportedBrowserMatrix';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Browser' ,[operation] = 'logBrowser' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Browser' AND [operation] = 'logBrowser';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Application' ,[operation] = 'create' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Application' AND [operation] = 'create';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Configurations' ,[operation] = 'getSystemConfigurations' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Configurations' AND [operation] = 'getSystemConfigurations';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Country' ,[operation] = 'getAllCountries' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Country' AND [operation] = 'getAllCountries';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Country' ,[operation] = 'getCountryCodes' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Country' AND [operation] = 'getCountryCodes';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Country' ,[operation] = 'get' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Country' AND [operation] = 'get';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'Currency' ,[operation] = 'get' WHERE [service_name] = 'RBObjects' AND [object_name] = 'Currency' AND [operation] = 'get';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'OutageMessage' ,[operation] = 'createOutageMessage' WHERE [service_name] = 'RBObjects' AND [object_name] = 'OutageMessage' AND [operation] = 'createOutageMessage';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'OutageMessage' ,[operation] = 'getOutageMessage' WHERE [service_name] = 'RBObjects' AND [object_name] = 'OutageMessage' AND [operation] = 'getOutageMessage';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'OutageMessage' ,[operation] = 'updateOutageMessage' WHERE [service_name] = 'RBObjects' AND [object_name] = 'OutageMessage' AND [operation] = 'updateOutageMessage';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'OutageMessage' ,[operation] = 'deleteOutageMessage' WHERE [service_name] = 'RBObjects' AND [object_name] = 'OutageMessage' AND [operation] = 'deleteOutageMessage';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'States' ,[operation] = 'getAllRegions' WHERE [service_name] = 'RBObjects' AND [object_name] = 'States' AND [operation] = 'getAllRegions';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'States' ,[operation] = 'get' WHERE [service_name] = 'RBObjects' AND [object_name] = 'States' AND [operation] = 'get';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'States' ,[operation] = 'getRegionDetails' WHERE [service_name] = 'RBObjects' AND [object_name] = 'States' AND [operation] = 'getRegionDetails';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Utility',[object_name] = 'States' ,[operation] = 'getAllCities' WHERE [service_name] = 'RBObjects' AND [object_name] = 'States' AND [operation] = 'getAllCities';
GO
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'TrackDeviceRegistration' ,[operation] = 'trackDeviceRegistration' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'TrackDeviceRegistration' AND [operation] = 'trackDeviceRegistration';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Security' ,[operation] = 'generateCaptcha' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'Security' AND [operation] = 'generateCaptcha';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'requestResetPasswordOTP' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'requestResetPasswordOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyUser' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyUser';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'resetUserPassword' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'resetUserPassword';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'getPasswordRulesAndPolicy' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'getPasswordRulesAndPolicy';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'getPasswordLockoutSettings' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'getPasswordLockoutSettings';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users' ,[operation] = 'verifyPin' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers' AND [operation] = 'verifyPin';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Security' ,[operation] = 'verifyCaptcha' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'Security' AND [operation] = 'verifyCaptcha';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyOTPPreLogin' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyOTPPreLogin';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users' ,[operation] = 'getUserProfileImage' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'getUserProfileImage';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'customCreate' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'customCreate';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'dbx_updateCustomerDeviceInfo' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'dbx_updateCustomerDeviceInfo';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'get' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'get';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'create' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'create';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'dbx_registerCustomerDevice' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'dbx_registerCustomerDevice';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'delete' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'delete';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'DeviceRegistration' ,[operation] = 'dbx_isDeviceRegistered' WHERE [service_name] = 'RBObjects' AND [object_name] = 'DeviceRegistration' AND [operation] = 'dbx_isDeviceRegistered';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'ExternalUserManagement',[object_name] = 'EnrollmentSecurity' ,[operation] = 'generateCaptchaForEnrollment' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'Security' AND [operation] = 'generateCaptchaForEnrollment';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'requestLoginMFAOTP' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'requestLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyLoginMFAOTP' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyLoginMFAOTP';
UPDATE [${dbxschemaname}].[service_permission_mapper] SET [service_name] = 'Login',[object_name] = 'Users_2' ,[operation] = 'verifyLoginMFASecurityQuestions' WHERE [service_name] = 'ExternalUserManagement' AND [object_name] = 'ExternalUsers_2' AND [operation] = 'verifyLoginMFASecurityQuestions';
GO
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('fba6678d-09b1-41t6-8cj3-17176dbd7c9t', 'Login', 'Users', 'partialupdate', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('17y8827a-ci96-4fac-be2f-0ea8u4ef1d06', 'ExternalUserManagement', 'ExternalUsers', 'getReferenceById', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('cb49ce41-fdij-4fc8-8c91-fb9i80j9g647', 'Login', 'Users', 'get', 'ALLOW');
GO
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('ff84d4a2-e0e5-429a-8ca0-8fccc86832e2', 'PartyExperienceAPI', 'Party', 'createPartyIdentifier', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('2c5c8a16-fd7c-4e7e-b309-2d654a7bb993', 'PartyExperienceAPI', 'Party', 'createParty', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('e7d0e748-5df4-410b-83fb-97e48eb72c8e', 'PartyExperienceAPI', 'Party', 'getPartyRelations', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('7fecdaaa-bc5f-44ee-84a5-4521b66d8531', 'PartyExperienceAPI', 'Party', 'createPartyRelations', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('6df9a40f-688f-4603-9fa8-08501725dc3d', 'PartyExperienceAPI', 'Party', 'updatePartyRelations', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('0ef1867f-9481-4379-8982-a21e695518f2', 'PartyExperienceAPI', 'Party', 'getParty', 'ALLOW');
INSERT INTO [${dbxschemaname}].[service_permission_mapper] ([id], [service_name], [object_name], [operation], [permissions]) VALUES ('7c140876-d035-4f4b-a640-cf8c18dc84d4', 'PartyExperienceAPI', 'Party', 'updateParty', 'ALLOW');
GO
