#Table Data constants
C_AUDIT_TRANSACTION_CUST_USERCONST=systemuser
C_TRANSACTION_MODULE_CONST=Fund Transfer


#transaction activity
channel=chnl
username=user
currencyCode=payeecurrency
payeeName=payeename
serviceName=transactiontype
fromAccount=fromaccountnumber
toAccount=toaccountnumber
amount=amount
status=status
routingNumber=routingnumber
swiftCode=swiftcode
ibanCode=iban
type=transactiontype
description=transactionsnotes
transactionDate=transactiondate
#transactionDate=scheduleddate
toAccountType=toaccounttype
fromAccountType=fromaccounttype
toMobileOrEmail=paypersonemail
batchId=batchid
referenceNumber=referenceid
transactionId=referenceid



#customer activity
activityType=activitytype
moduleName=modulename
userName=user
description=description
status=status
ipAddress=ipaddress
device=device
operatingSystem=plat
referenceId=referenceid
errorCode=errorcode
createdby=createdby
customerId=customerid



#moneymovement activity
##Not Exists in input or output of transfer
ExpenseCategory_id=expensecategory_id
toAccountBalance=toaccountbalance
checkNumber=checknumber1
imageURL1=imageurl1
imageURL2=imageurl2
deliverBy=deliverby
requestCreatedDate=requestcreateddate
isPaypersonDeleted=ispaypersondeleted
frontImage1=frontimage1
frontImage2=frontimage2
backImage1=backimage1
backImage2=backimage2
checkDesc=checkdesc
bankName1=bankname1
bankName2=bankname2
withdrawlAmount1=withdrawlamount1
withdrawlAmount2=withdrawlamount2
cashAmount=cashamount
isDisputed=isdisputed
disputeDescription=disputedescription
disputeReason=disputereason
disputeStatus=disputestatus
disputeDate=disputedate
isPayeeDeleted=ispayeedeleted
amountRecieved=amountrecieved
statementReference=statementreference
transCreditDebitIndicator=transcreditdebitindicator
bookingDateTime=bookingdatetime
valueDateTime=valuedatetime
transactionInformation=transactioninformation
transactionAmount=transactionamount
chargeAmount=chargeamount
chargeCurrency=chargecurrency
targetCurrency=targetcurrency
unitCurrency=unitcurrency
exchangeRate=exchangerate
contractIdentification=contractidentification
quotationDate=quotationdate
transactionCode=transactioncode
instructedAmount=instructedamount
instructedCurrency=instructedcurrency
transactionSubCode=transactionsubcode
proprietaryTransactionCode=proprietarytransactioncode
proprietaryTransactionIssuer=proprietarytransactionissuer
balanceCreditDebitIndicator=balancecreditdebitindicator
balanceType=balancetype
balanceAmount=balanceamount
balanceCurrency=balancecurrency
merchantName=merchantname
creditorAgentName=creditoragentname
merchantCategoryCode=merchantcategorycode
creditorAgentSchemeName=creditoragentschemename
creditorAgentIdentification=creditoragentidentification
creditorAgentaddressType=creditoragentaddresstype
creditorAgentDepartment=creditoragentdepartment
creditorAgentSubDepartment=creditoragentsubdepartment
creditorAgentStreetName=creditoragentstreetname
creditorAgentBuildingNumber=creditoragentbuildingnumber
creditorAgentPostCode=creditoragentpostcode
creditorAgentTownName=creditoragenttownname
creditorAgentCountrySubDivision=creditoragentcountrysubdivision
creditorAgentCountry=creditoragentcountry
creditorAgentAddressLine=creditoragentaddressline
creditorAccountIdentification=creditoraccountidentification
creditorAccountName=creditoraccountname
creditorAccountSeconIdentification=creditoraccountseconidentification
debtorAgentSchemeName=debtoragentschemename
debtorAgentIdentification=debtoragentidentification
debtorAgentName=debtoragentname
debtorAgentAddressType=debtoragentaddresstype
debtorAgentDepartment=debtoragentdepartment
debtorAgentSubDepartment=debtoragentsubdepartment
debtorAgentStreetName=debtoragentstreetname
debtorAgentBuildingNumber=debtoragentbuildingnumber
dedtorAgentPostCode=dedtoragentpostcode
debtorAgentTownName=debtoragenttownname
debtorAgentCountrySubDivision=debtoragentcountrysubdivision
debtorAgentCountry=debtoragentcountry
debtorAgentAddressLine=debtoragentaddressline
debtorAccountSeconIdentification=debtoraccountseconidentification
cardInstrumentSchemeName=cardinstrumentschemename
cardInstrumentAuthorisationType=cardinstrumentauthorisationtype
cardInstrumentName=cardinstrumentname
cardInstrumentIdentification=cardinstrumentidentification
sortCode=sortcode
FirstPaymentDateTime=firstpaymentdatetime
NextPaymentDateTime=nextpaymentdatetime
FinalPaymentDateTime=finalpaymentdatetime
StandingOrderStatusCode=standingorderstatuscode
FP_Amount=fp_amount
FP_Currency=fp_currency
NP_Amount=np_amount
NP_Currency=np_currency
FPA_Amount=fpa_amount
FPA_Currency=fpa_currency
MerchantCustomerIdentification=merchantcustomeridentification
##Exists in input or output of transfer
isScheduled=isscheduled
Payee_id=payeeid
Bill_id=billid
Type_id=transactiontype
Reference_id=referenceid
fromAccountNumber=fromaccountnumber
fromAccountBalance=fromaccountbalance
toAccountNumber=toaccountnumber
amount=amount
convertedAmount=convertedamount
transactionCurrency=transactioncurrency
baseCurrency=basecurrency
Status_id=status
statusDesc=statusdescription
notes=transactionsnotes
hasDepositImage=hasdepositimage
description=description
scheduledDate=scheduleddate
transactionDate=transactiondate
createdDate=createddate
transactionComments=transactioncomments
toExternalAccountNumber=externalaccountnumber
Person_Id=personid
frequencyType=frequencytype
numberOfRecurrences=numberofrecurrences
frequencyStartDate=frequencystartdate
frequencyEndDate=frequencyenddate
checkImage=checkimage
checkImageBack=checkimageback
cashlessOTPValidDate=cashlessotpvaliddate
cashlessOTP=cashlessotp
cashlessPhone=cashlessphone
cashlessEmail=cashlessemail
cashlessPersonName=cashlesspersonname
cashlessMode=cashlessmode
cashlessSecurityCode=cashlesssecuritycode
cashWithdrawalTransactionStatus=cashwithdrawaltransactionstatus
cashlessPin=cashlesspin
category=category
billCategory=billcategory
recurrenceDesc=recurrencedesc
p2pContact=p2pcontact
p2pRequiredDate=p2prequireddate
penaltyFlag=penaltyflag
payoffFlag=payoffflag
viewReportLink=viewreportlink
fee=fee
feeCurrency=feecurrency
feePaidByReceipent=feepaidbyreceipent
checkNumber1=checknumber1
checkNumber2=checknumber2
payeeCurrency=payeecurrency
billid=billid
payeeName=payeename
checkDateOfIssue=checkdateofissue
checkReason=checkreason
requestValidity=requestValidityinmonths
addressLine=addressline1
sourceCurrency=payeecurrency
creditorAccountSchemeName=creditoraccountschemename
debtorAccountSchemeName=debtoraccountschemename
debtorAccountName=debtoraccountname
IBAN=iban
ConsentId=consentid
Initiation_InstructionIdentification=initiation_instructionidentification
Initiation_EndToEndIdentification=initiation_endtoendidentification
RI_Reference=ri_reference
RI_Unstructured=ri_unstructured
RiskPaymentContextCode=riskpaymentcontextcode
beneficiaryName=beneficiaryname
bankName=bankname
swiftCode=swiftcode
DomesticPaymentId=domesticpaymentid
linkSelf=linkself
StatusUpdateDateTime=statusupdatedatetime
dataStatus=datastatus
#serviceName=servicename
payPersonName=paypersonname


##Audit activity
jobHistoryId=schedulerjobdefinitionid
isSchedulingEngineRecord=schedulermoneymovementid
EventType=eventtype
EventSubType=eventsubtype
EventId=eventid
Status_id=status_id
AppId=appid
UserName=user
Customer_id=customerid
AdminUserName=csr_username
AdminUserRole=csr_role
Producer=producer
MoneyMovementRefId=monymovementrefid
createdby=createdby
createdts=createdts
sessionId=sessionid
deviceModel=dm
operatingSystem=os
browser=ua
deviceId=did
channel=chnl
appVersion=aver
platform=plat
currency=transactioncurrency
mfa_State=mfastate
mfa_ServiceKey=servicekey
mfa_Type=mfatype
eventts=eventdispatcherserverdate
creditcardnumber=cardnumber
phoneNumber=phone
email=email
isCSRAssist=iscsrassist
appSessionId=appsessionid
payeeNickName=payeenickname
relationshipNumber=accountnumber

#Non searchable fields
C_NON_SEARCHABLES=transactionType:transactiontype,checkNumber:checknumber,accountNumber:accountnumber,dbperrorcode:dbperrorcode,errmsg:errmsg,opstatus:opstatus
