##Assign the below properties for connecting to database
db.user=root
db.password=root
db.host=localhost
db.port=3306
db.conn.props=useSSL=false&requireSSL=false&verifyServerCertificate=false
db.name=dbxdb
db.type=MYSQL
db.schemaName=dbxdb
upgradedFromVersion=
upgradedToVersion=202304

#Input LegalEntities
db.updateLe=GB0010001
db.insertLe=GB0010005

#config_value update for configurations Table 
# please provide the json data below
jsonConfigValue=[{"id": "GB0010001","companyName": "Europe","region": "Europe","typeId": "LEGALENTITY","parentId": "GR23698574","countryCode": "EU","baseCurrency": "Euro","language": "EN","effectiveDate": "1990-09-20","closeDate": "2045-09-20","description": "LE for Europe"}]