-- ARB-34845 Start
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-APPROVE', N'Approve International Recepient', N'Approve creation, editing or deletion of an international-bank beneficiary', 3, null, N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTER_BANK_ACCOUNT_FUND_TRANSFER-APPROVE', N'Approve Inter Bank Recepient', N'Approve creation, editing or deletion of an inter-bank beneficiary', 3, null, N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTRA_BANK_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTRA_BANK_FUND_TRANSFER-APPROVE', N'Approve Intra Bank Recepient', N'Approve creation, editing or deletion of an intra-bank beneficiary', 3, null, N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-APPROVE', N'Self Approve International Recepient', N'Self Approve creation, editing or deletion of an international-bank beneficiary', 3, N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTER_BANK_ACCOUNT_FUND_TRANSFER-APPROVE', N'Self Approve Inter Bank Recepient', N'Self Approve creation, editing or deletion of an inter-bank beneficiary', 3, N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTRA_BANK_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTRA_BANK_FUND_TRANSFER-APPROVE', N'Self Approve Intra Bank Recepient', N'Self Approve creation, editing or deletion of an intra-bank beneficiary', 3, N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'APPROVE', N'CUSTOMERID_LEVEL', 1, N'ALL');

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'de-DE', N'Approve International Payee', N'Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-GB', N'Approve International Payee', N'Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-US', N'Approve International Payee', N'Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'es-ES', N'Approve International Payee', N'Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'fr-FR', N'Approve International Payee', N'Approve International Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'de-DE', N'Approve Inter Bank Payee', N'Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-GB', N'Approve Inter Bank Payee', N'Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-US', N'Approve Inter Bank Payee', N'Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'es-ES', N'Approve Inter Bank Payee', N'Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'fr-FR', N'Approve Inter Bank Payee', N'Approve Inter Bank Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'de-DE', N'Approve Intra Bank Payee', N'Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-GB', N'Approve Intra Bank Payee', N'Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'en-US', N'Approve Intra Bank Payee', N'Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'es-ES', N'Approve Intra Bank Payee', N'Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'fr-FR', N'Approve Intra Bank Payee', N'Approve Intra Bank Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'de-DE', N'Self Approve Intra Bank Payee', N'Self Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-GB', N'Self Approve Intra Bank Payee', N'Self Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-US', N'Self Approve Intra Bank Payee', N'Self Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'es-ES', N'Self Approve Intra Bank Payee', N'Self Approve Intra Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'fr-FR', N'Self Approve Intra Bank Payee', N'Self Approve Intra Bank Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'de-DE', N'Self Approve Inter Bank Payee', N'Self Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-GB', N'Self Approve Inter Bank Payee', N'Self Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-US', N'Self Approve Inter Bank Payee', N'Self Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'es-ES', N'Self Approve Inter Bank Payee', N'Self Approve Inter Bank Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'fr-FR', N'Self Approve Inter Bank Payee', N'Self Approve Inter Bank Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'de-DE', N'Self Approve International Payee', N'Self Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-GB', N'Self Approve International Payee', N'Self Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'en-US', N'Self Approve International Payee', N'Self Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'es-ES', N'Self Approve International Payee', N'Self Approve International Payee', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'fr-FR', N'Self Approve International Payee', N'Self Approve International Payee', N'ALL');

INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTRA_BANK_FUND_TRANSFER', N'Approve Intra Bank Recepient', N'Intra Bank Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'Approve Inter Bank Recepient', N'Interbank Account to Account Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'Approve International Recepient', N'International Account to Account Fund Transfer N', N'ALL');

-- ARB-34845 End

-- set the action levels of beneficiary management to customer level, instead of account level
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET isAccountLevel='0' , actionlevelId = N'CUSTOMERID_LEVEL' WHERE id= N'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';

INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient-International Transfer', N'International account fund transfer edit recipient', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient Linkage-International Transfer', N'International account fund transfer edit recipient linkage', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient Optional Field-International Transfer', N'International account fund transfer edit recipient optional field',0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');

INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient-Domestic Transfer', N'Inter bank fund transfer edit recipient', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient Linkage-Domestic Transfer', N'Inter bank fund transfer edit recipient linkage', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTER_BANK_ACCOUNT_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', N'Edit Recipient Optional Field-Domestic Transfer', N'Inter bank fund transfer edit recipient optional field', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');

INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTRA_BANK_FUND_TRANSFER-CREATE', N'Edit Recipient-Same bank Transfer', N'Intra bank fund transfer edit recipient', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTRA_BANK_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTRA_BANK_FUND_TRANSFER-CREATE', N'Edit Recipient Linkage-Same bank Transfer', N'Intra bank fund transfer edit recipient linkage', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [DisplaySequence], [dependency], [accesspolicyId], [actionlevelId], [isApprovalAction], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTRA_BANK_FUND_TRANSFER', N'RETAIL_AND_BUSINESS_BANKING', N'NON_MONETARY', N'INTRA_BANK_FUND_TRANSFER-CREATE', N'Edit Recipient Optional Field-Same bank Transfer', N'Intra bank fund transfer edit recipient optional field', 0, null, N'CREATE', N'CUSTOMERID_LEVEL', 0, N'ALL');

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'ALL');

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'ALL');

INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'ALL');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id], [Action_id], [companyLegalUnit]) VALUES (N'TYPE_ID_BUSINESS', N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'de-DE', N'Edit International Beneficiary', N'Edit International Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'en-GB', N'Edit International Beneficiary', N'Edit International Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'en-US', N'Edit International Beneficiary', N'Edit International Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'es-ES', N'Edit International Beneficiary', N'Edit International Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'fr-FR', N'Edit International Beneficiary', N'Edit International Beneficiary', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'de-DE', N'Edit International Beneficiary Linkage', N'Edit International Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-GB', N'Edit International Beneficiary Linkage', N'Edit International Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-US', N'Edit International Beneficiary Linkage', N'Edit International Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'es-ES', N'Edit International Beneficiary Linkage', N'Edit International Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'fr-FR', N'Edit International Beneficiary Linkage', N'Edit International Beneficiary Linkage', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'de-DE', N'Edit International Beneficiary Optional Fields', N'Edit International Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-GB', N'Edit International Beneficiary Optional Fields', N'Edit International Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-US', N'Edit International Beneficiary Optional Fields', N'Edit International Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'es-ES', N'Edit International Beneficiary Optional Fields', N'Edit International Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'fr-FR', N'Edit International Beneficiary Optional Fields', N'Edit International Beneficiary Optional Fields', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'de-DE', N'Edit Inter Bank Beneficiary', N'Edit Inter Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'en-GB', N'Edit Inter Bank Beneficiary', N'Edit Inter Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'en-US', N'Edit Inter Bank Beneficiary', N'Edit Inter Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'es-ES', N'Edit Inter Bank Beneficiary', N'Edit Inter Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'fr-FR', N'Edit Inter Bank Beneficiary', N'Edit Inter Bank Beneficiary', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'de-DE', N'Edit Inter Bank Beneficiary Linkage', N'Edit Inter Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-GB', N'Edit Inter Bank Beneficiary Linkage', N'Edit Inter Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-US', N'Edit Inter Bank Beneficiary Linkage', N'Edit Inter Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'es-ES', N'Edit Inter Bank Beneficiary Linkage', N'Edit Inter Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'fr-FR', N'Edit Inter Bank Beneficiary Linkage', N'Edit Inter Bank Beneficiary Linkage', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'de-DE', N'Edit Inter Bank Beneficiary Optional Fields', N'Edit Inter Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-GB', N'Edit Inter Bank Beneficiary Optional Fields', N'Edit Inter Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-US', N'Edit Inter Bank Beneficiary Optional Fields', N'Edit Inter Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'es-ES', N'Edit Inter Bank Beneficiary Optional Fields', N'Edit Inter Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'fr-FR', N'Edit Inter Bank Beneficiary Optional Fields', N'Edit Inter Bank Beneficiary Optional Fields', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'de-DE', N'Edit Intra Bank Beneficiary', N'Edit Intra Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'en-GB', N'Edit Intra Bank Beneficiary', N'Edit Intra Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'en-US', N'Edit Intra Bank Beneficiary', N'Edit Intra Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'es-ES', N'Edit Intra Bank Beneficiary', N'Edit Intra Bank Beneficiary', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'fr-FR', N'Edit Intra Bank Beneficiary', N'Edit Intra Bank Beneficiary', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'de-DE', N'Edit Intra Bank Beneficiary Linkage', N'Edit Intra Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-GB', N'Edit Intra Bank Beneficiary Linkage', N'Edit Intra Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'en-US', N'Edit Intra Bank Beneficiary Linkage', N'Edit Intra Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'es-ES', N'Edit Intra Bank Beneficiary Linkage', N'Edit Intra Bank Beneficiary Linkage', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'fr-FR', N'Edit Intra Bank Beneficiary Linkage', N'Edit Intra Bank Beneficiary Linkage', N'ALL');

INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'de-DE', N'Edit Intra Bank Beneficiary Optional Fields', N'Edit Intra Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-GB', N'Edit Intra Bank Beneficiary Optional Fields', N'Edit Intra Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'en-US', N'Edit Intra Bank Beneficiary Optional Fields', N'Edit Intra Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'es-ES', N'Edit Intra Bank Beneficiary Optional Fields', N'Edit Intra Bank Beneficiary Optional Fields', N'ALL');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'fr-FR', N'Edit Intra Bank Beneficiary Optional Fields', N'Edit Intra Bank Beneficiary Optional Fields', N'ALL');

INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Intra Bank Recepient', N'Intra Bank Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Intra Bank Recepient Linkage', N'Intra Bank Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Intra Bank Recepient Optional Fields', N'Intra Bank Fund Transfer', N'ALL');

INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Inter Bank Recepient', N'Interbank Account to Account Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Inter Bank Recepient Linkage', N'Interbank Account to Account Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit Inter Bank Recepient Optional Fields', N'Interbank Account to Account Fund Transfer', N'ALL');

INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit International Bank Recepient', N'International Account to Account Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit International Bank Recepient Linkage', N'International Account to Account Fund Transfer', N'ALL');
INSERT INTO [${dbxschemaname}].[dependentactions] ([actionId], [dependentactionId], [featureId], [actionName], [featureName], [companyLegalUnit]) VALUES (N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', N'INTRA_BANK_FUND_TRANSFER', N'Edit International Bank Recepient Optional Fields', N'International Account to Account Fund Transfer', N'ALL');

-- set the approve dependency action for the create/edit/delete feature actions of beneficiary management
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE [${dbxschemaname}].[featureaction] SET approveFeatureAction= N'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE id= N'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE [${dbxschemaname}].[featureaction] SET name= N'Create Recipient-Same Bank Transfer' WHERE id= N'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET name= N'Delete Recipient-Same Bank Transfer' WHERE id= N'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET name= N'Create Recipient-Domestic Transfer' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET name= N'Delete Recipient-Domestic Transfer' WHERE id= N'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET name= N'Create Recipient-International Transfer' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE [${dbxschemaname}].[featureaction] SET name= N'Delete Recipient-International Transfer' WHERE id= N'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';