INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'392', N'NUO_CONFIG_SME_BUNDLE',N'PREFERENCE',N'SME_T24_CUSTOMER_CONFIG','Configuration for SME T24 Customer',N'{\"externalSystemId\":\"PARTYMS\",\"language\": \"1\",\"accountOfficerId\": \"251\",\"industryId\":\"1000\",\"target\":\"4\",\"sectorTypeSme\":\"2015\",\"sectorTypeCompany\":\"2001\",\"sectorTypeRelatedCompany\":\"2003\",\"customerStatus\":\"71\",\"infinitySystemId\":\"DBX\"}', 'SERVER', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'393', N'NUO_CONFIG_BUNDLE',N'PREFERENCE',N'RETAIL_T24_CUSTOMER_CONFIG','Configuration for Retail T24 Customer',N'{\"externalSystemId\":\"PARTYMS\",\"language\": \"1\",\"accountOfficerId\": \"26\",\"industryId\":\"1000\",\"target\":\"4\",\"sectorTypeRetail\":\"1000\",\"customerStatus\":\"4\",\"infinitySystemId\":\"DBX\"}', 'SERVER', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'394', N'NUO_CONFIG_BUNDLE',N'PREFERENCE',N'OTHER_INCOME','Configuration for Other Income Options',N'[\"Bonus year1\",\"Bonus year 2\",\"Commission\",\"Investment Income\",\"Rental Income\",\"Pension\"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{"DEPOSITS":["DEPOSITS","RETAIL.DEPOSIT"],"CHECKING":["CURRENT.ACCOUNTS","RETAIL.CURRENT.ACCOUNT"],"SAVINGS":["SAVINGS.ACCOUNTS","RETAIL.SAVINGS.ACCOUNT"],"CREDITCARDS":["CREDIT.CARDS"],"LOANS":["SMALL.BUSINESS.LOANS","BUSINESS.BANKING.LOAN"],"OVERDRAFT":["OVERDRAFT.ACCOUNTS"]}' WHERE (configuration_id = 'SME_17');

UPDATE [${dbxschemaname}].[configurations] SET config_value = '{"BUSINESS.BANKING.LOAN" :{ "loanPurpose": ["Working Capital Finance","Capital Expenditure","Technology up-gradation","Expansion","Others"]}}' WHERE (configuration_id = 'SME_96');

UPDATE [${dbxschemaname}].[configurations] set config_value = '[SMALL.BUSINESS.LOANS,OVERDRAFT.ACCOUNTS,CREDIT.CARDS,BUSINESS.BANKING.LOAN]' WHERE (configuration_id = 'c631b8a5-e2f2-494e-a3b1-3b9bcd83ba09');

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'395', N'NUO_CONFIG_BUNDLE',N'PREFERENCE',N'INCOME_SOURCE','Configuration for Income Source Options',N'[\"Dividends\",\"Interest\",\"Investor\"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);