DROP PROCEDURE IF EXISTS `dbxdb`.`MultiEntityDataUpgrade202306`;
$$
CREATE PROCEDURE `dbxdb`.`MultiEntityDataUpgrade202306`(
    IN _companyLegalUnit VARCHAR(50) CHARACTER SET UTF8 COLLATE utf8_general_ci
)
BEGIN

    SET foreign_key_checks = 0;
    -- feature
    INSERT IGNORE INTO `dbxdb`.`feature` (`id`, `App_id`, `name`, `description`, `Type_id`, `Status_id`, `DisplaySequence`, `isPrimary`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'Beneficiary Management', 'Beneficiary Management', 'NON_MONETARY', 'SID_FEATURE_ACTIVE', '34', '0', _companyLegalUnit);

    -- featuredisplaynamedescription
    INSERT IGNORE INTO `dbxdb`.`featuredisplaynamedescription` (`Feature_id` ,`Locale_id` ,`displayName` ,`displayDescription`, `softdeleteflag`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT' ,'en-GB' ,'Beneficiary Management' ,'Beneficiary Management' ,'0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featuredisplaynamedescription` (`Feature_id` ,`Locale_id` ,`displayName` ,`displayDescription`, `softdeleteflag`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT' ,'de-DE' ,'Beneficiary Management' ,'Beneficiary Management' ,'0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featuredisplaynamedescription` (`Feature_id` ,`Locale_id` ,`displayName` ,`displayDescription`, `softdeleteflag`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT' ,'en-US' ,'Beneficiary Management' ,'Beneficiary Management' ,'0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featuredisplaynamedescription` (`Feature_id` ,`Locale_id` ,`displayName` ,`displayDescription`, `softdeleteflag`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT' ,'es-ES' ,'Beneficiary Management' ,'Beneficiary Management' ,'0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featuredisplaynamedescription` (`Feature_id` ,`Locale_id` ,`displayName` ,`displayDescription`, `softdeleteflag`, `companyLegalUnit`) VALUES ('BENEFICIARY_MANAGEMENT' ,'fr-FR' ,'Beneficiary Management' ,'Beneficiary Management' ,'0', _companyLegalUnit);

    -- featureroletype
    INSERT IGNORE INTO `dbxdb`.`featureroletype` (`RoleType_id`, `Feature_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'BENEFICIARY_MANAGEMENT', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureroletype` (`RoleType_id`, `Feature_id`, `companyLegalUnit`) VALUES ('TYPE_ID_RETAIL', 'BENEFICIARY_MANAGEMENT', _companyLegalUnit);

    -- featureaction
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient International Transfer Approval', 'Create Recipient International Transfer Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient International Transfer Self Approval', 'Create Recipient International Transfer Self Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-International Transfer', 'International account fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-International Transfer', 'International account fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);
    
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient Domestic Transfer Self Approval', 'Create Recipient Domestic Transfer Self Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient Domestic Transfer Approval', 'Create Recipient Domestic Transfer Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-Domestic Transfer', 'Inter bank fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-Domestic Transfer', 'Inter bank fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);
    
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient Same bank Transfer Self Approval', 'Create Recipient Same bank Transfer Self Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction`(`id`,`Feature_id`,`App_id`,`Type_id`,`Rrole_id`,`name`,`description`,`isAccountLevel`,`isMFAApplicable`,`MFA_id`,`isPrimary`,`DisplaySequence`,`dependency`,`softdeleteflag`,`accesspolicyId`,`actionlevelId`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT-APPROVE', 'Create Recipient Same bank Transfer Approval', 'Create Recipient Same bank Transfer Approval', 0, 0, null, 0, 50, null, 0, 'APPROVE', 'CUSTOMERID_LEVEL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-Same bank Transfer', 'Intra bank fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-Same bank Transfer', 'Intra bank fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 0, _companyLegalUnit);

    -- featureactionroletype

    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', _companyLegalUnit);

    -- actiondisplaynamedescription

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit International Beneficiary', 'Edit International Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit International Beneficiary', 'Edit International Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit International Beneficiary', 'Edit International Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit International Beneficiary', 'Edit International Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit International Beneficiary', 'Edit International Beneficiary', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve International Payee', 'Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve International Payee', 'Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve International Payee', 'Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve International Payee', 'Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve International Payee', 'Approve International Payee', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve International Payee', 'Self Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve International Payee', 'Self Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve International Payee', 'Self Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve International Payee', 'Self Approve International Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve International Payee', 'Self Approve International Payee', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', _companyLegalUnit);

    -- dependentactions

    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTRA_BANK_FUND_TRANSFER', 'Approve Intra Bank Recepient', 'Intra Bank Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient', 'Intra Bank Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient Optional Fields', 'Intra Bank Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient Linkage', 'Intra Bank Fund Transfer', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'Approve Inter Bank Recepient', 'Interbank Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient', 'Interbank Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient Optional Fields', 'Interbank Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient Linkage', 'Interbank Account to Account Fund Transfer', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'Approve International Recepient', 'International Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient', 'International Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient Optional Fields', 'International Account to Account Fund Transfer', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient Linkage', 'International Account to Account Fund Transfer', _companyLegalUnit);

    

    -- compositeaction
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID993', 'PID45', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID996', 'PID45', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1002', 'PID45', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1003', 'PID45', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', '1', '0');

    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID995', 'PID45', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID994', 'PID45', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1000', 'PID45', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1001', 'PID45', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', '1', '0');

    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID992', 'PID45', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID991', 'PID45', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'BENEFICIARY_MANAGEMENT', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1004', 'PID45', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTRA_BANK_FUND_TRANSFER', '1', '0');
    -- INSERT IGNORE INTO `dbxdb`.`compositeaction` (`id`, `Permission_id`, `Action_id`, `Feature_id`, `isEnabled`, `softdeleteflag`) VALUES ('CAID1005', 'PID45', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTRA_BANK_FUND_TRANSFER', '1', '0');

    -- groupactionlimit

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_ADMINISTRATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);


    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'GROUP_CREATOR', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);


    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`groupactionlimit` (`id`, `Group_id`, `Action_id`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'a759860a-683a-4d41-81f8-fbd97d53b608', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);

    -- servicedefinitionactionlimit
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'UID10', '0', _companyLegalUnit);

    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '5801fa32-a416-45b6-af01-b22e2de93777', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'f85d8392-9afe-4128-b23e-a370f138784f', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), 'bef2fe82-9c21-4ccb-b599-3308de18de44', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    INSERT IGNORE INTO `dbxdb`.`servicedefinitionactionlimit` (`id`, `serviceDefinitionId`, `actionId`, `createdby`, `softdeleteflag`, `companyLegalUnit`) VALUES (uuid(), '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'UID10', '0', _companyLegalUnit);
    SET foreign_key_checks = 1;
END
$$
DROP PROCEDURE IF EXISTS `dbxdb`.`UpdateActionLevelOfOldFeatureActions202306`;
$$
CREATE PROCEDURE `dbxdb`.`UpdateActionLevelOfOldFeatureActions202306`()
BEGIN
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';

    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
    UPDATE `dbxdb`.`featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

    UPDATE `dbxdb`.`featureaction` SET `name` = 'Create Recipient-Same Bank Transfer' WHERE (`id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT');
    UPDATE `dbxdb`.`featureaction` SET `name` = 'Delete Recipient-Same Bank Transfer' WHERE (`id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT');
    UPDATE `dbxdb`.`featureaction` SET `name` = 'Create Recipient-Domestic Transfer' WHERE (`id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT');
    UPDATE `dbxdb`.`featureaction` SET `name` = 'Delete Recipient-Domestic Transfer' WHERE (`id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT');
    UPDATE `dbxdb`.`featureaction` SET `name` = 'Create Recipient-International Transfer' WHERE (`id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT');
    UPDATE `dbxdb`.`featureaction` SET `name` = 'Delete Recipient-International Transfer' WHERE (`id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT');

END
$$
