#Import Letter of Credits
letterOfCreditsType = LetterOfCredits
letterOfCreditsSubType = LetterOfCreditsImport
letterOfCreditsModule = LetterOfCreditsImport

#Import Letter of Credit Drawings
LetterOfCreditsDrawingsType = LetterOfCredits
LetterOfCreditsDrawingsSubType = ReviewImportDrawing
LetterOfCreditsDrawingsModule = ReviewImportDrawing

#Import Letter of Credit Drawing SwiftAndAdvices
LetterOfCreditSwiftsAndAdvicesType = SwiftAndAdvices
LetterOfCreditSwiftsAndAdvicesSubType = GenerateImportDrawingAdvices
LetterOfCreditSwiftsAndAdvicesModule = GenerateImportDrawingAdvices

#Export Letter of Credit Drawing Payment Advice
PaymentAdviceType = SwiftAndAdvices
PaymentAdviceSubType = GenerateExportDrawingAdvices
PaymentAdviceModule = GenerateExportDrawingAdvices

#Export Letter of Credits
ExportLetterOfCreditsType = LetterOfCredits
ExportLetterOfCreditsSubType = LetterOfCreditsExport
ExportLetterOfCreditsModule = LetterOfCreditsExport

#Export Letter of Credit Drawings
ExportLetterOfCreditsDrawingType = LetterOfCredits
ExportLetterOfCreditsDrawingsSubType = ExportLCDrawing
ExportLetterOfCreditsDrawingsModule = ExportLCDrawing

#Export Letter of Credit Drawings Swifts And Advice
LetterOfCreditExportSwiftsAndAdvicesType = SwiftAndAdvices
LetterOfCreditExportSwiftsAndAdvicesSubType = GenerateExportLCAdvices
LetterOfCreditExportSwiftsAndAdvicesModule = GenerateExportLCAdvices

#Import Letter of Credit Amendment
LetterOfCreditsAmendmentType = LetterOfCredits
LetterOfCreditsAmendmentSubType = ImportLCAmendment
LetterOfCreditsAmendmentModule = ImportLCAmendment

#Export Letter of Credit Amendment
ExportLetterOfCreditsAmendmentType = LetterOfCredits
ExportLetterOfCreditsAmendmentSubType = ExportLCAmendments
ExportLetterOfCreditsAmendmentModule = ExportLCAmendments

#Issued Guarantees
GuaranteesType = LetterOfGuarantee
GuaranteesSubType = Guarantees
GuaranteesModule = Guarantees

#Issued Guarantee Letter of Credits Amendments
GuaranteeLetterOfCreditAmendmentsType = LetterOfGuarantee
GuaranteeLetterOfCreditAmendmentsSubType = GuaranteeLCAmendments
GuaranteeLetterOfCreditAmendmentsModule = GuaranteeLCAmendments

#Issued Guarantee Claim
IssuedGuaranteeClaimsType = LetterOfGuarantee
IssuedGuaranteeClaimsSubType = IssuedGuaranteeClaims
IssuedGuaranteeClaimsModule = IssuedGuaranteeClaims

#Issued Guarantee Amendments Swift And Advices
GuaranteeLetterOfCreditAmendmentsSwiftAndAdvicesType=SwiftAndAdvices
GuaranteeLetterOfCreditAmendmentsSwiftAndAdvicesSubType=GenerateGuaranteesAmendmentAdvices
GuaranteeLetterOfCreditAmendmentsSwiftAndAdvicesModule=GenerateGuaranteesAmendmentAdvices

#Received Guarantees
ReceivedGuaranteesType = LetterOfGuarantee
ReceivedGuaranteesSubType = ReceivedGuarantees
ReceivedGuaranteesModule = ReceivedGuarantees

#Received Guarantee Amendments
ReceivedGuaranteeAmendmentsType = LetterOfGuarantee
ReceivedGuaranteeAmendmentsSubType = ReceivedGuaranteeAmendments
ReceivedGuaranteeAmendmentsModule = ReceivedGuaranteeAmendments

#Received Guarantee Claim
ReceivedGuaranteeClaimsType = LetterOfGuarantee
ReceivedGuaranteeClaimsSubType = ReceivedGuaranteeClaims
ReceivedGuaranteeClaimsModule = ReceivedGuaranteeClaims

#Swifts and Messages for Received Guarantees, Amendments and Claims
ReceivedGuaranteeSwiftMessagesType = SwiftAndAdvices
ReceivedGuaranteeSwiftMessagesSubType = ReceivedGuaranteeSwiftMessages
ReceivedGuaranteeSwiftMessagesModule = ReceivedGuaranteeSwiftMessages

#Inward Collection
InwardCollectionsType = Collections
InwardCollectionsSubType = InwardCollections
InwardCollectionsModule = InwardCollections

#Inward Collection Amendments
InwardCollectionAmendmentsType = Collections
InwardCollectionAmendmentsSubType = InwardCollectionAmendments
InwardCollectionAmendmentsModule = InwardCollectionAmendments

#Outward Collections
OutwardCollectionsType = Collections
OutwardCollectionsSubType = OutwardCollections
OutwardCollectionsModule = OutwardCollections

#Outward Collection Amendments
OutwardCollectionAmendmentsType = Collections
OutwardCollectionAmendmentsSubType = OutwardCollectionModify
OutwardCollectionAmendmentsModule = OutwardCollectionModify
