SET FOREIGN_KEY_CHECKS = 0;
UPDATE `configurations` SET `config_value` = 'QUEUE_APPLICATION_RETAIL_LARGE_SIZE_PL,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_PL,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_PL,QUEUE_APPLICATION_RETAIL_LARGE_SIZE_OD,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_OD,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_OD,QUEUE_APPLICATION_RETAIL_CC_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CC_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CC_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CC_UK_LONDON,QUEUE_APPLICATION_RETAIL_CC_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CC_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CC_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CC_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CC_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_CHECKING_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CHECKING_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CHECKING_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CHECKING_UK_LONDON,QUEUE_APPLICATION_RETAIL_CHECKING_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CHECKING_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_SAVINGS_US_AUSTIN,QUEUE_APPLICATION_RETAIL_SAVINGS_US_ORLANDO,QUEUE_APPLICATION_RETAIL_SAVINGS_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LONDON,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_CD_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CD_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CD_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CD_UK_LONDON,QUEUE_APPLICATION_RETAIL_CD_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CD_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CD_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CD_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CD_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_DEFAULT_QUEUE,QUEUE_APPLICATION_SME_LARGE_BL,QUEUE_APPLICATION_SME_MEDIUM_BL,QUEUE_APPLICATION_SME_SMALL_BL,QUEUE_APPLICATION_SME_LARGE_OD,QUEUE_APPLICATION_SME_MEDIUM_OD,QUEUE_APPLICATION_SME_SMALL_OD,QUEUE_APPLICATION_SME_LARGE_CC,QUEUE_APPLICATION_SME_MEDIUM_CC,QUEUE_APPLICATION_SME_SMALL_CC,QUEUE_APPLICATION_SME_CURRENT_IN_HYD,QUEUE_APPLICATION_SME_CURRENT_IN_CHEN,QUEUE_APPLICATION_SME_CURRENT_US_SANFRAN,QUEUE_APPLICATION_SME_CURRENT_US_AUSTIN,QUEUE_APPLICATION_SME_CURRENT_UK_LONDON,QUEUE_APPLICATION_SME_CURRENT_UK_MANU,QUEUE_APPLICATION_SME_CURRENT_UK_LP,QUEUE_APPLICATION_SME_CURRENT_EGYPT_CAIRO,QUEUE_APPLICATION_SME_CURRENT_COMMON_OTHER,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_LARGE_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_LENDING_DEFAULT,QUEUE_APPLICATION_RETAIL_MORTGAGE_DEFAULT' WHERE (`configuration_id` = '23b62843-e025-40a4-8c22-14a9a45c6yue57w');


INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_25','INFINITY_ASSIST_CONFIG_BUNDLE','PREFERENCE','CONFIRM_AND_CANCEL_SIMULATIONS','Confirm and Cancel Popup Messages For Resimulate Screen','{\"CONFIRM\": \"CONFIRM_SIMULATION_POPUP_TEXT\",\"CANCEL\": \"CANCEL_SIMULATION_POPUP_TEXT\"}','CLIENT',1);

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_26','INFINITY_ASSIST_CONFIG_BUNDLE','PREFERENCE','MORTGAGE_BUREAU_SCORE','MIN and MAX Bureau score value of Mortgage Application','{\"MIN_BUREAU_SCORE\":\"600\", \"MAX_BUREAU_SCORE\":\"750\"}','CLIENT',1);

UPDATE `configurations` SET `config_value` = 'QUEUE_APPLICATION_RETAIL_LARGE_SIZE_PL,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_PL,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_PL,QUEUE_APPLICATION_RETAIL_LARGE_SIZE_OD,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_OD,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_OD,QUEUE_APPLICATION_RETAIL_CC_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CC_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CC_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CC_UK_LONDON,QUEUE_APPLICATION_RETAIL_CC_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CC_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CC_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CC_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CC_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_CHECKING_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CHECKING_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CHECKING_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CHECKING_UK_LONDON,QUEUE_APPLICATION_RETAIL_CHECKING_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CHECKING_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CHECKING_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_SAVINGS_US_AUSTIN,QUEUE_APPLICATION_RETAIL_SAVINGS_US_ORLANDO,QUEUE_APPLICATION_RETAIL_SAVINGS_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LONDON,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_SAVINGS_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_SAVINGS_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_CD_US_AUSTIN,QUEUE_APPLICATION_RETAIL_CD_US_ORLANDO,QUEUE_APPLICATION_RETAIL_CD_US_SANFRANCISCO,QUEUE_APPLICATION_RETAIL_CD_UK_LONDON,QUEUE_APPLICATION_RETAIL_CD_UK_MANCHESTER,QUEUE_APPLICATION_RETAIL_CD_UK_LIVERPOOL,QUEUE_APPLICATION_RETAIL_CD_EGYPT_BANHA,QUEUE_APPLICATION_RETAIL_CD_EGYPT_CAIRO,QUEUE_APPLICATION_RETAIL_CD_EGYPT_TANTA,QUEUE_APPLICATION_RETAIL_DEFAULT_QUEUE,QUEUE_APPLICATION_SME_LARGE_BL,QUEUE_APPLICATION_SME_MEDIUM_BL,QUEUE_APPLICATION_SME_SMALL_BL,QUEUE_APPLICATION_SME_LARGE_OD,QUEUE_APPLICATION_SME_MEDIUM_OD,QUEUE_APPLICATION_SME_SMALL_OD,QUEUE_APPLICATION_SME_LARGE_CC,QUEUE_APPLICATION_SME_MEDIUM_CC,QUEUE_APPLICATION_SME_SMALL_CC,QUEUE_APPLICATION_SME_CURRENT_IN_HYD,QUEUE_APPLICATION_SME_CURRENT_IN_CHEN,QUEUE_APPLICATION_SME_CURRENT_US_SANFRAN,QUEUE_APPLICATION_SME_CURRENT_US_AUSTIN,QUEUE_APPLICATION_SME_CURRENT_UK_LONDON,QUEUE_APPLICATION_SME_CURRENT_UK_MANU,QUEUE_APPLICATION_SME_CURRENT_UK_LP,QUEUE_APPLICATION_SME_CURRENT_EGYPT_CAIRO,QUEUE_APPLICATION_SME_CURRENT_COMMON_OTHER,QUEUE_APPLICATION_RETAIL_SMALL_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_MEDIUM_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_LARGE_SIZE_MORTGAGE,QUEUE_APPLICATION_RETAIL_LENDING_DEFAULT,QUEUE_APPLICATION_RETAIL_MORTGAGE_DEFAULT,QUEUE_MORTGAGE_SERVICING,QUEUE_CUSTOMER_PROFILE' WHERE (`configuration_id` = '23b62843-e025-40a4-8c22-14a9a45c6yue57w');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('4e31abf8-0019-4c3b-876d-b3a19wcfg3bc','INFINITY_ASSIST_CONFIG_BUNDLE','PREFERENCE','SERVICE_REQUEST_MOCK_STATUS','Mock status for Service Request','{"servicing_mock_flag": "true", "fulfilmentStatus": "Completed"}','CLIENT',1);

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) 
VALUES ('e67be3e0-2b6a-4772-b062-18f704718cf3','INFINITY_ASSIST_CONFIG_BUNDLE','PREFERENCE','SERVICE_PAM_PROCESS_CONFIG','PAM process change config for Servicing journey','[{\"eventType\": \"serviceRequestCreated\",\"processDetails\": {\"processType\": \"Create\",\"processId\": \"InfinityAssist.SRParentProcess\",\"signalName\": \"\",\"uniqueSignalRequired\": false}}]','CLIENT',1);

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_27', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CUSTOMER_OFFER_LETTER', 'Config to set recipients and notification type for Retail Receiving Offer Letter Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_28', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CREDIT_APPROVAL', 'Config to set recipients and notification type for Retail receiving notification for credit Approval Notification.', '{\"notifyRecipients\" : \"RM\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_29', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_APPLICATION_APPROVED', 'Config to set recipients and notification type for Retail application Approved status Notification.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_30', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_KYC_COMPLETION', 'Config to set recipients and notification type for Retail KYC Completion Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_31', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_AIP_ILLUSTRATIVE_CUSTOMER_ACTION', 'Config to set recipients and notification type for Retail AIP Ilustrative CustomerActions Notification.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_32', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_APPLICATON_REJECTION', 'Config to set recipients and notification type for Retail Application Rejection Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_33', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_USER_OFFER_LETTER', 'Config to set recipients and notification type for Retail Receiving Offer Letter Notification.', '{\"notifyRecipients\" : \"RM\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_34', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_DENIED_APPLICATION', 'Config to set recipients and notification type for Retail Denied Application Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_35', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_CUSTOMER_OFFER_LETTER', 'Config to set recipients and notification type for SME Receiving Offer Letter Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_36', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_CUSTOMER_OFFER_LETTER_COAPPLICANT', 'Config to set recipients and notification type for SME Receiving Offer Letter Notification.', '{\"notifyRecipients\" : \"CO_APPLICANT\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_37', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_CREDIT_APPROVAL', 'Config to set recipients and notification type for SME credit Approval Notification.', '{\"notifyRecipients\" : \"RM\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_38', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_APPLICATION_APPROVED', 'Config to set recipients and notification type for SME Application Approved status Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_39', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_DENIED_APPLICATION', 'Config to set recipients and notification type for SME Denied Application Notification.', '{\"notifyRecipients\" : \"MAIN_BORROWER\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_40', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CUSTOMER_ACTION_XCREDIT_CARDS_CONSENT', 'Config to set recipients and notification type for Retail Credit cards Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_41', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CUSTOMER_ACTION_CONSENT', 'Config to set recipients and notification type for Retail Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_42', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', 'Config to set recipients and notification type for Retail offerAcceptance CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_43', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_CONSENT', 'Config to set recipients and notification type for Retail Mortgage Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_44', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', 'Config to set recipients and notification type for Retail Mortgage offerAcceptance CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_45', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_MORTGAGE_NOTIFY_CUSTOMER_ACTION_AIP', 'Config to set recipients and notification type for Retail Mortgage AIP CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_46', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_CUSTOMER_ACTION_MOBILE_PHONE_NUMBER_CONSENT', 'Config to set recipients and notification type for Retail Mobile Phone Number Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_47', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'RETAIL_NOTIFY_RETRIGGER_SIMULATION', 'Config to set recipients and notification type for Retail Retrigger Simulation.', '{\"notifyRecipients\" : \"RM\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_48', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_CUSTOMER_ACTION_XCREDIT_CARDS_CONSENT', 'Config to set recipients and notification type for SME Credit cards Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_49', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SME_NOTIFY_CUSTOMER_ACTION_CONSENT', 'Config to set recipients and notification type for SME Consent CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('IA_50', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'SMS_NOTIFY_CUSTOMER_ACTION_OFFER_ACCEPTANCE', 'Config to set recipients and notification type for SME offerAcceptance CustomerActions.', '{\"notifyRecipients\" : \"ALL_PARTIES\",\"notificationType\" : \"BOTH\"}', 'CLIENT', '1');
SET FOREIGN_KEY_CHECKS = 1;