spotlight_ak=<<KonyBankingAdminConsole-AppKey>>
spotlight_as=<<KonyBankingAdminConsole-AppSecret>>
spotlight_aat=<<AC_INTERNAL_API_ACCESS_TOKEN>>
# example: http://localhost:8080/authService/10000002/login?provider=KonyBankingAdminConsoleAPIIdentityService
spotlight_apitokenendpoint={{HTTP-Protocol}}://{{Auth-URL}}/login?provider=KonyBankingAdminConsoleIdentityService
# example: http://localhost:8080/services/data/v1/DeleteUserSessionObjService/operations/session/deleteUserSession
delete_session_exp_api={{HTTP-Protocol}}://{{Host-URL}}/services/data/v1/DeleteUserSessionObjService/operations/session/deleteUserSession
clos_user_create_exp_api={{HTTP-Protocol}}://{{Host-URL}}/services/ClosKeyClock/createKeyclockUser
clos_role_mapping_exp_api={{HTTP-Protocol}}://{{Host-URL}}/services/ClosKeyClock/createKeyclockRole

