INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('369', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_REQUESTED_LOAN_TERM_MIN', 'Configuration for minimum allowed requested Bridge Loan term', '1', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('370', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_REQUESTED_LOAN_TERM_MAX', 'Configuration for maximum allowed requested Bridge Loan term', '12', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('371', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_PURPOSE', 'Dropdown values - Purpose of Bridge Loan', '["Fund purchase of new residential property", "Renovation of new residential property", "Renovation of existing property", "Others"]', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('372', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_SOURCE_OF_REPAYMENT', 'Dropdown values - Source of Repayment of Bride Loan', '["Sale of Old Property", "Sale of Other Asset", "Maturity of Term Deposit"]', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('373', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_REPAYMENT_TYPE', 'Dropdown values - Repayment Type of Bridge Loan', '["Interest Only"]', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('374', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_EXISTING_MORTGAGE_STATUS', 'Radio button options - question on any existing mortgage present on collateral used for Bridge Loan', '["Yes, Mortgage is held with this bank", "Yes, Mortgage is held with external bank", "No"]', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('4e31aghi9-0019-4c3b-876d-b3a19eaca3bc', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'PROPERTY_VALUATION_VALUE', 'Property valuation value', '{\"valuation_percentage\" : \"80\"}', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('375', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'BRIDGE_LOAN_DOC_CHECKLIST', 'List of documents for bridge loan', '&emsp; 1.Proof of Identity\r\n&emsp;&emsp; a.Tax ID(mandatory)\r\n&emsp;&emsp; b.The ID which is entered under ID section to be pre populated\r\n(Any one document from below is Mandatory)\r\n&emsp;&emsp;&emsp;&emsp;  i. Driving License\r\n&emsp;&emsp;&emsp; &emsp; ii.Passport\r\n&emsp;&emsp;&emsp;&emsp;iii.Employee ID\r\n&emsp;&emsp;&emsp;&emsp; iv.Photo ID card issued by Local Government  <br>\r\n&emsp;2.Proof of Address : (Any one document from below is Mandatory)   \r\n&emsp;&emsp; a.Driving License    \r\n&emsp;&emsp; b.Passport    \r\n&emsp;&emsp; c.Utility Bills    \r\n&emsp;&emsp; d.Employer/HR letter   \r\n&emsp;&emsp; e.House Rent Contract <br>\r\n&emsp; 3.Proof of Income :    \r\n&emsp;&emsp;  a.For Status (Employment Status) - Salaried (Full Time Employee, Part Time Employee, Contract Employee, Casual Employee)    \r\n&emsp;&emsp;  &emsp;&emsp;     i.Pay-slips(mandatory) \r\n&emsp;&emsp;&emsp;    &emsp;  ii.Salary Account statement ( optional)    \r\n&emsp;&emsp; b.For Status(Employment Status) - Non-Salaried (Self-Employed, Retired,\r\n&emsp;&emsp;&emsp;Unemployed, Trainee)    \r\n&emsp;&emsp;&emsp;  &emsp;   i.Tax Return Statements(mandatory) \r\n&emsp;&emsp;&emsp;&emsp;   ii.Account Statements ( optional) <br>\r\n&emsp; 4.Supporting financial documents :    \r\n&emsp;&emsp; a.Bank statements    \r\n&emsp;&emsp; b.Credit card statement    \r\n&emsp;&emsp; c.Proof of deposit    \r\n&emsp;&emsp; d.Proof of Assets   \r\n&emsp;&emsp; e.Car finance agreement   \r\n&emsp;&emsp; f.Loan statements held with third parties <br>\r\n&emsp; 5.Product Document: Bridge Loan : (Add below documents if available) (Optional) \r\n&emsp;&emsp;  a.Mortgage Loan Outstanding Statement  \r\n&emsp;&emsp;  b.Consent for Second Charge    \r\n&emsp;&emsp;  c.Additional Mortgage Document    \r\n&emsp;&emsp;  d.Existing loan - Repayment Schedule <br>\r\n&emsp; 6.Property Document : (Add below documents if available) (Optional) \r\n&emsp;&emsp;    a.Sale Agreement    \r\n&emsp;&emsp;    b.Sale Deed    \r\n&emsp;&emsp;    c.Parent Document \r\n&emsp;&emsp;    d.Plan Approval/Layout Approval    \r\n&emsp;&emsp; e.Property Tax Receipt    \r\n&emsp;&emsp;   f.Electricity, Water and Drainage Certificate/Receipt', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('eb1c78c2-af07-4d4-b7db-bcd5febe184', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'ADDITIONAL_QUESTIONS_SECTION_BRIDGE_LOAN', 'Configuration for Additional Questions in Bridge loan', '{\"bridgeLoanConfig\":{\"Dropdown\":{\"question\":\"What is the purpose of this Bridge loan?\",\"answers\":[{\"ans1\":\"Fund purchase of new residential property \",\"ans2\":\"Renovation of new residential property\",\"ans3\":\"Renovation of existing property\",\"ans4\":\"Others\"}]},\"Radio\":{\"question\":\"Is the mortgage application for your new residential property held with this bank?\",\"Options\":[\"Yes\",\"No\"]},\"Note\":\"Please login with the Existing credentials to connect bridge loan with Existing Loan\",\"enableBridgeLoan\":\"true\",\"isBridgeLoan\":true,\"productID\":\"BRIDGE.LOAN\"}}', 'CLIENT', '1');

INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('69b5dc53-3754-41eb-bda7-cc02d2e40544567', 'NUO_CONFIG_BUNDLE','PREFERENCE','BRIDGE_LOAN_PRODUCT_CONFIG', 'Configuration for Bridge loan Product details','{\"DefaultProduct\":{\"ProductLineId\":\"PL222830PUDL\",\"ProductId\": \"PR22335ORQFR\",\"ProductRef\": \"BRIDGE.LOAN\",\"ProductLineRef\":\"FACILITY\",\"ProductLineDisplayName\":\"Facility\",\"ProductGroupId\":\"PG22283MQTO7\",\"ProductGroupRef\":\"MORTGAGES\",\"ProductCurrencyId\":\"USD\",\"ProductGroupDisplayName\":\"Mortgage\",\"ProductName\":\"Bridge Loan\",\"ProductDescription\":{\"description\":\"Fast and flexible residential finance to help you bridge the gap\",\"detailedDesc\":\"A bridge loan is a short-term loan used to bridge the gap \\\"in funding a new mortgage loan or use the funds for home renovation or home improvement.\\\"\",\"notes\":\"Bridge loans are fast to arrange.|+|Bridge loans have flexible lending criteria.|+|Can be arranged as second charge.\",\"termsConditions\":\"\",\"disclosure\":\"\",\"extensionData\":{}}}}', 'CLIENT', 1);

UPDATE `configurations` SET `config_value` = 'false' WHERE (`configuration_id` = '126');
UPDATE `configurations` SET `config_value` = 'false' WHERE (`configuration_id` = 'SME_18');

UPDATE `configurations` SET `config_value` = 'CREDIT.CARDS,PERSONAL.LOANS,OVERDRAFT.ACCOUNTS,MORTGAGES,MORTGAGE.FACILITIES,BRIDGE' WHERE (`configuration_id` = '20c01647-2d15-4e77-9a8c-0f75bbeb065b' AND `config_key`='INCOME_EMPLOYMENT_REQUIRED');

UPDATE `configurations` SET `config_value`='[CREDIT.CARDS,OVERDRAFT.ACCOUNTS,PERSONAL.LOANS,MORTGAGES,MORTGAGE.FACILITIES,BRIDGE]' WHERE `configuration_id`='fab6e31f-052e-451e-83c5-b2d2dd9d92c9';

UPDATE `configurations` SET `config_value` = '{\"bridgeLoanConfig\":{\"Dropdown\":{\"question\":\"What is the purpose of this Bridge loan?\",\"answers\":[{\"ans1\":\"Fund purchase of new residential property \",\"ans2\":\"Renovation of new residential property\",\"ans3\":\"Renovation of existing property\",\"ans4\":\"Others\"}]},\"Radio\":{\"question\":\"Is the mortgage application for your new residential property held with this bank?\",\"Options\":[\"Yes\",\"No\"]},\"Note\":\"Please login with the Existing credentials to connect bridge loan with Existing Loan\",\"enableBridgeLoan\":\"true\",\"isBridgeLoan\":true,\"productID\":\"BRIDGE.LOAN\",\"interestRate\":\"5\"}}' WHERE (`configuration_id` = 'eb1c78c2-af07-4d4-b7db-bcd5febe184');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('390', 'NUO_CONFIG_BUNDLE', 'PREFERENCE', 'COAPPLICANT_OFFER_CONSENT_NOTIFY_CONFIG', 'Config to set recipients and notification type for the notification received by coApplicant after main applicant accepts offer.', '{\"notifyRecipients\" : \"CO_APPLICANT\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');
INSERT IGNORE INTO `configurations` (`configuration_id`, `bundle_id`, `config_type`, `config_key`, `description`, `config_value`, `target`, `isPreLoginConfiguration`) VALUES ('391', 'NUO_CONFIG_SME_BUNDLE', 'PREFERENCE', 'COAPPLICANT_OFFER_CONSENT_NOTIFY_CONFIG_SME', 'Config to set recipients and notification type for the notification received by coApplicant after main applicant accepts offer.', '{\"notifyRecipients\" : \"CO_APPLICANT\",\"notificationType\" : \"EMAIL\"}', 'CLIENT', '1');

UPDATE `configurations` SET `config_value` = '&emsp; 1.Proof of Identity\r\n&emsp;&emsp; a.Tax ID(mandatory)\r\n&emsp;&emsp; b.The ID which is entered under ID section to be pre populated\r\n(Any one document from below is Mandatory)\r\n&emsp;&emsp;&emsp;&emsp;  i. Driving License\r\n&emsp;&emsp;&emsp; &emsp; ii.Passport\r\n&emsp;&emsp;&emsp;&emsp; iii.Employee ID\r\n&emsp;&emsp;&emsp;&emsp; iv.Photo ID card issued by Local Government  <br>\r\n&emsp;2.Proof of Address : (Any one document from below is Mandatory)   \r\n&emsp;&emsp; a.Driving License    \r\n&emsp;&emsp; b.Passport    \r\n&emsp;&emsp; c.Utility Bills    \r\n&emsp;&emsp; d.Employer/HR letter   \r\n&emsp;&emsp; e.House Rent Contract <br>\r\n&emsp; 3.Proof of Income :    \r\n&emsp;&emsp;  a.For Status (Employment Status) - Salaried (Full Time Employee, Part Time Employee, Contract Employee, Casual Employee)    \r\n&emsp;&emsp;  &emsp;&emsp;     i.Pay-slips(mandatory) \r\n&emsp;&emsp;&emsp;    &emsp;  ii.Salary Account statement ( optional)    \r\n&emsp;&emsp; b.For Status(Employment Status) - Non-Salaried (Self-Employed, Retired,\r\n&emsp;&emsp;&emsp;Unemployed, Trainee)    \r\n&emsp;&emsp;&emsp;  &emsp;   i.Tax Return Statements(mandatory) \r\n&emsp;&emsp;&emsp;&emsp;   ii.Account Statements ( optional) <br>\r\n&emsp; 4.Supporting financial documents :    \r\n&emsp;&emsp; a.Bank statements    \r\n&emsp;&emsp; b.Credit card statement    \r\n&emsp;&emsp; c.Proof of deposit    \r\n&emsp;&emsp; d.Proof of Assets   \r\n&emsp;&emsp; e.Car finance agreement   \r\n&emsp;&emsp; f.Loan statements held with third parties <br>\r\n&emsp; 5.Product Document: Bridge Loan : (Add below documents if available) (Optional) \r\n&emsp;&emsp;  a.Mortgage Loan Outstanding Statement  \r\n&emsp;&emsp;  b.Consent for Second Charge    \r\n&emsp;&emsp;  c.Additional Mortgage Document    \r\n&emsp;&emsp;  d.Existing loan - Repayment Schedule <br>\r\n&emsp; 6.Property Document : (Add below documents if available) (Optional) \r\n&emsp;&emsp;    a.Sale Agreement    \r\n&emsp;&emsp;    b.Sale Deed    \r\n&emsp;&emsp;    c.Parent Document \r\n&emsp;&emsp;    d.Plan Approval/Layout Approval    \r\n&emsp;&emsp;    e.Property Tax Receipt    \r\n&emsp;&emsp;    f.Electricity, Water and Drainage Certificate/Receipt' WHERE (`configuration_id` = '375');