#Anchor Funding Request for SRMS
AnchorFundingRequestType = FundingRequest
AnchorFundingRequestSubType = AnchorFundingRequest

#Anchor Funding Request for DBXDB
AnchorFundingRequestModule = AnchorFundingRequest

#Anchor Funding Invoice for SRMS
AnchorInvoiceType = InvoiceUpload
AnchorInvoiceSubType = AnchorInvoiceUpload

#Anchor Funding Invoice for DBXDB
AnchorInvoiceModule = AnchorInvoiceUpload

#Counterparty Funding Invoice for SRMS
CounterPartyInvoiceType = InvoiceUpload
CounterPartyInvoiceSubType = CounterPartyInvoiceUpload

#Counterparty Funding Invoice for DBXDB
CounterPartyInvoiceModule = CounterPartyInvoiceUpload

#Payment Allocation Module for DBXDB
PaymentAllocationModule = SCF_PAYMENT_ALLOCATIONS