INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_17', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'GLOBAL_SEARCH_INFO_TEXT', N'This property is used to fetch the global search info message on hovering of the search icon', N'You can search an application via: Request ID, Facility/Product ID, Application No. or Name. All searches are case sensitive.\n\nFor Individual Party- Name Search supported by “Last Name” only \nFor Non-Individual Party (Business)- Name Search supported by “Full Company Name”', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_20', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'CURRENCY_CODE', N'Currencies support configuration', N'USD', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

UPDATE [${dbxschemaname}].[configurations] SET config_value = 'You can search an application via: Request ID, Facility/Product ID, Application No. or Name. All searches are case sensitive.'+ CHAR(10) + CHAR(10) + 'For Individual Party- Name Search supported by “Last Name” only' + CHAR(10) + 'For Non-Individual Party (Business)- Name Search supported by “Full Company Name”' WHERE (configuration_id = 'IA_17');

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'gd23fec2-4ce4-545f-5416-g28036bdd15h', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_CUSTOMER_STATUS', N'Retail Customer status after verification', N'ACTIVE', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'hd23fec2-5ce7-445g-4417-f28036bdd15s', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_CUSTOMER_STATUS', N'SME Customer status after verification', N'ACTIVE', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_23', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETENTION_PERIOD_WITHDRAWN_APPLICATIONS', N'Config value to set retention period for withdrawn applications', N'20', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_24', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETENTION_PERIOD_REJECTED_APPLICATIONS', N'Config value to set retention period for rejected applications', N'30', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

