<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.temenos.infinity</groupId>
    <artifactId>tradesupplyfinance-services</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.kony.dbp</groupId>
            <artifactId>DBPFramework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.temenos.infinity</groupId>
            <artifactId>infinity-api-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>
        <dependency>
			<groupId>com.temenos.technology</groupId>
			<artifactId>TemnLogger</artifactId>
		</dependency>
		<dependency>
			<groupId>com.temenos.technology</groupId>
			<artifactId>TemnMonitorLib</artifactId>
			<type>pom</type>
		</dependency>
        <dependency>
            <groupId>com.kony.dbp</groupId>
            <artifactId>dbp-productservices</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.kony.dbp</groupId>
            <artifactId>dbp-ObjectServices</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-inline</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>2.17.1</version>
		</dependency>
    </dependencies>

    <name>tradesupplyfinance-services</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>11</java.version>
    </properties>

    <parent>
        <artifactId>dbp-localservicesaggregator</artifactId>
        <groupId>com.kony.dbp</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <build>
        <finalName>tradesupplyfinance-services</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
					 <skipTests>true</skipTests>
                    <systemPropertyVariables>
                        <jacoco-agent.destfile>
							${project.build.directory}/coverage.exec</jacoco-agent.destfile>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
			
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>mBaaS</id>
            <name>mBaaS releases</name>
            <url>https://quantum-maven.temenosgroup.com/content/repositories/mBaaS</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>
</project>