INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID232');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID370');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID370');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID370');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID370');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID183');
DELETE FROM `rolepermission` WHERE (Role_id = "RID_SME_RM" and Permission_id = "PID414");
DELETE FROM `rolepermission` WHERE (Role_id = "RID_SME_RM" and Permission_id = "PID415");
DELETE FROM `rolepermission` WHERE (Role_id = "RID_SME_RM" and Permission_id = "PID416");
DELETE FROM `rolepermission` WHERE (Role_id = "RID_SME_OPS" and Permission_id = "PID414");
DELETE FROM `rolepermission` WHERE (Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID234");
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID233');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID238');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID239');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID240');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID241');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID362');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID300');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID301');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID302');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID303');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID344');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID345');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID346');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID347');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID136');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID137');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID138');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID139');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID154');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID155');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID156');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID157');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID167');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID168');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID169');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID170');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID180');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID189');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID190');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID191');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID192');
DELETE FROM rolepermission WHERE Role_id = "RID_SME_UW" and Permission_id = "PID414";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_UW" and Permission_id = "PID415";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_UW" and Permission_id = "PID416";
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID233');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID234');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_UW', 'PID233');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_UW', 'PID234');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_OPS', 'PID233');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_OPS', 'PID234');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID362');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_UW', 'PID362');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_OPS', 'PID362');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID143');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID251');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID255');
DELETE FROM rolepermission WHERE Role_id = "RID_SME_UW" and Permission_id = "PID417";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID414";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID415";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID416";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID417";
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID371');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID386');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_RM', 'PID333');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_UW', 'PID333');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_OPS', 'PID256');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_OPS', 'PID333');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_SUPERVISOR', 'PID371');
INSERT INTO rolepermission (Role_id, Permission_id) VALUES ('RID_SME_SUPERVISOR', 'PID333');

DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailOps') and (`Permission_id` = 'PID414');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID414');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID414');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID414');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID415');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID415');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID415');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID416');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID416');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID416');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID417');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID255');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID251');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID143');
INSERT INTO `permission` (`id`, `Type_id`, `Status_id`, `Name`, `Description`, `isComposite`, `PermissionValue`) VALUES ('PID426', 'PER_TYPE_BORROWER_FEE', 'SID_ACTIVE', 'FacilityOverviewViewBorrowerFee', 'Permission to view borrower fee in Facility Overview', '0', 'TRUE');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID426');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID426');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID426');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID426');
INSERT INTO `permission` (`id`, `Type_id`, `Status_id`, `Name`, `Description`, `isComposite`, `PermissionValue`) VALUES ('PID427', 'PER_TYPE_FACILITY', 'SID_ACTIVE', 'RequestOverviewAddFacility', 'Permission to add facility in Request Overview', '0', 'TRUE');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID427');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID427');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID427');

INSERT INTO `role` (`id`, `Type_id`, `Status_id`, `Parent_id`, `Name`, `Description`, `createdby`, `softdeleteflag`) VALUES ('RID_SME_RM_MANAGER', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME RM Manager', 'This role is for SME RM Manager', 'Kony User', '0');
INSERT INTO `role` (`id`, `Type_id`, `Status_id`, `Parent_id`, `Name`, `Description`, `createdby`,  `softdeleteflag`) VALUES ('RID_SME_OPERATIONS_MANAGER', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME Operations Manager', 'This role is for Operations Manager', 'Kony User', '0');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`, `createdby`, `softdeleteflag`) VALUES ('RID_SME_RM_MANAGER', 'PID01', 'Kony User', '0');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`, `createdby`, `softdeleteflag`) VALUES ('RID_SME_OPERATIONS_MANAGER', 'PID01', 'Kony User', '0');
INSERT INTO `role` (`id`, `Type_id`, `Status_id`, `Parent_id`, `Name`, `Description`, `createdby`, `softdeleteflag`) VALUES ('RID_SME_IT_ADMINISTRATOR', 'ROLE_TYPE_1', 'SID_ACTIVE', 'RID_SUPERADMIN', 'SME IT Administrator', 'This role is for SME IT Administrator', 'Kony User', '0');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`, `createdby`, `softdeleteflag`) VALUES ('RID_SME_IT_ADMINISTRATOR', 'PID01', 'Kony User',  '0');
INSERT INTO `permission` (`id`,`Type_id`,`Status_id`,`Name`,`Description`,`isComposite`,`PermissionValue`) VALUES ('PID423','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewAddExternalService','Permission to add services in Request Overview','0','TRUE');
INSERT INTO `permission` (`id`,`Type_id`,`Status_id`,`Name`,`Description`,`isComposite`,`PermissionValue`) VALUES ('PID424','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewUpdateExternalService','Permission to update services in Request Overview','0','TRUE');
INSERT INTO `permission` (`id`,`Type_id`,`Status_id`,`Name`,`Description`,`isComposite`,`PermissionValue`) VALUES ('PID425','PER_TYPE_INTEGRATION','SID_ACTIVE','RequestOverviewDeleteExternalService','Permission to delete services in Request Overview','0','TRUE');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID425');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SUPERVISOR', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SUPERVISOR', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SUPERVISOR', 'PID425');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID425');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID425');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID425');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID183');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID423');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID424');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID425');



INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_OPERATIONS', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_OPERATIONS', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_OPERATIONS', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID148');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID260');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID264');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID265');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID149');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID261');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID265');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailOps') and (`Permission_id` = 'PID270');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailOps') and (`Permission_id` = 'PID271');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailOps') and (`Permission_id` = 'PID272');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailOps') and (`Permission_id` = 'PID273');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID270');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID271');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID272');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailRM') and (`Permission_id` = 'PID273');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID270');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID271');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID272');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailSupervisor') and (`Permission_id` = 'PID273');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID270');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID271');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID272');
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_RetailUW') and (`Permission_id` = 'PID273');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SECRETARY', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RELATIONSHIP_MANAGER', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_UNDERWRITER', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SUPERVISOR', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_OPERATIONS', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_UW', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_RM', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_OPS', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_SME_SUPERVISOR', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailRM', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailUW', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailOps', 'PID249');
INSERT INTO `rolepermission` (`Role_id`, `Permission_id`) VALUES ('RID_RetailSupervisor', 'PID249');
DELETE FROM rolepermission WHERE Role_id = "RID_SME_OPS" and Permission_id = "PID233";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_OPS" and Permission_id = "PID362";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID136";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID137";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID138";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID139";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID238";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID239";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID240";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID241";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID154";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID155";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID156";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID157";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID274";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID275";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID276";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID277";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID189";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID190";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID191";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID192";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID344";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID345";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID346";
DELETE FROM rolepermission WHERE Role_id = "RID_SME_SUPERVISOR" and Permission_id = "PID347";
DELETE FROM `rolepermission` WHERE (`Role_id` = 'RID_OPERATIONS') and (`Permission_id` = 'PID378');