INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('93', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'DISPUTE_DURATION', 'Duration for which dispute transactions are maintained in days', '90', 'CLIENT', '0');
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('94', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'DISPUTE_REASON_CONFIG', 'Error scenarios for dispute transaction', '{\"disputeTransactionErrors\":[{\"id\": \"disputeReason1\",\"value\": \"I dont recognize this transaction\"},{\"id\": \"disputeReason2\",\"value\": \"Goods and services not received\"},{\"id\": \"disputeReason3\",\"value\": \"Billing error\"},{\"id\": \"disputeReason4\",\"value\": \"Duplicate transaction\"},{\"id\": \"disputeReason5\",\"value\": \"Recurring debit which was cancelled\"}]}', 'CLIENT', '0');
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('95', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'DISPUTE_TRANSACTION_CONFIG', 'Configure dispute transfer scenarios', '{\"disputeTransferConfig\":[{\"id\" : \"1\",\"description\" : \"both\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"2\",\"description\" : \"debit\",\"isDisputeAllowed\" : \"true\"}\",{\"id\" : \"3\",\"description\" : \"credit\",\"isDisputeAllowed\" : \"true\"}]}', 'CLIENT', '0');
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('92', 'DBP_CONFIG_BUNDLE', 'PREFERENCE', 'DISPUTE_TRANSACTION_TYPE_CONFIG', 'Configure dispute transaction scenarios', '{\"disputeScenariosConfig\":[{\"id\" : \"1\",\"description\" : \"InternalTransfer\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"2\",\"description\" : \"BillPay\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"3\",\"description\" : \"ExternalTransfer\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"4\",\"description\" : \"Deposit\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"5\",\"description\" : \"P2P\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"6\",\"description\" : \"Cardless\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"7\",\"description\" : \"CheckWithdrawal\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"8\",\"description\" : \"Withdrawal\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"9\",\"description\" : \"Interest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"10\",\"description\" : \"Request\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"11\",\"description\" : \"Loan\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"12\",\"description\" : \"ReceivedP2P\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"13\",\"description\" : \"ReceivedRequest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"14\",\"description\" : \"StopCheckPaymentRequest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"15\",\"description\" : \"Wire\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"16\",\"description\" : \"Credit\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"17\",\"description\" : \"InternetTransaction\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"18\",\"description\" : \"POS\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"19\",\"description\" : \"CardPayment\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"20\",\"description\" : \"Tax\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"21\",\"description\" : \"Fee\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"22\",\"description\" : \"SwiftPayment\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"23\",\"description\" : \"Draft\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"24\",\"description\" : \"Transfers\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"25\",\"description\" : \"Others\",\"isDisputeAllowed\" : \"true\"}]}', 'CLIENT', '0');

INSERT INTO [${dbxschemaname}].[permission] ([id], [Type_id], [Status_id], [Name], [Description], [isComposite], [PermissionValue]) VALUES ('PID524','PER_TYPE_REQUEST_OVERVIEW','SID_ACTIVE','RequestOverviewViewRiskAssessment','To view FCM results in Request Overview','0','TRUE');
INSERT INTO [${dbxschemaname}].[permission] ([id], [Type_id], [Status_id], [Name], [Description], [isComposite], [PermissionValue]) VALUES ('PID525','PER_TYPE_ENTITY_OVERVIEW','SID_ACTIVE','EntityOverviewViewFCMResults','To view FCM results in Entity Overview','0','TRUE');

INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_OPS', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_OPS_SUPERVISIOR', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_RM', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_RM_SUPERVISIOR', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SYSTEM_ADMIN', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID524');

INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_OPS', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_OPS_SUPERVISIOR', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_RM', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SMEONBOARDING_RM_SUPERVISIOR', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_SYSTEM_ADMIN', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_SME_UW', N'PID525');

UPDATE [${dbxschemaname}].[application] SET [deploymentGeography] = 'EUROPE' where [id] = '2'; 