INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','accountsstatementfiles','where userId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','achfile','where createdby = ?','achFile_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','achfilerecord','where achFileId in (select achFile_id from dbxdb.achfile where createdby = ? )','achFileRecordId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','achfilesubrecord','where achFileRecordId in (select achFileRecordId from dbxdb.achfilerecord where achFileId in (select achFile_id from dbxdb.achfile where createdby = ? ))','achFileSubRecordId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','achtransaction','where createdby = ?','transaction_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','achtransactionrecord','where transaction_id in (select transaction_id from dbxdb.achtransaction where createdby = ? )','transactionRecord_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','address','where id in (select Address_id from dbxdb.customeraddress where Customer_id = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','admincustomeractivity','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','alerthistory','where Customer_Id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','approvalmatrix','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','approvalmode','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','archivedalerthistory','where Customer_Id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','archivedauditactivity','where Customer_Id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','archivedmoneymovementlog','where Customer_id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','auditactivity','where Customer_Id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','backendidentifier','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bbactedrequest','where createdby = ?','approvalId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bbrequest','where createdby = ?','requestId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bbtemplate','where createdby = ?','templateId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bbtemplaterecord','where template_id in (select templateId from dbxdb.bbtemplate where createdby = ? )','templateRecord_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','billpaypayee','where cif in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymentfiles','where createdby = ?','fileId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymentrecord','where createdby = ?','recordId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymentrequest','where createdby = ?','paymentrequestId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymentrequestpos','where createdby = ?','paymentrequestPOId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymentsubrecord','where createdby = ?','paymentOrderId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymenttemplate','where createdby = ?','templateId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','bulkpaymenttemplatepos','where createdby = ?','paymentOrderId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractaccounts','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractactionlimit','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractcommunication','where contractId in (select contractId from dbxdb.contractcustomers where customerId = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractcorecustomers','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractcustomers','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractcustomrole','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','contractfeatures','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','coremembership','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','credentialchecker','where UserName in (select UserName from dbxdb.customer where id = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','csrassistgrant','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','custcompletedcampaign','where customer_id = ?','customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customer','where id  = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeraccounts','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeraction','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','customeractivity','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeraddress','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeralertchannel','where customerId = ?','customerId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeralertfrequency','where customerId = ?','customerId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customeralertswitch','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerapprovalmatrix','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerbusinesstype','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customercommunication','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerdevice','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customergroup','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerimage','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerlimitgrouplimits','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customernote','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customernotification','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerpreference','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customerrequest','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customersecurityquestions','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customersignatorygroup','where customerId = ?','customerSignatoryGroupId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customertermsandconditions','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customroleaccounts','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','customroleactionlimits','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','dbxcustomeralertentitlement','where Customer_id = ?','Customer_id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','deviceregistration','where User_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','excludedcontractaccounts','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','excludedcustomeraccounts','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','externalaccount','where User_id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','favouriteinstruments','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','feedback','where user_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','feedbackstatus','where customerID = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','interbankfundtransfers','where fromAccountNumber in (select Account_id from dbxdb.customeraccounts where Customer_id = ? )','transactionId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','interbankpayee','where cif in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','internationalfundtransfers','where fromAccountNumber in (select Account_id from dbxdb.customeraccounts where Customer_id = ? )','transactionId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','internationalpayee','where cif in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','intrabankpayee','where cif in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','intrabanktransfers','where fromAccountNumber in (select Account_id from dbxdb.customeraccounts where Customer_id = ? )','transactionId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','location','where Address_id in (select Address_id from dbxdb.customeraddress where Customer_id = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','manageapprovalmatrix','where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','contractId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','membership','where addressId in (select Address_id from dbxdb.customeraddress where Customer_id = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','mfaservice','where User_id = ?','serviceKey');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','moneymovementlog','where Customer_id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','notificationcardinfo','where Customer_id = ? ','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','OTP','where User_id = ?','securityKey');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','otpcount','where User_id = ?','key');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','ownaccounttransfers','where fromAccountNumber in (select Account_id from dbxdb.customeraccounts where Customer_id = ? )','transactionId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','p2ppayee','where cif in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','p2pregistration','where user_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','passwordhistory','where Customer_id = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','payee','where User_Id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','paymentfiles','where userId = ?','paymentFileID');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','recentcurrencies','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','requestmessage','where modifiedby in (select UserName from dbxdb.customer where id = ? )','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','signatorygroupmatrix','where approvalMatrixId in (select id from dbxdb.approvalmatrix where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24''))','signatoryGroupMatrixId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','signatorygrouprequestmatrix','where approvalMatrixId in (select id from dbxdb.approvalmatrix where coreCustomerId in (select BackendId from dbxdb.backendidentifier where Customer_id = ? AND BackendType = ''T24''))','signatoryGroupRequestMatrixId');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','suspendedcustomers','where customerId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','transaction','where Customer_id = ?','Id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxlogs','transactionlog','where customerId = ? ','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','transactionlogs','where userId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','travelnotification','where createdby = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','wealthuserpreferences','where userId = ?','id');
INSERT INTO `queryconfig` (`dbname`,`tablename`,`querystring`,`primaryKey`) VALUES('dbxdb','wiretransferspayee','where contractId in (select contractId from dbxdb.contractcustomers where customerId = ? )','id');

INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('61b8365c-7fc1-4685-a1f3-4c8b25332413', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5a11f3e3-3022-478f-827c-0363fbb952a7', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5dbc4a4d-d722-4721-b0de-d285e3ca7e57', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('57300402-803b-4b2f-99af-32c584b5dd86', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e6ef4a43-60c5-42ca-8689-b76a0a2004ea', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4f933e77-00d3-42a1-8503-7ec6ce832593', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de482', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de483', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ddf80d75-fa42-4bbb-8029-a96018296826', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('33c91eea-3a05-4a1c-a6ff-982bf1ee691c', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dfe013ee-50f5-4ca2-afd1-24d0937ab410', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e30-44995d88584e', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e31-44995d88584e', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e2-c31578349519', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e3-c31578349514', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');

INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c5f5d482-595c-41d9-be4b-0bfe0e263929', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c9a3348d-437b-40be-a683-841d7ed07f81', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a5faf805-851f-436e-ad7b-fa5121610321', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('7f76ca3f-3113-46c3-8cba-84ddbe141c5d', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283302', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283303', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e9931001-f979-441b-ac3f-638c7448637f', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c4d54eba-7cb5-45d2-aa35-091b4efb029f', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('d0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db1', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db2', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('260e3597-5e15-49d2-892b-4b97defea5ae', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('260e3597-5e15-49d2-892b-4b97defea5af', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');

INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ffdbc23c-cb88-423f-8d2c-b6f641636f44', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c7f17939-78e2-418f-8d33-0bbd07c70446', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1337d8a6-e8c1-4c53-b6aa-808698b07584', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('354743d9-bd17-4635-b057-6a94166eabbb', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', 'TYPE_ID_RETAILONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1c219e1e-c28c-4c54-8b25-47175195f161', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('474c5314-11d2-4e91-a17b-e6053d5e366f', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');
INSERT INTO `userlob` (`userId`, `lobId`, `softdeleteflag`, `companyLegalUnit`) VALUES ('796a50eb-e7b5-4e11-b21b-fc8adf3725ec', 'TYPE_ID_SMEONBOARDING', '0', 'ALL');

INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('61b8365c-7fc1-4685-a1f3-4c8b25332413', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5a11f3e3-3022-478f-827c-0363fbb952a7', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5dbc4a4d-d722-4721-b0de-d285e3ca7e57', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('57300402-803b-4b2f-99af-32c584b5dd86', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e6ef4a43-60c5-42ca-8689-b76a0a2004ea', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4f933e77-00d3-42a1-8503-7ec6ce832593', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de482', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de483', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ddf80d75-fa42-4bbb-8029-a96018296826', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('33c91eea-3a05-4a1c-a6ff-982bf1ee691c', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dfe013ee-50f5-4ca2-afd1-24d0937ab410', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e30-44995d88584e', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e31-44995d88584e', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e2-c31578349519', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e3-c31578349514', 'retailsuperuser', '0', 'ALL');

INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c5f5d482-595c-41d9-be4b-0bfe0e263929', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c9a3348d-437b-40be-a683-841d7ed07f81', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a5faf805-851f-436e-ad7b-fa5121610321', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('7f76ca3f-3113-46c3-8cba-84ddbe141c5d', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283302', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283303', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e9931001-f979-441b-ac3f-638c7448637f', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c4d54eba-7cb5-45d2-aa35-091b4efb029f', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('d0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db1', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db2', 'smesuperusers', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('260e3597-5e15-49d2-892b-4b97defea5ae', 'smesuperusers', '0', 'ALL');


INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ffdbc23c-cb88-423f-8d2c-b6f641636f44', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c7f17939-78e2-418f-8d33-0bbd07c70446', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1337d8a6-e8c1-4c53-b6aa-808698b07584', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('354743d9-bd17-4635-b057-6a94166eabbb', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', 'retailsuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1c219e1e-c28c-4c54-8b25-47175195f161', 'smesuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('474c5314-11d2-4e91-a17b-e6053d5e366f', 'smesuperuser', '0', 'ALL');
INSERT INTO `internalusermanager` (`userId`, `manager`, `softdeleteflag`, `companyLegalUnit`) VALUES ('796a50eb-e7b5-4e11-b21b-fc8adf3725ec', 'smesuperusers', '0', 'ALL');


INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('61b8365c-7fc1-4685-a1f3-4c8b25332413', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5a11f3e3-3022-478f-827c-0363fbb952a7', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5dbc4a4d-d722-4721-b0de-d285e3ca7e57', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('57300402-803b-4b2f-99af-32c584b5dd86', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e6ef4a43-60c5-42ca-8689-b76a0a2004ea', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4f933e77-00d3-42a1-8503-7ec6ce832593', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de482', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de483', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ddf80d75-fa42-4bbb-8029-a96018296826', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('33c91eea-3a05-4a1c-a6ff-982bf1ee691c', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dfe013ee-50f5-4ca2-afd1-24d0937ab410', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e30-44995d88584e', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e31-44995d88584e', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e2-c31578349519', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e3-c31578349514', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');

INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c5f5d482-595c-41d9-be4b-0bfe0e263929', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c9a3348d-437b-40be-a683-841d7ed07f81', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a5faf805-851f-436e-ad7b-fa5121610321', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('7f76ca3f-3113-46c3-8cba-84ddbe141c5d', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283302', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283303', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e9931001-f979-441b-ac3f-638c7448637f', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c4d54eba-7cb5-45d2-aa35-091b4efb029f', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('d0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db1', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db2', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('260e3597-5e15-49d2-892b-4b97defea5ae', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');


INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ffdbc23c-cb88-423f-8d2c-b6f641636f44', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c7f17939-78e2-418f-8d33-0bbd07c70446', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1337d8a6-e8c1-4c53-b6aa-808698b07584', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('354743d9-bd17-4635-b057-6a94166eabbb', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1c219e1e-c28c-4c54-8b25-47175195f161', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('474c5314-11d2-4e91-a17b-e6053d5e366f', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');
INSERT INTO `useraddress` (`User_id`, `Address_id`,`Type_id`, `softdeleteflag`, `companyLegalUnit`) VALUES ('796a50eb-e7b5-4e11-b21b-fc8adf3725ec', 'DMSADDR1', 'ADR_TYPE_WORK','0', 'ALL');

INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('61b8365c-7fc1-4685-a1f3-4c8b25332413', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5a11f3e3-3022-478f-827c-0363fbb952a7', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('5dbc4a4d-d722-4721-b0de-d285e3ca7e57', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('57300402-803b-4b2f-99af-32c584b5dd86', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e6ef4a43-60c5-42ca-8689-b76a0a2004ea', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4f933e77-00d3-42a1-8503-7ec6ce832593', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de482', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a884f15c-f347-4138-9cda-d20cc35de483', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ddf80d75-fa42-4bbb-8029-a96018296826', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('33c91eea-3a05-4a1c-a6ff-982bf1ee691c', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('dfe013ee-50f5-4ca2-afd1-24d0937ab410', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e30-44995d88584e', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('6829d098-35d3-427c-9e31-44995d88584e', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e2-c31578349519', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('4edab350-378f-4a55-81e3-c31578349514', 'INTERNAL', '0', 'ALL');

INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c5f5d482-595c-41d9-be4b-0bfe0e263929', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c9a3348d-437b-40be-a683-841d7ed07f81', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a5faf805-851f-436e-ad7b-fa5121610321', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('7f76ca3f-3113-46c3-8cba-84ddbe141c5d', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283302', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('73877665-5a54-4993-94c2-b0d759283303', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('e9931001-f979-441b-ac3f-638c7448637f', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c4d54eba-7cb5-45d2-aa35-091b4efb029f', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('d0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db1', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('68315eb0-24fe-409b-a517-a4ddf1b11db2', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('260e3597-5e15-49d2-892b-4b97defea5ae', 'INTERNAL', '0', 'ALL');

INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('ffdbc23c-cb88-423f-8d2c-b6f641636f44', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('c7f17939-78e2-418f-8d33-0bbd07c70446', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1337d8a6-e8c1-4c53-b6aa-808698b07584', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('354743d9-bd17-4635-b057-6a94166eabbb', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('1c219e1e-c28c-4c54-8b25-47175195f161', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('474c5314-11d2-4e91-a17b-e6053d5e366f', 'INTERNAL', '0', 'ALL');
INSERT INTO `internalusertype` (`userId`, `userType`, `softdeleteflag`, `companyLegalUnit`) VALUES ('796a50eb-e7b5-4e11-b21b-fc8adf3725ec', 'INTERNAL', '0', 'ALL');