
-- set the action levels of beneficiary management to customer level, instead of account level
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE `featureaction` SET `isAccountLevel` = 0, `actionlevelId` = 'CUSTOMERID_LEVEL' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';

ALTER TABLE `dbxdb`.`bbrequest` CHANGE COLUMN `featureActionId` `featureActionId` VARCHAR(64) NOT NULL ;
-- common feature action for approvals for each type
-- ARB-34845 Start
INSERT INTO `featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-APPROVE', 'Approve International Recepient', 'Approve creation, editing or deletion of an international-bank beneficiary', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-APPROVE', 'Self Approve International Recepient', 'Self Approve creation, editing or deletion of an international-bank beneficiary', 0, 0, null, null, null, 0, 3, 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient-International Transfer', 'International account fund transfer edit recipient', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-International Transfer', 'International account fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-International Transfer', 'International account fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');

INSERT INTO `featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-APPROVE', 'Approve Inter Bank Recepient', 'Approve creation, editing or deletion of an inter-bank beneficiary', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-APPROVE', 'Self Approve Inter Bank Recepient', 'Self Approve creation, editing or deletion of an inter-bank beneficiary', 0, 0, null, null, null, 0, 3, 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient-Domestic Transfer', 'Inter bank fund transfer edit recipient', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-Domestic Transfer', 'Inter bank fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTER_BANK_ACCOUNT_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-Domestic Transfer', 'Inter bank fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');

INSERT INTO `featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-APPROVE', 'Approve Intra Bank Recepient', 'Approve creation, editing or deletion of an intra-bank beneficiary', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-APPROVE', 'Self Approve Intra Bank Recepient', 'Self Approve creation, editing or deletion of an intra-bank beneficiary', 0, 0, null, null, null, 0, 3, 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'APPROVE', 'CUSTOMERID_LEVEL', null, 1, 'ALL');
INSERT INTO `featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-CREATE', 'Edit Recipient-Same bank Transfer', 'Intra bank fund transfer edit recipient', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-CREATE', 'Edit Recipient Linkage-Same bank Transfer', 'Intra bank fund transfer edit recipient linkage', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');
INSERT INTO `featureaction` VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTRA_BANK_FUND_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'NON_MONETARY', 'INTRA_BANK_FUND_TRANSFER-CREATE', 'Edit Recipient Optional Field-Same bank Transfer', 'Intra bank fund transfer edit recipient optional field', 0, 0, null, null, null, 0, 3, null, null, null, curdate(), curdate(), curdate(), 0, 'SID_ACTION_ACTIVE', null, 'CREATE', 'CUSTOMERID_LEVEL', null, 0, 'ALL');

INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'ALL');

INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'ALL');

INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'ALL');
INSERT INTO `featureactionroletype` (`RoleType_id`, `Action_id`, `companyLegalUnit`) VALUES ('TYPE_ID_BUSINESS', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit International Beneficiary', 'Edit International Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit International Beneficiary', 'Edit International Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit International Beneficiary', 'Edit International Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit International Beneficiary', 'Edit International Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit International Beneficiary', 'Edit International Beneficiary', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit International Beneficiary Linkage', 'Edit International Beneficiary Linkage', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit International Beneficiary Optional Fields', 'Edit International Beneficiary Optional Fields', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve International Payee', 'Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve International Payee', 'Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve International Payee', 'Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve International Payee', 'Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve International Payee', 'Approve International Payee', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve International Payee', 'Self Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve International Payee', 'Self Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve International Payee', 'Self Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve International Payee', 'Self Approve International Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve International Payee', 'Self Approve International Payee', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit Inter Bank Beneficiary', 'Edit Inter Bank Beneficiary', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit Inter Bank Beneficiary Optional Fields', 'Edit Inter Bank Beneficiary Optional Fields', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit Inter Bank Beneficiary Linkage', 'Edit Inter Bank Beneficiary Linkage', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve Inter Bank Payee', 'Approve Inter Bank Payee', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve Inter Bank Payee', 'Self Approve Inter Bank Payee', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'de-DE', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'en-GB', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'en-US', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'es-ES', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'fr-FR', 'Edit Intra Bank Beneficiary', 'Edit Intra Bank Beneficiary', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'de-DE', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-GB', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'en-US', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'es-ES', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'fr-FR', 'Edit Intra Bank Beneficiary Optional Fields', 'Edit Intra Bank Beneficiary Optional Fields', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'de-DE', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-GB', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'en-US', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'es-ES', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'fr-FR', 'Edit Intra Bank Beneficiary Linkage', 'Edit Intra Bank Beneficiary Linkage', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'de-DE', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-GB', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'en-US', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'es-ES', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'fr-FR', 'Approve Intra Bank Payee', 'Approve Intra Bank Payee', 'ALL');

INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'de-DE', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-GB', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'en-US', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'es-ES', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', 'ALL');
INSERT INTO `actiondisplaynamedescription` (`Action_id`, `Locale_id`, `displayName`, `displayDescription`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'fr-FR', 'Self Approve Intra Bank Payee', 'Self Approve Intra Bank Payee', 'ALL');

INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTRA_BANK_FUND_TRANSFER', 'Approve Intra Bank Recepient', 'Intra Bank Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient', 'Intra Bank Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient Optional Fields', 'Intra Bank Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Intra Bank Recepient Linkage', 'Intra Bank Fund Transfer', 'ALL');

INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER', 'Approve Inter Bank Recepient', 'Interbank Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient', 'Interbank Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient Optional Fields', 'Interbank Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit Inter Bank Recepient Linkage', 'Interbank Account to Account Fund Transfer', 'ALL');

INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_SELF_APPROVAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER', 'Approve International Recepient', 'International Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient', 'International Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient Optional Fields', 'International Account to Account Fund Transfer', 'ALL');
INSERT INTO `dependentactions` (`actionId`, `dependentactionId`, `featureId`, `actionName`, `featureName`, `companyLegalUnit`) VALUES ('INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE', 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT', 'INTRA_BANK_FUND_TRANSFER', 'Edit International Bank Recepient Linkage', 'International Account to Account Fund Transfer', 'ALL');

-- set the approve dependency action for the create/edit/delete feature actions of beneficiary management
UPDATE `featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE `featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE `featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_LINKAGE';
UPDATE `featureaction` SET `approveFeatureAction` = 'INTRA_BANK_FUND_TRANSFER_RECEPIENT_APPROVE' WHERE `id` = 'INTRA_BANK_FUND_TRANSFER_EDIT_RECEPIENT_OPTIONAL';

UPDATE `featureaction` SET `name` = 'Create Recipient-Same Bank Transfer' WHERE (`id` = 'INTRA_BANK_FUND_TRANSFER_CREATE_RECEPIENT');
UPDATE `featureaction` SET `name` = 'Delete Recipient-Same Bank Transfer' WHERE (`id` = 'INTRA_BANK_FUND_TRANSFER_DELETE_RECEPIENT');
UPDATE `featureaction` SET `name` = 'Create Recipient-Domestic Transfer' WHERE (`id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT');
UPDATE `featureaction` SET `name` = 'Delete Recipient-Domestic Transfer' WHERE (`id` = 'INTER_BANK_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT');
UPDATE `featureaction` SET `name` = 'Create Recipient-International Transfer' WHERE (`id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE_RECEPIENT');
UPDATE `featureaction` SET `name` = 'Delete Recipient-International Transfer' WHERE (`id` = 'INTERNATIONAL_ACCOUNT_FUND_TRANSFER_DELETE_RECEPIENT');