CREATE TABLE `sca_actions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `App_id` varchar(50) NOT NULL,
  `Action_id` varchar(50) NOT NULL,
  `Status_id` varchar(50) NOT NULL,
  `Description` varchar(300) DEFAULT NULL,
  `createdby` varchar(50) DEFAULT NULL,
  `modifiedby` varchar(50) DEFAULT NULL,
  `createdts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastmodifiedts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `synctimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `softdeleteflag` tinyint(1) NOT NULL DEFAULT '0',
  `risk_score` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_appactionmfa_status_id_idx` (`Status_id`),
  KEY `FK_appactionmfa_App_id_idx` (`App_id`),
  KEY `FK_appactionmfa_FeatureAction_id_idx` (`Action_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1868396817 DEFAULT CHARSET=utf8;

CREATE TABLE `external_feature_actions` (
  `id` text,
  `Feature_id` text,
  `App_id` text,
  `Type_id` text,
  `Rrole_id` text,
  `name` text,
  `description` text,
  `isAccountLevel` int(11) DEFAULT NULL,
  `isMFAApplicable` int(11) DEFAULT NULL,
  `MFA_id` text,
  `TermsAndConditions_id` text,
  `notes` text,
  `isPrimary` int(11) DEFAULT NULL,
  `DisplaySequence` int(11) DEFAULT NULL,
  `dependency` text,
  `createdby` text,
  `modifiedby` text,
  `createdts` text,
  `lastmodifiedts` text,
  `synctimestamp` text,
  `softdeleteflag` int(11) DEFAULT NULL,
  `status` text,
  `limitgroupId` text,
  `accesspolicyId` text,
  `actionlevelId` text,
  `approveFeatureAction` text,
  `isApprovalAction` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;