package com.kony.logservices.util;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import com.temenos.logger.Logger;
import com.temenos.logger.alert.Alert;

import com.kony.logservices.core.BaseActivity;
import com.kony.logservices.dto.AdminActivityDTO;
import com.kony.logservices.dto.AdminCustomerActivityDTO;
import com.kony.logservices.dto.AuditActivityDTO;
import com.kony.logservices.dto.CustomerActivityDTO;
import com.kony.logservices.dto.MoneyMovementLogDTO;
import com.kony.logservices.dto.TransactionActivityDTO;

/**
 * Enum used to maintain sql queries with associated constants
 * 
 * @author Venkateswara Rao Alla
 * 
 */

public enum SQLQueriesEnum {

    // admin activity
    MYSQL_ADMINACTIVITY_READ, MYSQL_ADMINACTIVITY_INSERT, MYSQL_ADMINACTIVITY_DELETE, MYSQL_ADMINACTIVITY_COUNT_READ,
    MYSQL_ADMINACTIVITY_WHERECLAUSE_USERNAME, MYSQL_ADMINACTIVITY_WHERECLAUSE_MODULENAME, MYSQL_ADMINACTIVITY_WHERECLAUSE_EVENTTS,
    MYSQL_ADMINACTIVITY_WHERECLAUSE_EVENT, MYSQL_ADMINACTIVITY_WHERECLAUSE_USERROLE, MYSQL_ADMINACTIVITY_WHERECLAUSE_STATUS,

    // customer activity
    MYSQL_CUSTOMERACTIVITY_READ, MYSQL_CUSTOMERACTIVITY_INSERT, MYSQL_CUSTOMERACTIVITY_DELETE, MYSQL_CUSTOMERACTIVITY_READ_COUNT,
    MYSQL_CUSTOMERACTIVITY_QUERY_USERNAME, MYSQL_CUSTOMERACTIVITY_QUERY_MODULENAME, MYSQL_CUSTOMERACTIVITY_QUERY_STATUS,
    MYSQL_CUSTOMERACTIVITY_QUERY_CHANNEL, MYSQL_CUSTOMERACTIVITY_QUERY_OPERATINGSYSTEM, MYSQL_CUSTOMERACTIVITY_LAST_N_SESSIONS,

    // customer activity by admin
    MYSQL_ADMINCUSTOMERACTIVITY_READ, MYSQL_ADMINCUSTOMERACTIVITY_INSERT, MYSQL_ADMINCUSTOMERACTIVITY_DELETE,
    MYSQL_ADMINCUSTOMERACTIVITY_READ_COUNT, MYSQL_ADMINCUSTOMERACTIVITY_QUERY_CUSTOMERID, MYSQL_ADMINCUSTOMERACTIVITY_QUERY_ADMINNAME,
    MYSQL_ADMINCUSTOMERACTIVITY_QUERY_ADMINROLE, MYSQL_ADMINCUSTOMERACTIVITY_QUERY_ACTIVITYTYPE,

    // transaction log
    MYSQL_TRANSACTIONLOG_READ, MYSQL_TRANSACTIONLOG_INSERT, MYSQL_TRANSACTIONLOG_DELETE, MYSQL_TRANSACTIONLOG_COUNT_READ,
    MYSQL_TRANSACTIONVALUEVOLUMETYPE_READ, MYSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATE, MYSQL_TRANSACTIONLOG_GROUPBY,
    MYSQL_TRANSACTIONLOG_WHERECLAUSE_SERVICENAME, MYSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONID, MYSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATEBETWEEN,
    MYSQL_TRANSACTIONLOG_WHERECLAUSE_AMOUNT, MYSQL_TRANSACTIONLOG_WHERECLAUSE_FROMACCOUNTTYPE,MYSQL_TRANSACTIONLOG_WHERECLAUSE_TOACCOUNTTYPE,
    MYSQL_TRANSACTIONLOG_WHERECLAUSE_STATUS, MYSQL_TRANSACTIONLOG_WHERECLAUSE_TYPE, MYSQL_TRANSACTIONLOG_WHERECLAUSE_CURRENCYCODE,
    MYSQL_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILLIKE, MYSQL_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILNOTLIKE,
    MYSQL_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILLIKE, MYSQL_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILNOTLIKE, MYSQL_TRANSACTIONLOG_ORDERBY,

    // Audit logs
    MYSQL_AUDITLOG_READ, MYSQL_AUDITLOG_ARCH_READ, MYSQL_AUDITLOG_INSERT, MYSQL_AUDITLOG_DELETE, MYSQL_AUDITLOG_COUNT_READ,
    MYSQL_AUDITLOG_SEARCH_SELECT_QUERY, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_USERNAME, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_CUSTOMERID,
    MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_FROMACCOUNTNUMBER, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_TOACCOUNTNUMBER, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_ISCSRASSIST,
    MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_EVENTTYPE, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_EVENTSUBTYPE,
    MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_AMOUNT, MYSQL_AUDITLOG_SEARCH_WHERECLAUSE_CREATEDTS, MYSQL_AUDITLOG_LAST_N_SESSIONS,

    // MoneyMovement logs
    MYSQL_MONEYMOVEMENT_READ, MYSQL_MONEYMOVEMENT_DELETE, MYSQL_MONEYMOVEMENT_INSERT,
    
    // MSSQL - STARTS
    
    // admin activity
    MSSQL_ADMINACTIVITY_READ, MSSQL_ADMINACTIVITY_INSERT, MSSQL_ADMINACTIVITY_DELETE, MSSQL_ADMINACTIVITY_COUNT_READ,
    MSSQL_ADMINACTIVITY_WHERECLAUSE_USERNAME, MSSQL_ADMINACTIVITY_WHERECLAUSE_MODULENAME, MSSQL_ADMINACTIVITY_WHERECLAUSE_EVENTTS,
    MSSQL_ADMINACTIVITY_WHERECLAUSE_EVENT, MSSQL_ADMINACTIVITY_WHERECLAUSE_USERROLE, MSSQL_ADMINACTIVITY_WHERECLAUSE_STATUS,
    
    // customer activity
    MSSQL_CUSTOMERACTIVITY_READ, MSSQL_CUSTOMERACTIVITY_INSERT, MSSQL_CUSTOMERACTIVITY_DELETE, MSSQL_CUSTOMERACTIVITY_READ_COUNT,
    MSSQL_CUSTOMERACTIVITY_QUERY_USERNAME, MSSQL_CUSTOMERACTIVITY_QUERY_MODULENAME, MSSQL_CUSTOMERACTIVITY_QUERY_STATUS,
    MSSQL_CUSTOMERACTIVITY_QUERY_CHANNEL, MSSQL_CUSTOMERACTIVITY_QUERY_OPERATINGSYSTEM, MSSQL_CUSTOMERACTIVITY_LAST_N_SESSIONS,

    // customer activity by admin
    MSSQL_ADMINCUSTOMERACTIVITY_READ, MSSQL_ADMINCUSTOMERACTIVITY_INSERT, MSSQL_ADMINCUSTOMERACTIVITY_DELETE,
    MSSQL_ADMINCUSTOMERACTIVITY_READ_COUNT, MSSQL_ADMINCUSTOMERACTIVITY_QUERY_CUSTOMERID, MSSQL_ADMINCUSTOMERACTIVITY_QUERY_ADMINNAME,
    MSSQL_ADMINCUSTOMERACTIVITY_QUERY_ADMINROLE, MSSQL_ADMINCUSTOMERACTIVITY_QUERY_ACTIVITYTYPE,

    // transaction log
    MSSQL_TRANSACTIONLOG_READ, MSSQL_TRANSACTIONLOG_INSERT, MSSQL_TRANSACTIONLOG_DELETE, MSSQL_TRANSACTIONLOG_COUNT_READ,
    MSSQL_TRANSACTIONVALUEVOLUMETYPE_READ, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATE, MSSQL_TRANSACTIONLOG_GROUPBY,
    MSSQL_TRANSACTIONLOG_WHERECLAUSE_SERVICENAME, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONID, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATEBETWEEN,
    MSSQL_TRANSACTIONLOG_WHERECLAUSE_AMOUNT, MSSQL_TRANSACTIONLOG_WHERECLAUSE_FROMACCOUNTTYPE, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TOACCOUNTTYPE,
    MSSQL_TRANSACTIONLOG_WHERECLAUSE_STATUS, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TYPE, MSSQL_TRANSACTIONLOG_WHERECLAUSE_CURRENCYCODE,
    MSSQL_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILLIKE, MSSQL_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILNOTLIKE,
    MSSQL_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILLIKE, MSSQL_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILNOTLIKE, MSSQL_TRANSACTIONLOG_ORDERBY,

    // Audit logs
    MSSQL_AUDITLOG_READ, MSSQL_AUDITLOG_ARCH_READ, MSSQL_AUDITLOG_INSERT, MSSQL_AUDITLOG_DELETE, MSSQL_AUDITLOG_COUNT_READ,
    MSSQL_AUDITLOG_SEARCH_SELECT_QUERY, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_USERNAME, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_CUSTOMERID,
    MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_FROMACCOUNTNUMBER, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_TOACCOUNTNUMBER, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_ISCSRASSIST,
    MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_EVENTTYPE, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_EVENTSUBTYPE,
    MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_AMOUNT, MSSQL_AUDITLOG_SEARCH_WHERECLAUSE_CREATEDTS, MSSQL_AUDITLOG_LAST_N_SESSIONS,

    // MoneyMovement logs
    MSSQL_MONEYMOVEMENT_READ, MSSQL_MONEYMOVEMENT_DELETE, MSSQL_MONEYMOVEMENT_INSERT,
    
    // ORACLE - STARTS
    
    // admin activity
    ORACLE_ADMINACTIVITY_READ, ORACLE_ADMINACTIVITY_INSERT, ORACLE_ADMINACTIVITY_DELETE, ORACLE_ADMINACTIVITY_COUNT_READ,
    ORACLE_ADMINACTIVITY_WHERECLAUSE_USERNAME, ORACLE_ADMINACTIVITY_WHERECLAUSE_MODULENAME, ORACLE_ADMINACTIVITY_WHERECLAUSE_EVENTTS,
    ORACLE_ADMINACTIVITY_WHERECLAUSE_EVENT, ORACLE_ADMINACTIVITY_WHERECLAUSE_USERROLE, ORACLE_ADMINACTIVITY_WHERECLAUSE_STATUS,
    
    //	customer activity
    ORACLE_CUSTOMERACTIVITY_READ, ORACLE_CUSTOMERACTIVITY_INSERT, ORACLE_CUSTOMERACTIVITY_DELETE, ORACLE_CUSTOMERACTIVITY_READ_COUNT,
    ORACLE_CUSTOMERACTIVITY_QUERY_USERNAME, ORACLE_CUSTOMERACTIVITY_QUERY_MODULENAME, ORACLE_CUSTOMERACTIVITY_QUERY_STATUS,
    ORACLE_CUSTOMERACTIVITY_QUERY_CHANNEL, ORACLE_CUSTOMERACTIVITY_QUERY_OPERATINGSYSTEM, ORACLE_CUSTOMERACTIVITY_LAST_N_SESSIONS,
    
    // customer activity by admin
    ORACLE_ADMINCUSTOMERACTIVITY_READ, ORACLE_ADMINCUSTOMERACTIVITY_INSERT, ORACLE_ADMINCUSTOMERACTIVITY_DELETE,
    ORACLE_ADMINCUSTOMERACTIVITY_READ_COUNT, ORACLE_ADMINCUSTOMERACTIVITY_QUERY_CUSTOMERID, ORACLE_ADMINCUSTOMERACTIVITY_QUERY_ADMINNAME,
    ORACLE_ADMINCUSTOMERACTIVITY_QUERY_ADMINROLE, ORACLE_ADMINCUSTOMERACTIVITY_QUERY_ACTIVITYTYPE,

    // transaction log
    ORACLE_TRANSACTIONLOG_READ, ORACLE_TRANSACTIONLOG_INSERT, ORACLE_TRANSACTIONLOG_DELETE, ORACLE_TRANSACTIONLOG_COUNT_READ,
    ORACLE_TRANSACTIONVALUEVOLUMETYPE_READ, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATE, ORACLE_TRANSACTIONLOG_GROUPBY,
    ORACLE_TRANSACTIONLOG_WHERECLAUSE_SERVICENAME, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONID, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TRANSACTIONDATEBETWEEN,
    ORACLE_TRANSACTIONLOG_WHERECLAUSE_AMOUNT, ORACLE_TRANSACTIONLOG_WHERECLAUSE_FROMACCOUNTTYPE, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TOACCOUNTTYPE,
    ORACLE_TRANSACTIONLOG_WHERECLAUSE_STATUS, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TYPE, ORACLE_TRANSACTIONLOG_WHERECLAUSE_CURRENCYCODE,
    ORACLE_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILLIKE, ORACLE_TRANSACTIONLOG_WHERECLAUSE_FROMMOBILEOREMAILNOTLIKE,
    ORACLE_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILLIKE, ORACLE_TRANSACTIONLOG_WHERECLAUSE_TOMOBILEOREMAILNOTLIKE, ORACLE_TRANSACTIONLOG_ORDERBY,

    // Audit logs
    ORACLE_AUDITLOG_READ, ORACLE_AUDITLOG_ARCH_READ, ORACLE_AUDITLOG_INSERT, ORACLE_AUDITLOG_DELETE, ORACLE_AUDITLOG_COUNT_READ,
    ORACLE_AUDITLOG_SEARCH_SELECT_QUERY, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_USERNAME, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_CUSTOMERID,
    ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_FROMACCOUNTNUMBER, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_TOACCOUNTNUMBER, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_ISCSRASSIST,
    ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_EVENTTYPE, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_EVENTSUBTYPE,
    ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_AMOUNT, ORACLE_AUDITLOG_SEARCH_WHERECLAUSE_CREATEDTS, ORACLE_AUDITLOG_LAST_N_SESSIONS,

    // MoneyMovement logs
    ORACLE_MONEYMOVEMENT_READ, ORACLE_MONEYMOVEMENT_DELETE, ORACLE_MONEYMOVEMENT_INSERT,
    
    // Limit
    MYSQL_LIMIT,MSSQL_LIMIT,MYSQL_LIMIT_ARCH,MSSQL_LIMIT_ARCH, MYSQL_DATE_CAST, MSSQL_DATE_CAST,
    ORACLE_LIMIT,ORACLE_LIMIT_ARCH,ORACLE_DATE_CAST,
    
    // Eventts column 
    MYSQL_QUERY_EVENTTS, MSSQL_QUERY_EVENTTS, ORACLE_QUERY_EVENTTS,
    
    // TransactionDate column
    MYSQL_READQUERY_TRANSACTIONDATE, MSSQL_READQUERY_TRANSACTIONDATE, ORACLE__READQUERY_TRANSACTIONDATE,
    
    // mapLogTypeAndDeleteQueries LogArchiveDAO
    MYSQL_DELETEQUERY_WHERECLAUSE, MSSQL_DELETEQUERY_WHERECLAUSE, ORACLE_DELETEQUERY_WHERECLAUSE,
    ;

	private static final Alert alert = Logger.forAlert().forModule("Infinity", "SPOTLIGHT");
    private static final Properties PROPS = loadProps();

    private SQLQueriesEnum() {
    }

    private static Properties loadProps() {
        Properties properties = new Properties();
        try (InputStream inputStream = SQLQueriesEnum.class.getClassLoader()
                .getResourceAsStream("sql-queries.properties")) {
            properties.load(inputStream);
            return properties;
        } catch (Exception e) {
            alert.prepareError("Error while loading sql-queries.properties", e).log();
        }
        return properties;
    }

    /**
     * Returns query associated with this enum constant
     * 
     * @param key
     * @return
     */
    public String getQuery() {
        return PROPS.getProperty(this.name());
    }

    static final Map<Class<? extends BaseActivity>, String> LOG_INSERT_QUERIES_MAPPER =
            mapLogTypeAndInsertQueries();

    static final Map<Class<? extends BaseActivity>, String> LOG_DELETE_QUERIES_MAPPER =
            mapLogTypeAndDeleteQueries();

    static final Map<Class<? extends BaseActivity>, String> LOG_READ_QUERIES_MAPPER =
            mapLogTypeAndReadQueries();

    /**
     * Mapper maps sub class of type {@link BaseActivity} to corresponding insert query constant from
     * {@link SQLQueriesEnum}
     * 
     * @return
     */
    public static Map<Class<? extends BaseActivity>, String> mapLogTypeAndInsertQueries() {
        Map<Class<? extends BaseActivity>, String> map = new HashMap<>();
        map.put(TransactionActivityDTO.class, QueryFormer.replaceDbType("TRANSACTIONLOG_INSERT"));
        map.put(AdminActivityDTO.class, QueryFormer.replaceDbType("ADMINACTIVITY_INSERT"));
        map.put(CustomerActivityDTO.class, QueryFormer.replaceDbType("CUSTOMERACTIVITY_INSERT"));
        map.put(AdminCustomerActivityDTO.class, QueryFormer.replaceDbType("ADMINCUSTOMERACTIVITY_INSERT"));
        map.put(AuditActivityDTO.class, QueryFormer.replaceDbType("AUDITLOG_INSERT"));
        map.put(MoneyMovementLogDTO.class, QueryFormer.replaceDbType("MONEYMOVEMENT_INSERT"));
        return map;
    }

    /**
     * Mapper maps sub class of type {@link BaseActivity} to corresponding delete query constant from
     * {@link SQLQueriesEnum}
     * 
     * @return
     */
    public static Map<Class<? extends BaseActivity>, String> mapLogTypeAndDeleteQueries() {
        Map<Class<? extends BaseActivity>, String> map = new HashMap<>();
        map.put(TransactionActivityDTO.class, QueryFormer.replaceDbType("TRANSACTIONLOG_DELETE"));
        map.put(AdminActivityDTO.class, QueryFormer.replaceDbType("ADMINACTIVITY_DELETE"));
        map.put(CustomerActivityDTO.class, QueryFormer.replaceDbType("CUSTOMERACTIVITY_DELETE"));
        map.put(AdminCustomerActivityDTO.class, QueryFormer.replaceDbType("ADMINCUSTOMERACTIVITY_DELETE"));
        map.put(AuditActivityDTO.class, QueryFormer.replaceDbType("AUDITLOG_DELETE"));
        map.put(MoneyMovementLogDTO.class, QueryFormer.replaceDbType("MONEYMOVEMENT_DELETE"));
        return map;
    }

    /**
     * Mapper maps sub class of type {@link BaseActivity} to corresponding read query constant from
     * {@link SQLQueriesEnum}
     * 
     * @return
     */
    public static Map<Class<? extends BaseActivity>, String> mapLogTypeAndReadQueries() {
        Map<Class<? extends BaseActivity>, String> map = new HashMap<>();
        map.put(TransactionActivityDTO.class, QueryFormer.replaceDbType("TRANSACTIONLOG_READ"));
        map.put(AdminActivityDTO.class, QueryFormer.replaceDbType("ADMINACTIVITY_READ"));
        map.put(CustomerActivityDTO.class, QueryFormer.replaceDbType("CUSTOMERACTIVITY_READ"));
        map.put(AdminCustomerActivityDTO.class, QueryFormer.replaceDbType("ADMINCUSTOMERACTIVITY_READ"));
        map.put(AuditActivityDTO.class, QueryFormer.replaceDbType("AUDITLOG_ARCH_READ"));
        map.put(MoneyMovementLogDTO.class, QueryFormer.replaceDbType("MONEYMOVEMENT_READ"));
        return map;
    }

    /**
     * Returns insert sql string for the provided concrete class of type {@link BaseActivity}
     * 
     * @param clazz
     * @return
     */
    public static <T extends BaseActivity> String getActivityInsertQuery(Class<T> clazz) {
        return SQLQueriesEnum.valueOf(LOG_INSERT_QUERIES_MAPPER.get(clazz))
        		.getQuery().replace("?1", QueryFormer.dbName);
    }

    /**
     * Returns delete sql string for the provided concrete class of type {@link BaseActivity}
     * 
     * @param clazz
     * @return
     */
    public static <T extends BaseActivity> String getActivityDeleteQuery(Class<T> clazz) {
        return SQLQueriesEnum.valueOf(LOG_DELETE_QUERIES_MAPPER.get(clazz))
        		.getQuery().replace("?1", QueryFormer.dbName);
    }

    /**
     * Returns select sql string for the provided concrete class of type {@link BaseActivity}
     * 
     * @param clazz
     * @return
     */
    public static <T extends BaseActivity> String getActivityReadQuery(Class<T> clazz) {
        return SQLQueriesEnum.valueOf(LOG_READ_QUERIES_MAPPER.get(clazz))
        		.getQuery().replace("?1", QueryFormer.dbName);
    }

}
