INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_OPS', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_OPS_SUPERVISIOR', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_RM', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_RM_SUPERVISIOR', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAIL_SYSTEM_ADMIN', N'PID524');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID524');

INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_OPS', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_OPS_SUPERVISIOR', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_RM', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAILONBOARDING_RM_SUPERVISIOR', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RETAIL_SYSTEM_ADMIN', N'PID525');
INSERT INTO [${dbxschemaname}].[rolepermission] ([Role_id], [Permission_id]) VALUES (N'RID_RetailUW', N'PID525');

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '{"disputeTransactionErrors":[{"id": "disputeReason1","value": "I dont recognize this transaction"},{"id": "disputeReason2","value": "Goods and services not received"},{"id": "disputeReason3","value": "Billing error"},{"id": "disputeReason4","value": "Duplicate transaction"},{"id": "disputeReason5","value": "Recurring debit which was cancelled"}]}' where [config_key] = 'DISPUTE_REASON_CONFIG'; 

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '{"disputeTransferConfig":[{"id" : "1","description" : "both","isDisputeAllowed" : "true"},{"id" : "2","description" : "debit","isDisputeAllowed" : "true"},{"id" : "3","description" : "credit","isDisputeAllowed" : "true"}]}' where [config_key] = 'DISPUTE_TRANSACTION_CONFIG'; 

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '{"disputeScenariosConfig":[{"id" : "1","description" : "InternalTransfer","isDisputeAllowed" : "true"},{"id" : "2","description" : "BillPay","isDisputeAllowed" : "true"},{"id" : "3","description" : "ExternalTransfer","isDisputeAllowed" : "true"},{"id" : "4","description" : "Deposit","isDisputeAllowed" : "false"},{"id" : "5","description" : "P2P","isDisputeAllowed" : "true"},{"id" : "6","description" : "Cardless","isDisputeAllowed" : "true"},{"id" : "7","description" : "CheckWithdrawal","isDisputeAllowed" : "true"},{"id" : "8","description" : "Withdrawal","isDisputeAllowed" : "true"},{"id" : "9","description" : "Interest","isDisputeAllowed" : "false"},{"id" : "10","description" : "Request","isDisputeAllowed" : "false"},{"id" : "11","description" : "Loan","isDisputeAllowed" : "false"},{"id" : "12","description" : "ReceivedP2P","isDisputeAllowed" : "false"},{"id" : "13","description" : "ReceivedRequest","isDisputeAllowed" : "false"},{"id" : "14","description" : "StopCheckPaymentRequest","isDisputeAllowed" : "false"},{"id" : "15","description" : "Wire","isDisputeAllowed" : "true"},{"id" : "16","description" : "Credit","isDisputeAllowed" : "false"},{"id" : "17","description" : "InternetTransaction","isDisputeAllowed" : "true"},{"id" : "18","description" : "POS","isDisputeAllowed" : "true"},{"id" : "19","description" : "CardPayment","isDisputeAllowed" : "true"},{"id" : "20","description" : "Tax","isDisputeAllowed" : "false"},{"id" : "21","description" : "Fee","isDisputeAllowed" : "false"},{"id" : "22","description" : "SwiftPayment","isDisputeAllowed" : "true"},{"id" : "23","description" : "Draft","isDisputeAllowed" : "true"},{"id" : "24","description" : "Transfers","isDisputeAllowed" : "true"},{"id" : "25","description" : "Others","isDisputeAllowed" : "true"}]}' where [config_key] = 'DISPUTE_TRANSACTION_TYPE_CONFIG'; 
