USE [${logdbname}]
GO
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'BiWeekly')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Daily')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Every Two Weeks')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Half Yearly')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Monthly')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Once')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Quarterly')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Weekly')
INSERT [${logschemaname}].[freq1] ([freqId]) VALUES (N'Yearly')
GO
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Auto & Transport')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Bills & Utilities')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Business Services')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Education')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Entertainment')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Fees & Charges')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Financial')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Food & Dining')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Gifts & Donations')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Health & Fitness')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Home')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Income')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Investments')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Kids')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Personal Care')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Pets')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Shopping')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Taxes')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Transfer')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Travel')
INSERT [${logschemaname}].[tcategories] ([categId]) VALUES (N'Uncategorised')
GO
INSERT [${logschemaname}].[billcategory] ([billcategId]) VALUES (N'Credit Card')
INSERT [${logschemaname}].[billcategory] ([billcategId]) VALUES (N'Insurance')
INSERT [${logschemaname}].[billcategory] ([billcategId]) VALUES (N'Phone')
INSERT [${logschemaname}].[billcategory] ([billcategId]) VALUES (N'Utilities')
GO
