######
#
# T24 properties
#
######
Temenos.Enrollment.PreLoginUserName = Admin
Temenos.Enrollment.PreLoginUserId = 10
#Temenos.General.RoleId = ADMIN             -TSR-762075
Temenos.General.RoleId = INFINITY.RETAIL 
Temenos.Party.RoleId = INFINITY.RETAIL
Temenos.PartyEnrollment.PreLoginUserName = T24
Temenos.PartyEnrollment.PreLoginUserId = 0001




