INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','accountsstatementfiles','where userId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','achfile','where createdby = ?','achFile_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','achfilerecord','where achFileId in (select achFile_id from [${dbxschemaname}].[achfile] where createdby = ? )','achFileRecordId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','achfilesubrecord','where achFileRecordId in (select achFileRecordId from [${dbxschemaname}].[achfilerecord] where achFileId in (select achFile_id from [${dbxschemaname}].[achfile] where createdby = ? ))','achFileSubRecordId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','achtransaction','where createdby = ?','transaction_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','achtransactionrecord','where transaction_id in (select transaction_id from [${dbxschemaname}].[achtransaction] where createdby = ? )','transactionRecord_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','address','where id in (select Address_id from [${dbxschemaname}].[customeraddress] where Customer_id = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','admincustomeractivity','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','alerthistory','where Customer_Id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','approvalmatrix','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','approvalmode','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','archivedalerthistory','where Customer_Id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','archivedauditactivity','where Customer_Id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','archivedmoneymovementlog','where Customer_id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','auditactivity','where Customer_Id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','backendidentifier','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bbactedrequest','where createdby = ?','approvalId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bbrequest','where createdby = ?','requestId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bbtemplate','where createdby = ?','templateId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bbtemplaterecord','where template_id in (select templateId from [${dbxschemaname}].[bbtemplate] where createdby = ? )','templateRecord_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','billpaypayee','where cif in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymentfiles','where createdby = ?','fileId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymentrecord','where createdby = ?','recordId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymentrequest','where createdby = ?','paymentrequestId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymentrequestpos','where createdby = ?','paymentrequestPOId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymentsubrecord','where createdby = ?','paymentOrderId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymenttemplate','where createdby = ?','templateId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','bulkpaymenttemplatepos','where createdby = ?','paymentOrderId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractaccounts','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractactionlimit','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractcommunication','where contractId in (select contractId from [${dbxschemaname}].[contractcustomers] where customerId = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractcorecustomers','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractcustomers','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractcustomrole','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','contractfeatures','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','coremembership','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','credentialchecker','where UserName in (select UserName from [${dbxschemaname}].[customer] where id = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','csrassistgrant','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','custcompletedcampaign','where customer_id = ?','customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customer','where id  = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeraccounts','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeraction','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','customeractivity','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeraddress','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeralertchannel','where customerId = ?','customerId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeralertfrequency','where customerId = ?','customerId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customeralertswitch','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerapprovalmatrix','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerbusinesstype','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customercommunication','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerdevice','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customergroup','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerimage','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerlimitgrouplimits','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customernote','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customernotification','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerpreference','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customerrequest','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customersecurityquestions','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customersignatorygroup','where customerId = ?','customerSignatoryGroupId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customertermsandconditions','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customroleaccounts','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','customroleactionlimits','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','dbxcustomeralertentitlement','where Customer_id = ?','Customer_id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','deviceregistration','where User_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','excludedcontractaccounts','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','excludedcustomeraccounts','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','externalaccount','where User_id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','favouriteinstruments','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','feedback','where user_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','feedbackstatus','where customerID = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','interbankfundtransfers','where fromAccountNumber in (select Account_id from [${dbxschemaname}].[customeraccounts] where Customer_id = ? )','transactionId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','interbankpayee','where cif in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','internationalfundtransfers','where fromAccountNumber in (select Account_id from [${dbxschemaname}].[customeraccounts] where Customer_id = ? )','transactionId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','internationalpayee','where cif in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','intrabankpayee','where cif in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','intrabanktransfers','where fromAccountNumber in (select Account_id from [${dbxschemaname}].[customeraccounts] where Customer_id = ? )','transactionId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','location','where Address_id in (select Address_id from [${dbxschemaname}].[customeraddress] where Customer_id = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','manageapprovalmatrix','where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','contractId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','membership','where addressId in (select Address_id from [${dbxschemaname}].[customeraddress] where Customer_id = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','mfaservice','where User_id = ?','serviceKey');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','moneymovementlog','where Customer_id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','notificationcardinfo','where Customer_id = ? ','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','OTP','where User_id = ?','securityKey');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','otpcount','where User_id = ?','key');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','ownaccounttransfers','where fromAccountNumber in (select Account_id from [${dbxschemaname}].[customeraccounts] where Customer_id = ? )','transactionId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','p2ppayee','where cif in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24'')','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','p2pregistration','where user_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','passwordhistory','where Customer_id = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','payee','where User_Id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','paymentfiles','where userId = ?','paymentFileID');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','recentcurrencies','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','requestmessage','where modifiedby in (select UserName from [${dbxschemaname}].[customer] where id = ? )','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','signatorygroupmatrix','where approvalMatrixId in (select id from [${dbxschemaname}].[approvalmatrix] where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24''))','signatoryGroupMatrixId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','signatorygrouprequestmatrix','where approvalMatrixId in (select id from [${dbxschemaname}].[approvalmatrix] where coreCustomerId in (select BackendId from [${dbxschemaname}].[backendidentifier] where Customer_id = ? AND BackendType = ''T24''))','signatoryGroupRequestMatrixId');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','suspendedcustomers','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','transaction','where Customer_id = ?','Id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxlogs','transactionlog','where customerId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','transactionlogs','where userId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','travelnotification','where createdby = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','wealthuserpreferences','where userId = ?','id');
INSERT INTO [${dbxschemaname}].[queryconfig] ([dbname],[tablename],[querystring],[primaryKey]) VALUES('dbxdb','wiretransferspayee','where contractId in (select contractId from [${dbxschemaname}].[contractcustomers] where customerId = ? )','id');
GO

INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'61b8365c-7fc1-4685-a1f3-4c8b25332413', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'5a11f3e3-3022-478f-827c-0363fbb952a7', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'5dbc4a4d-d722-4721-b0de-d285e3ca7e57', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'57300402-803b-4b2f-99af-32c584b5dd86', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'e6ef4a43-60c5-42ca-8689-b76a0a2004ea', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'4f933e77-00d3-42a1-8503-7ec6ce832593', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de482', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de483', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'ddf80d75-fa42-4bbb-8029-a96018296826', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'33c91eea-3a05-4a1c-a6ff-982bf1ee691c', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'dfe013ee-50f5-4ca2-afd1-24d0937ab410', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e30-44995d88584e', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e31-44995d88584e', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e2-c31578349519', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e3-c31578349514', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
																			   
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'c5f5d482-595c-41d9-be4b-0bfe0e263929', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'c9a3348d-437b-40be-a683-841d7ed07f81', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'a5faf805-851f-436e-ad7b-fa5121610321', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'7f76ca3f-3113-46c3-8cba-84ddbe141c5d', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283302', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283303', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'e9931001-f979-441b-ac3f-638c7448637f', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'c4d54eba-7cb5-45d2-aa35-091b4efb029f', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'd0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db1', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db2', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'260e3597-5e15-49d2-892b-4b97defea5ae', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob]([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'260e3597-5e15-49d2-892b-4b97defea5af', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');

GO

INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'ffdbc23c-cb88-423f-8d2c-b6f641636f44', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'c7f17939-78e2-418f-8d33-0bbd07c70446', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'1337d8a6-e8c1-4c53-b6aa-808698b07584', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'354743d9-bd17-4635-b057-6a94166eabbb', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', N'TYPE_ID_RETAILONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'1c219e1e-c28c-4c54-8b25-47175195f161', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'474c5314-11d2-4e91-a17b-e6053d5e366f', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[userlob] ([userId], [lobId], [softdeleteflag], [companyLegalUnit]) VALUES (N'796a50eb-e7b5-4e11-b21b-fc8adf3725ec', N'TYPE_ID_SMEONBOARDING', N'0', N'ALL');

INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'61b8365c-7fc1-4685-a1f3-4c8b25332413', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'5a11f3e3-3022-478f-827c-0363fbb952a7', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'5dbc4a4d-d722-4721-b0de-d285e3ca7e57', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'57300402-803b-4b2f-99af-32c584b5dd86', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'e6ef4a43-60c5-42ca-8689-b76a0a2004ea', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'4f933e77-00d3-42a1-8503-7ec6ce832593', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de482', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de483', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'ddf80d75-fa42-4bbb-8029-a96018296826', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'33c91eea-3a05-4a1c-a6ff-982bf1ee691c', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'dfe013ee-50f5-4ca2-afd1-24d0937ab410', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e30-44995d88584e', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e31-44995d88584e', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e2-c31578349519', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e3-c31578349514', N'retailsuperuser', N'0', N'ALL');

INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'c5f5d482-595c-41d9-be4b-0bfe0e263929', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'c9a3348d-437b-40be-a683-841d7ed07f81', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'a5faf805-851f-436e-ad7b-fa5121610321', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'7f76ca3f-3113-46c3-8cba-84ddbe141c5d', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283302', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283303', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'e9931001-f979-441b-ac3f-638c7448637f', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'c4d54eba-7cb5-45d2-aa35-091b4efb029f', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'd0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db1', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db2', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'260e3597-5e15-49d2-892b-4b97defea5ae', N'smesuperuser', N'0', N'ALL');


INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'ffdbc23c-cb88-423f-8d2c-b6f641636f44', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'c7f17939-78e2-418f-8d33-0bbd07c70446', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'1337d8a6-e8c1-4c53-b6aa-808698b07584', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'354743d9-bd17-4635-b057-6a94166eabbb', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', N'retailsuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'1c219e1e-c28c-4c54-8b25-47175195f161', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'474c5314-11d2-4e91-a17b-e6053d5e366f', N'smesuperuser', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusermanager] ([userId], [manager], [softdeleteflag], [companyLegalUnit]) VALUES (N'796a50eb-e7b5-4e11-b21b-fc8adf3725ec', N'smesuperuser', N'0', N'ALL');

INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'61b8365c-7fc1-4685-a1f3-4c8b25332413', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'5a11f3e3-3022-478f-827c-0363fbb952a7', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'5dbc4a4d-d722-4721-b0de-d285e3ca7e57', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'57300402-803b-4b2f-99af-32c584b5dd86', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'e6ef4a43-60c5-42ca-8689-b76a0a2004ea', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'4f933e77-00d3-42a1-8503-7ec6ce832593', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de482', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de483', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'ddf80d75-fa42-4bbb-8029-a96018296826', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'33c91eea-3a05-4a1c-a6ff-982bf1ee691c', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'dfe013ee-50f5-4ca2-afd1-24d0937ab410', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e30-44995d88584e', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e31-44995d88584e', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e2-c31578349519', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e3-c31578349514', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');


INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'c5f5d482-595c-41d9-be4b-0bfe0e263929', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'c9a3348d-437b-40be-a683-841d7ed07f81', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'a5faf805-851f-436e-ad7b-fa5121610321', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'7f76ca3f-3113-46c3-8cba-84ddbe141c5d', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283302', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283303', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'e9931001-f979-441b-ac3f-638c7448637f', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'c4d54eba-7cb5-45d2-aa35-091b4efb029f', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'd0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db1', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db2', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'260e3597-5e15-49d2-892b-4b97defea5ae
', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');


INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'ffdbc23c-cb88-423f-8d2c-b6f641636f44', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'c7f17939-78e2-418f-8d33-0bbd07c70446', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'1337d8a6-e8c1-4c53-b6aa-808698b07584', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'354743d9-bd17-4635-b057-6a94166eabbb', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'1c219e1e-c28c-4c54-8b25-47175195f161', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'474c5314-11d2-4e91-a17b-e6053d5e366f', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[useraddress] ([User_id], [Address_id], [Type_id], [softdeleteflag], [companyLegalUnit]) VALUES (N'796a50eb-e7b5-4e11-b21b-fc8adf3725ec', N'DMSADDR1', N'ADR_TYPE_WORK',N'0', N'ALL');

INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'61b8365c-7fc1-4685-a1f3-4c8b25332413', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'5a11f3e3-3022-478f-827c-0363fbb952a7', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'5dbc4a4d-d722-4721-b0de-d285e3ca7e57', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'57300402-803b-4b2f-99af-32c584b5dd86', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'e6ef4a43-60c5-42ca-8689-b76a0a2004ea', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'4f933e77-00d3-42a1-8503-7ec6ce832593', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de482', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'a884f15c-f347-4138-9cda-d20cc35de483', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'fcdb6334-edb3-4d9b-a7fa-2d9f11dc345e', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'ddf80d75-fa42-4bbb-8029-a96018296826', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'dc99c2fd-cc86-4a04-b1b8-7cfc6884a0a7', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'33c91eea-3a05-4a1c-a6ff-982bf1ee691c', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'dfe013ee-50f5-4ca2-afd1-24d0937ab410', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e30-44995d88584e', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'6829d098-35d3-427c-9e31-44995d88584e', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e2-c31578349519', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'4edab350-378f-4a55-81e3-c31578349514', N'INTERNAL', N'0', N'ALL');


INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'c5f5d482-595c-41d9-be4b-0bfe0e263929', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'c9a3348d-437b-40be-a683-841d7ed07f81', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'a5faf805-851f-436e-ad7b-fa5121610321', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'7f76ca3f-3113-46c3-8cba-84ddbe141c5d', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283302', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'73877665-5a54-4993-94c2-b0d759283303', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'e9931001-f979-441b-ac3f-638c7448637f', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'c4d54eba-7cb5-45d2-aa35-091b4efb029f', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'd0ccd4a4-4be7-4d44-8ee2-ecef49b9e466', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db1', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'68315eb0-24fe-409b-a517-a4ddf1b11db2', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'260e3597-5e15-49d2-892b-4b97defea5ae
', N'INTERNAL', N'0', N'ALL');

INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'ffdbc23c-cb88-423f-8d2c-b6f641636f44', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'c7f17939-78e2-418f-8d33-0bbd07c70446', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'1337d8a6-e8c1-4c53-b6aa-808698b07584', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'354743d9-bd17-4635-b057-6a94166eabbb', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'a58d8e12-cfcc-4eae-8d48-64bbf0d5aa9f', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'1c219e1e-c28c-4c54-8b25-47175195f161', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'474c5314-11d2-4e91-a17b-e6053d5e366f', N'INTERNAL', N'0', N'ALL');
INSERT INTO [${dbxschemaname}].[internalusertype] ([userId], [userType], [softdeleteflag], [companyLegalUnit]) VALUES (N'796a50eb-e7b5-4e11-b21b-fc8adf3725ec', N'INTERNAL', N'0', N'ALL');

GO