default=PayeeVerificationJavaServices.paymentTypePayeeVerification
SameBank=PayeeVerificationJavaServices.paymentTypeSameBankPayeeVerification
Domestic=PayeeVerificationJavaServices.paymentTypeDomesticPayeeVerification
International=PayeeVerificationJavaServices.paymentTypeInternationalPayeeVerification