INSERT INTO [${dbxschemaname}].[configurationbundles] ([bundle_id], [bundle_name], [app_id], [createdby], [modifiedby]) VALUES ('INFINITY_ASSIST_CONFIG_BUNDLE', 'InfinityAssist', 'InfinityAssist', 'Kony dev', 'Kony dev');
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_1', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_OFAC_CHECK_REPORT_WITHIN_DAYS', N'Retail OFAC check report', N'5', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_2', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_BLACKLIST_CHECK_REPORT_WITHIN_DAYS', N'Retail blacklist check report', N'5', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_3', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_BUREAU_CHECK', N'Retail bureau check', N'{\"provider\":\"Experian\",\"withinDays\":\"30\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_4', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_OFFER_ACCEPTANCE_MODE', N'Retail offer acceptance mode', N'Offline', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_5', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'RETAIL_RM_SUPERVISOR', N'Retail rm supervisor', N'rmautouser', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{\"provider\":\"07\",\"withinDays\":\"30\"}'  WHERE (configuration_id = 'IA_3');
GO

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_6', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_OFAC_CHECK_REPORT_WITHIN_DAYS', N'SME OFAC check report', N'5', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_7', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_BLACKLIST_CHECK_REPORT_WITHIN_DAYS', N'SME blacklist check report', N'5', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_8', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_BUSINESS_BUREAU_CHECK', N'SME Business Bureau Check', N'{\"provider\":\"Experian\",\"withinDays\":\"30\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_9', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_RELATED_PARTY_BUREAU_CHECK', N'SME Related Party Bureau Check', N'{\"provider\":\"Experian\",\"withinDays\":\"30\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_10', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_OFFER_ACCEPTANCE_MODE', N'SME offer acceptance mode', N'Offline', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_11', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'SME_RM_SUPERVISOR', N'SME rm supervisor', N'smermautouser', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
insert into [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdby], [modifiedby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) values 
('4e31abf8-0019-4c3b-876d-b3a19eaca3bc', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'ASSESSMENT_MOCK_SERVICE_STATUS', 'Mock status data for OFAC/Blacklist ', '{\"blacklist_mock_flag\" : \"true\",\"ofac_mock_flag\" : \"true\",\"ofac_status\": \"pass\",\"blacklist_status\": \"pass\"}', 'CLIENT', '1', '', '', '2021-10-08 10:19:19', '2021-10-08 10:19:19', '2021-10-08 10:19:19', '0');
GO
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{\"provider\":\"07\",\"withinDays\":\"30\"}'  WHERE (configuration_id = 'IA_8');
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{\"provider\":\"07\",\"withinDays\":\"30\"}'  WHERE (configuration_id = 'IA_9');
GO
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_12', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'PRODUCTID_MCMS_REDHAT_MAPPING', N'Mapping of MCMS product ids to Redhat Identifiers', N'{\"ADVANCED.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"BASIC.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"PREFERRED.CHECKING.ACCOUNT\":\"RETAIL.UNSECURED\",\"SAVINGS.PRIME.INFINITY\":\"RETAIL.UNSECURED\",\"SAVINGS.STANDARD.INFINITY\":\"RETAIL.UNSECURED\",\"SAVINGS.SALARY.INFINITY\":\"RETAIL.UNSECURED\",\"INFINITY.ADAMANTIUM.CARD\":\"RETAIL.UNSECURED\",\"INFINITY.VIBRANIUM.CARD\":\"RETAIL.UNSECURED\",\"INFINITY.BESKAR.CARD\":\"RETAIL.UNSECURED\",\"OVERDRAFT.ACCOUNT\":\"RETAIL.UNSECURED\",\"PERSONAL.LOAN\":\"RETAIL.UNSECURED\",\"OVERDRAFT.ACCOUNT.SME\":\"SME.OVERDRAFT\",\"INFINITY.TRAVEL.CARD\":\"SME.CREDITCARD\",\"INFINITY.FUSION.BUSINESS.CARD\":\"SME.CREDITCARD\",\"INFINITY.UNLIMITED.REWARDS.CARD\":\"SME.CREDITCARD\",\"SMALL.BUSINESS.LOAN\":\"SME.LOAN\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'IA_13', N'INFINITY_ASSIST_CONFIG_BUNDLE', N'PREFERENCE', N'FINANCIAL_RATIO_DEFAULT_VALUES', N'Default values for Financial Ratio Fields', N'{\"debtToIncomeRatio\":\"50\",\"dscr\":\"3.5\",\"debtToEquity\":\"1.1\",\"operatingMargin\":\"0.30\",\"netProfitMargin\":\"0.40\",\"currentRatio\":\"1.8\"}', N'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO
UPDATE [${dbxschemaname}].[configurations] SET config_value= '{\"blacklist_mock_flag\" : \"true\",\"ofac_mock_flag\" : \"true\",\"ofac_status\": \"pass\", \"blacklist_status\": \"pass\", \"bureau_mock_flag\" : \"true\", \"mock_bureau_eventType\" : \"Business Bureau\", \"mock_bureau_level\" : \"package1\", \"mock_bureau_score\" : \"1000\", \"mock_bureau_status\" : \"Pending\"}'  WHERE (configuration_id = '4e31abf8-0019-4c3b-876d-b3a19eaca3bc');
GO