USE [${dbxdbname}]
GO

DELETE FROM [${dbxschemaname}].[groupactionlimit] WHERE ([id] = '82235ea9-c3cb-430f-a318-eba98a8ac58b');
DELETE FROM [${dbxschemaname}].[groupactionlimit] WHERE ([id] = '90cf9505-dadd-46e2-8adc-4919e2fc44a3');
DELETE FROM [${dbxschemaname}].[groupactionlimit] WHERE ([id] = 'aac00784-791b-11ea-9300-00090faa1002');
GO

DELETE FROM [${dbxschemaname}].[servicedefinitionactionlimit] WHERE ([id] = '3fc017dd-4dd4-4bfd-9492-0d4ef2c1ce3f');
DELETE FROM [${dbxschemaname}].[servicedefinitionactionlimit] WHERE ([id] = '98d249a9-9e64-4b8e-9c98-6498ec0da641');
DELETE FROM [${dbxschemaname}].[servicedefinitionactionlimit] WHERE ([id] = '16756222-6516-11eb-ae93-0242ac130002');
DELETE FROM [${dbxschemaname}].[servicedefinitionactionlimit] WHERE ([id] = 'c02bfc54-3aab-487d-9c6e-47938fbeeeba');
DELETE FROM [${dbxschemaname}].[servicedefinitionactionlimit] WHERE ([id] = '20033197-94f0-4044-8a1e-3e39bc1b8eaa');
GO

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '365' WHERE ([configuration_id] = '93');
GO

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '{\"disputeScenariosConfig\":[{\"id\" : \"1\",\"description\" : \"InternalTransfer\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"2\",\"description\" : \"BillPay\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"3\",\"description\" : \"ExternalTransfer\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"4\",\"description\" : \"Deposit\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"5\",\"description\" : \"P2P\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"6\",\"description\" : \"Cardless\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"7\",\"description\" : \"CheckWithdrawal\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"8\",\"description\" : \"Withdrawal\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"9\",\"description\" : \"Interest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"10\",\"description\" : \"Request\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"11\",\"description\" : \"Loan\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"12\",\"description\" : \"ReceivedP2P\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"13\",\"description\" : \"ReceivedRequest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"14\",\"description\" : \"StopCheckPaymentRequest\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"15\",\"description\" : \"Wire\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"16\",\"description\" : \"Credit\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"17\",\"description\" : \"InternetTransaction\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"18\",\"description\" : \"POS\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"19\",\"description\" : \"CardPayment\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"20\",\"description\" : \"Tax\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"21\",\"description\" : \"Fee\",\"isDisputeAllowed\" : \"false\"},{\"id\" : \"22\",\"description\" : \"SwiftPayment\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"23\",\"description\" : \"Draft\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"24\",\"description\" : \"Transfers\",\"isDisputeAllowed\" : \"true\"},{\"id\" : \"25\",\"description\" : \"Others\",\"isDisputeAllowed\" : \"true\"}]}' WHERE ([configuration_id] = '92');
GO
INSERT INTO [${dbxschemaname}].[rrole] ([id],[createdts],[lastmodifiedts],[softdeleteflag]) VALUES ('UNIFIED_TRANSFER-CREATE',GETDATE(),GETDATE(),0);
GO
INSERT INTO [${dbxschemaname}].[feature]([id], [App_id], [name], [description], [Type_id], [Status_id], [Service_Fee], [DisplaySequence],[isPrimary],[createdby],[modifiedby],[softdeleteflag]) VALUES ('UNIFIED_TRANSFER','RETAIL_AND_BUSINESS_BANKING','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer','MONETARY','SID_FEATURE_ACTIVE', null, 80, 0,null,null,0);
GO
INSERT INTO [${dbxschemaname}].[featureroletype]([RoleType_id],[Feature_id]) VALUES ('TYPE_ID_BUSINESS','UNIFIED_TRANSFER');
INSERT INTO [${dbxschemaname}].[featureroletype]([RoleType_id],[Feature_id]) VALUES ('TYPE_ID_RETAIL','UNIFIED_TRANSFER');
GO
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id],[Locale_id],[displayName],[displayDescription])VALUES ('UNIFIED_TRANSFER','de-DE','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer');
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id],[Locale_id],[displayName],[displayDescription])VALUES ('UNIFIED_TRANSFER','en-US','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer');
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id],[Locale_id],[displayName],[displayDescription])VALUES ('UNIFIED_TRANSFER','en-GB','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer');
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id],[Locale_id],[displayName],[displayDescription])VALUES ('UNIFIED_TRANSFER','es-ES','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer');
INSERT INTO [${dbxschemaname}].[featuredisplaynamedescription]([Feature_id],[Locale_id],[displayName],[displayDescription])VALUES ('UNIFIED_TRANSFER','fr-FR','Unified Transfer','Fund Transfers to own accounts & Third Party Accounts in Unified Transfer');
GO
INSERT INTO [${dbxschemaname}].[featureaction] ([id], [Feature_id], [App_id], [Type_id], [Rrole_id], [name], [description], [isAccountLevel], [isPrimary], [DisplaySequence], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag], [status], [limitgroupId], [accesspolicyId], [actionlevelId], [approveFeatureAction], [isApprovalAction]) VALUES ('UNIFIED_TRANSFER_CREATE', 'UNIFIED_TRANSFER', 'RETAIL_AND_BUSINESS_BANKING', 'MONETARY', 'UNIFIED_TRANSFER-CREATE', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer', '1', '1', '1', GETDATE(), GETDATE(), GETDATE(), '0', 'SID_ACTION_ACTIVE', 'SINGLE_PAYMENT', 'CREATE', 'ACCOUNT_LEVEL', null, '0');
GO
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id],[Action_id]) VALUES ('TYPE_ID_BUSINESS','UNIFIED_TRANSFER_CREATE');
INSERT INTO [${dbxschemaname}].[featureactionroletype] ([RoleType_id],[Action_id]) VALUES ('TYPE_ID_RETAIL','UNIFIED_TRANSFER_CREATE');
GO
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UNIFIED_TRANSFER_CREATE', 'de-DE', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UNIFIED_TRANSFER_CREATE', 'en-GB', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UNIFIED_TRANSFER_CREATE', 'en-US', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UNIFIED_TRANSFER_CREATE', 'es-ES', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer');
INSERT INTO [${dbxschemaname}].[actiondisplaynamedescription] ([Action_id], [Locale_id], [displayName], [displayDescription]) VALUES ('UNIFIED_TRANSFER_CREATE', 'fr-FR', 'Show Unified Transfer','Make Transfers to own accounts & Third Party Accounts and add beneficiaries in Unified Transfer');
GO
INSERT INTO [${dbxschemaname}].[compositeaction] ([id], [Permission_id], [Action_id], [Feature_id], [isEnabled]) VALUES ('CAID251', 'PID45', 'UNIFIED_TRANSFER_CREATE', 'BULK_PAYMENT_REQUEST', '1');
GO
INSERT INTO [${dbxschemaname}].[actionlimit] ([Action_id], [LimitType_id], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[actionlimit] ([Action_id], [LimitType_id], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[actionlimit] ([Action_id], [LimitType_id], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('UNIFIED_TRANSFER_CREATE', 'MIN_TRANSACTION_LIMIT', '1.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[actionlimit] ([Action_id], [LimitType_id], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', GETDATE(), GETDATE(), GETDATE(), '0');
GO
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce03c-2286-11ec-9621-0242ac130002', 'DEFAULT_GROUP', 'UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce4d8-2286-11ec-9621-0242ac130002', 'DEFAULT_GROUP', 'UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce5e6-2286-11ec-9621-0242ac130002', 'DEFAULT_GROUP', 'UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce6ae-2286-11ec-9621-0242ac130002', 'GROUP_ADMINISTRATOR', 'UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce76c-2286-11ec-9621-0242ac130002', 'GROUP_ADMINISTRATOR', 'UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[groupactionlimit] ([id], [Group_id], [Action_id], [LimitType_id], [value], [createdby], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce82a-2286-11ec-9621-0242ac130002', 'GROUP_ADMINISTRATOR', 'UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', 'UID11', GETDATE(), GETDATE(), GETDATE(), '0');

GO
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce8e8-2286-11ec-9621-0242ac130002', '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ce99c-2286-11ec-9621-0242ac130002', '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07cea5a-2286-11ec-9621-0242ac130002', '707dfea8-d0fe-4154-89c3-e7d7ef2ee16a', 'UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07cec80-2286-11ec-9621-0242ac130002', '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ced52-2286-11ec-9621-0242ac130002', '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07cee06-2286-11ec-9621-0242ac130002', '83c9b8d7-3715-480e-8c7d-3d6e61c00035', 'UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07ceeba-2286-11ec-9621-0242ac130002', '5801fa32-a416-45b6-af01-b22e2de93777', 'UNIFIED_TRANSFER_CREATE', 'MAX_TRANSACTION_LIMIT', '500.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07cef6e-2286-11ec-9621-0242ac130002', '5801fa32-a416-45b6-af01-b22e2de93777', 'UNIFIED_TRANSFER_CREATE', 'WEEKLY_LIMIT', '5000.00', GETDATE(), GETDATE(), GETDATE(), '0');
INSERT INTO [${dbxschemaname}].[servicedefinitionactionlimit] ([id], [serviceDefinitionId], [actionId], [limitTypeId], [value], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES ('c07cf022-2286-11ec-9621-0242ac130002', '5801fa32-a416-45b6-af01-b22e2de93777', 'UNIFIED_TRANSFER_CREATE', 'DAILY_LIMIT', '1000.00', GETDATE(), GETDATE(), GETDATE(), '0');
GO