INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'369', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_REQUESTED_LOAN_TERM_MIN', N'Configuration for minimum allowed requested Bridge Loan term', N'1', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'370', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_REQUESTED_LOAN_TERM_MAX', N'Configuration for maximum allowed requested Bridge Loan term', N'12', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'371', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_PURPOSE', N'Dropdown values - Purpose of Bridge Loan', N'["Fund purchase of new residential property", "Renovation of new residential property", "Renovation of existing property", "Others"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'372', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_SOURCE_OF_REPAYMENT', N'Dropdown values - Source of Repayment of Bride Loan', N'["Sale of Old Property", "Sale of Other Asset", "Maturity of Term Deposit"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'373', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_REPAYMENT_TYPE', N'Dropdown values - Repayment Type of Bridge Loan', N'["Interest Only"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'374', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_EXISTING_MORTGAGE_STATUS', N'Radio button options - question on any existing mortgage present on collateral used for Bridge Loan', N'["Yes, Mortgage is held with this bank", "Yes, Mortgage is held with external bank", "No"]', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration]) VALUES ('4e31aghi9-0019-4c3b-876d-b3a19eaca3bc', 'INFINITY_ASSIST_CONFIG_BUNDLE', 'PREFERENCE', 'PROPERTY_VALUATION_VALUE', 'Property valuation value', '{\"valuation_percentage\" : \"80\"}', 'CLIENT', '1');

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'375', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'BRIDGE_LOAN_DOC_CHECKLIST', N'List of documents for bridge loan', N'&emsp; 1.Proof of Identity\r\n&emsp;&emsp; a.Tax ID(mandatory)\r\n&emsp;&emsp; b.The ID which is entered under ID section to be pre populated\r\n(Any one document from below is Mandatory)\r\n&emsp;&emsp;&emsp;&emsp;  i. Driving License\r\n&emsp;&emsp;&emsp; &emsp; ii.Passport\r\n&emsp;&emsp;&emsp;&emsp;iii.Employee ID\r\n&emsp;&emsp;&emsp;&emsp; iv.Photo ID card issued by Local Government  <br>\r\n&emsp;2.Proof of Address : (Any one document from below is Mandatory)   \r\n&emsp;&emsp; a.Driving License    \r\n&emsp;&emsp; b.Passport    \r\n&emsp;&emsp; c.Utility Bills    \r\n&emsp;&emsp; d.Employer/HR letter   \r\n&emsp;&emsp; e.House Rent Contract <br>\r\n&emsp; 3.Proof of Income :    \r\n&emsp;&emsp;  a.For Status (Employment Status) - Salaried (Full Time Employee, Part Time Employee, Contract Employee, Casual Employee)    \r\n&emsp;&emsp;  &emsp;&emsp;     i.Pay-slips(mandatory) \r\n&emsp;&emsp;&emsp;    &emsp;  ii.Salary Account statement ( optional)    \r\n&emsp;&emsp; b.For Status(Employment Status) - Non-Salaried (Self-Employed, Retired,\r\n&emsp;&emsp;&emsp;Unemployed, Trainee)    \r\n&emsp;&emsp;&emsp;  &emsp;   i.Tax Return Statements(mandatory) \r\n&emsp;&emsp;&emsp;&emsp;   ii.Account Statements ( optional) <br>\r\n&emsp; 4.Supporting financial documents :    \r\n&emsp;&emsp; a.Bank statements    \r\n&emsp;&emsp; b.Credit card statement    \r\n&emsp;&emsp; c.Proof of deposit    \r\n&emsp;&emsp; d.Proof of Assets   \r\n&emsp;&emsp; e.Car finance agreement   \r\n&emsp;&emsp; f.Loan statements held with third parties <br>\r\n&emsp; 5.Product Document: Bridge Loan : (Add below documents if available) (Optional) \r\n&emsp;&emsp;  a.Mortgage Loan Outstanding Statement  \r\n&emsp;&emsp;  b.Consent for Second Charge    \r\n&emsp;&emsp;  c.Additional Mortgage Document    \r\n&emsp;&emsp;  d.Existing loan - Repayment Schedule <br>\r\n&emsp; 6.Property Document : (Add below documents if available) (Optional) \r\n&emsp;&emsp;    a.Sale Agreement    \r\n&emsp;&emsp;    b.Sale Deed    \r\n&emsp;&emsp;    c.Parent Document \r\n&emsp;&emsp;    d.Plan Approval/Layout Approval    \r\n&emsp;&emsp; e.Property Tax Receipt    \r\n&emsp;&emsp;   f.Electricity, Water and Drainage Certificate/Receipt', N'CLIENT', '1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'eb1c78c2-af07-4d4-b7db-bcd5febe184', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'ADDITIONAL_QUESTIONS_SECTION_BRIDGE_LOAN', N'Configuration for Additional Questions in Bridge loan', N'{"bridgeLoanConfig":{"Dropdown":{"question":"What is the purpose of this Bridge loan?","answers":[{"ans1":"Fund purchase of new residential property ","ans2":"Renovation of new residential property","ans3":"Renovation of existing property","ans4":"Others"}]},"Radio":{"question":"Is the mortgage application for your new residential property held with this bank?","Options":["Yes","No"]},"Note":"Please login with the Existing credentials to connect bridge loan with Existing Loan","enableBridgeLoan":"true","isBridgeLoan":true,"productID":"BRIDGE.LOAN"}}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'69b5dc53-3754-41eb-bda7-cc02d2e40544567', N'NUO_CONFIG_BUNDLE',N'PREFERENCE',N'BRIDGE_LOAN_PRODUCT_CONFIG','Configuration for Bridge loan Product details',N'{\"DefaultProduct\":{\"ProductLineId\":\"PL222830PUDL\",\"ProductId\": \"PR22335ORQFR\",\"ProductRef\": \"BRIDGE.LOAN\",\"ProductLineRef\":\"FACILITY\",\"ProductLineDisplayName\":\"Facility\",\"ProductGroupId\":\"PG22283MQTO7\",\"ProductGroupRef\":\"MORTGAGES\",\"ProductCurrencyId\":\"USD\",\"ProductGroupDisplayName\":\"Mortgage\",\"ProductName\":\"Bridge Loan\",\"ProductDescription\":{\"description\":\"Fast and flexible residential finance to help you bridge the gap\",\"detailedDesc\":\"A bridge loan is a short-term loan used to bridge the gap \\\"in funding a new mortgage loan or use the funds for home renovation or home improvement.\\\"\",\"notes\":\"Bridge loans are fast to arrange.|+|Bridge loans have flexible lending criteria.|+|Can be arranged as second charge.\",\"termsConditions\":\"\",\"disclosure\":\"\",\"extensionData\":{}}}}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

UPDATE [${dbxschemaname}].[configurations] SET config_value = N'false' WHERE (configuration_id = '126');
UPDATE [${dbxschemaname}].[configurations] SET config_value = N'false' WHERE (configuration_id = 'SME_18');

UPDATE [${dbxschemaname}].[configurations] SET config_value= N'[CREDIT.CARDS,OVERDRAFT.ACCOUNTS,PERSONAL.LOANS,MORTGAGES,MORTGAGE.FACILITIES,BRIDGE]' WHERE (configuration_id = '20c01647-2d15-4e77-9a8c-0f75bbeb065b' AND config_key='INCOME_EMPLOYMENT_REQUIRED');

UPDATE [${dbxschemaname}].[configurations] SET config_value= '[CREDIT.CARDS,OVERDRAFT.ACCOUNTS,PERSONAL.LOANS,MORTGAGES,MORTGAGE.FACILITIES,BRIDGE]' WHERE (configuration_id = 'fab6e31f-052e-451e-83c5-b2d2dd9d92c9');

UPDATE [${dbxschemaname}].[configurations] SET config_value= N'{\"bridgeLoanConfig\":{\"Dropdown\":{\"question\":\"What is the purpose of this Bridge loan?\",\"answers\":[{\"ans1\":\"Fund purchase of new residential property \",\"ans2\":\"Renovation of new residential property\",\"ans3\":\"Renovation of existing property\",\"ans4\":\"Others\"}]},\"Radio\":{\"question\":\"Is the mortgage application for your new residential property held with this bank?\",\"Options\":[\"Yes\",\"No\"]},\"Note\":\"Please login with the Existing credentials to connect bridge loan with Existing Loan\",\"enableBridgeLoan\":\"true\",\"isBridgeLoan\":true,\"productID\":\"BRIDGE.LOAN\",\"interestRate\":\"5\"}}' WHERE (configuration_id = 'eb1c78c2-af07-4d4-b7db-bcd5febe184');
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'390', N'NUO_CONFIG_BUNDLE', N'PREFERENCE', N'COAPPLICANT_OFFER_CONSENT_NOTIFY_CONFIG', N'Config to set recipients and notification type for the notification received by coApplicant after main applicant accepts offer.', N'{"notifyRecipients" : "CO_APPLICANT","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO [${dbxschemaname}].[configurations] ([configuration_id], [bundle_id], [config_type], [config_key], [description], [config_value], [target], [isPreLoginConfiguration], [createdts], [lastmodifiedts], [synctimestamp], [softdeleteflag]) VALUES (N'391', N'NUO_CONFIG_SME_BUNDLE', N'PREFERENCE', N'COAPPLICANT_OFFER_CONSENT_NOTIFY_CONFIG_SME', N'Config to set recipients and notification type for the notification received by coApplicant after main applicant accepts offer.', N'{"notifyRecipients" : "CO_APPLICANT","notificationType" : "EMAIL"}', 'CLIENT', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
GO

UPDATE [${dbxschemaname}].[configurations] SET [config_value] = '&emsp; 1.Proof of Identity\r\n&emsp;&emsp; a.Tax ID(mandatory)\r\n&emsp;&emsp; b.The ID which is entered under ID section to be pre populated\r\n(Any one document from below is Mandatory)\r\n&emsp;&emsp;&emsp;&emsp;  i. Driving License\r\n&emsp;&emsp;&emsp; &emsp; ii.Passport\r\n&emsp;&emsp;&emsp;&emsp; iii.Employee ID\r\n&emsp;&emsp;&emsp;&emsp; iv.Photo ID card issued by Local Government  <br>\r\n&emsp;2.Proof of Address : (Any one document from below is Mandatory)   \r\n&emsp;&emsp; a.Driving License    \r\n&emsp;&emsp; b.Passport    \r\n&emsp;&emsp; c.Utility Bills    \r\n&emsp;&emsp; d.Employer/HR letter   \r\n&emsp;&emsp; e.House Rent Contract <br>\r\n&emsp; 3.Proof of Income :    \r\n&emsp;&emsp;  a.For Status (Employment Status) - Salaried (Full Time Employee, Part Time Employee, Contract Employee, Casual Employee)    \r\n&emsp;&emsp;  &emsp;&emsp;     i.Pay-slips(mandatory) \r\n&emsp;&emsp;&emsp;    &emsp;  ii.Salary Account statement ( optional)    \r\n&emsp;&emsp; b.For Status(Employment Status) - Non-Salaried (Self-Employed, Retired,\r\n&emsp;&emsp;&emsp;Unemployed, Trainee)    \r\n&emsp;&emsp;&emsp;  &emsp;   i.Tax Return Statements(mandatory) \r\n&emsp;&emsp;&emsp;&emsp;   ii.Account Statements ( optional) <br>\r\n&emsp; 4.Supporting financial documents :    \r\n&emsp;&emsp; a.Bank statements    \r\n&emsp;&emsp; b.Credit card statement    \r\n&emsp;&emsp; c.Proof of deposit    \r\n&emsp;&emsp; d.Proof of Assets   \r\n&emsp;&emsp; e.Car finance agreement   \r\n&emsp;&emsp; f.Loan statements held with third parties <br>\r\n&emsp; 5.Product Document: Bridge Loan : (Add below documents if available) (Optional) \r\n&emsp;&emsp;  a.Mortgage Loan Outstanding Statement  \r\n&emsp;&emsp;  b.Consent for Second Charge    \r\n&emsp;&emsp;  c.Additional Mortgage Document    \r\n&emsp;&emsp;  d.Existing loan - Repayment Schedule <br>\r\n&emsp; 6.Property Document : (Add below documents if available) (Optional) \r\n&emsp;&emsp;    a.Sale Agreement    \r\n&emsp;&emsp;    b.Sale Deed    \r\n&emsp;&emsp;    c.Parent Document \r\n&emsp;&emsp;    d.Plan Approval/Layout Approval    \r\n&emsp;&emsp;    e.Property Tax Receipt    \r\n&emsp;&emsp;    f.Electricity, Water and Drainage Certificate/Receipt' WHERE ([configuration_id] = N'375');