package com.hbl.transactionlimitsengine.constants;

import java.util.HashMap;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.dbp.transactionslimitengine.businessdelegate.impl.TransactionsLimitBusinessDelegateImpl;
import com.dbp.transactionslimitengine.utils.TransactionDBConstants;


public enum HBL_FEATUREENUM {


		P2PTRANSFERS, INTRABANKTRANSFERS, WIRETRANSFERS, INTERBANKFUNDTRANSFERS, INTERNATIONALFUNDTRANSFERS,
		BILLPAYTRANSFERS, ACHTRANSACTION, ACHFILE, OWNACCOUNTTRANSFERS,BULK_PAYMENT_REQUEST_SUBMIT,BULK_PAYMENT_SINGLE_SUBMIT,BULK_PAYMENT_MULTIPLE_SUBMIT,
		ORDER_BLOTTER_OPEN_ORDER_CREATE,UNIFIED_TRANSFER_CREATE,WEALTH_CASH_MGMT_CURRENCY_COVERSION_CREATE,WEALTH_CASH_MGMT_TRANSFER_CASH_CREATE,
		WEALTH_ORDER_MGMT_BUY_ORDER_CREATE,WEALTH_ORDER_MGMT_ORDER_CANCEL,WEALTH_ORDER_MGMT_ORDER_EDIT,WEALTH_ORDER_MGMT_SELL_ORDER_CREATE;
		private static final Logger logger = LogManager.getLogger(TransactionsLimitBusinessDelegateImpl.class);
		// static final Properties
		static final Map<String, HBL_FEATUREENUM> OPERATIONS_MAPPER = getMapper();

		public static String getDBServiceKey(String featureid) {
			if (OPERATIONS_MAPPER.get(featureid) == null)
				return null;

			logger.debug(TransactionDBConstants.dbservicemap);
			logger.debug(OPERATIONS_MAPPER.get(featureid));
			logger.debug(TransactionDBConstants.dbservicemap.get(OPERATIONS_MAPPER.get(featureid).toString()));
			return TransactionDBConstants.dbservicemap.get(OPERATIONS_MAPPER.get(featureid).toString());
		}

		
		public static Map<String, HBL_FEATUREENUM> getMapper() {
			Map<String, HBL_FEATUREENUM> map = new HashMap<>();
			map.put("BILL_PAY_CREATE", HBL_FEATUREENUM.BILLPAYTRANSFERS);
			map.put("P2P_CREATE", HBL_FEATUREENUM.P2PTRANSFERS);
			map.put("INTRA_BANK_FUND_TRANSFER_CREATE", HBL_FEATUREENUM.INTRABANKTRANSFERS);
			map.put("DOMESTIC_WIRE_TRANSFER_CREATE", HBL_FEATUREENUM.WIRETRANSFERS);
			map.put("INTERNATIONAL_WIRE_TRANSFER_CREATE", HBL_FEATUREENUM.WIRETRANSFERS);
			map.put("INTER_BANK_ACCOUNT_FUND_TRANSFER_CREATE", HBL_FEATUREENUM.INTERBANKFUNDTRANSFERS);
			map.put("INTERNATIONAL_ACCOUNT_FUND_TRANSFER_CREATE", HBL_FEATUREENUM.INTERNATIONALFUNDTRANSFERS);
			map.put("ACH_PAYMENT_CREATE", HBL_FEATUREENUM.ACHTRANSACTION);
			map.put("ACH_COLLECTION_CREATE", HBL_FEATUREENUM.ACHTRANSACTION);
			map.put("ACH_FILE_UPLOAD", HBL_FEATUREENUM.ACHFILE);
			map.put("TRANSFER_BETWEEN_OWN_ACCOUNT_CREATE", HBL_FEATUREENUM.OWNACCOUNTTRANSFERS);
			map.put("BULK_PAYMENT_REQUEST_SUBMIT", HBL_FEATUREENUM.BULK_PAYMENT_REQUEST_SUBMIT);
			map.put("BULK_PAYMENT_SINGLE_SUBMIT", HBL_FEATUREENUM.BULK_PAYMENT_SINGLE_SUBMIT);
			map.put("BULK_PAYMENT_MULTIPLE_SUBMIT", HBL_FEATUREENUM.BULK_PAYMENT_MULTIPLE_SUBMIT);
			
			map.put("ORDER_BLOTTER_OPEN_ORDER_CREATE", HBL_FEATUREENUM.ORDER_BLOTTER_OPEN_ORDER_CREATE);
			map.put("UNIFIED_TRANSFER_CREATE", HBL_FEATUREENUM.UNIFIED_TRANSFER_CREATE);
			map.put("WEALTH_CASH_MGMT_CURRENCY_COVERSION_CREATE", HBL_FEATUREENUM.WEALTH_CASH_MGMT_CURRENCY_COVERSION_CREATE);
			map.put("WEALTH_CASH_MGMT_TRANSFER_CASH_CREATE", HBL_FEATUREENUM.WEALTH_CASH_MGMT_TRANSFER_CASH_CREATE);
			map.put("WEALTH_ORDER_MGMT_BUY_ORDER_CREATE", HBL_FEATUREENUM.WEALTH_ORDER_MGMT_BUY_ORDER_CREATE);
			map.put("WEALTH_ORDER_MGMT_ORDER_CANCEL", HBL_FEATUREENUM.WEALTH_ORDER_MGMT_ORDER_CANCEL);
			map.put("WEALTH_ORDER_MGMT_ORDER_EDIT", HBL_FEATUREENUM.WEALTH_ORDER_MGMT_ORDER_EDIT);
			map.put("WEALTH_ORDER_MGMT_SELL_ORDER_CREATE", HBL_FEATUREENUM.WEALTH_ORDER_MGMT_SELL_ORDER_CREATE);
			return map;
		}
	}

